-- FICONTER Global Currency Engine — Phase 3
-- Exchange-rate cache and provider resilience.
-- ADDITIVE ONLY: no financial amount is rewritten.

begin;

create table if not exists public.fx_rate_cache (
  id bigint generated by default as identity primary key,
  base_currency text not null check (base_currency ~ '^[A-Z]{3}$'),
  quote_currency text not null check (quote_currency ~ '^[A-Z]{3}$'),
  requested_date date not null,
  rate_date date not null,
  rate numeric(28,12) not null check (rate > 0),
  source text not null default 'Frankfurter reference rate',
  fetched_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  unique (base_currency, quote_currency, requested_date)
);

create index if not exists fx_rate_cache_pair_date_idx
  on public.fx_rate_cache (base_currency, quote_currency, rate_date desc);

comment on table public.fx_rate_cache is
  'Shared non-user-specific FX reference-rate cache used by the FICONTER Currency Engine. It stores no customer financial records.';

comment on column public.fx_rate_cache.requested_date is
  'Date requested by FICONTER. Weekend/holiday requests may resolve to a provider rate_date from the nearest available reference-rate day.';

alter table public.fx_rate_cache enable row level security;

-- No client policies are intentionally created. Reads/writes happen only
-- through authenticated server API code using the service role.

notify pgrst, 'reload schema';

commit;
