import {
  Activity,
  ArrowLeftRight,
  Baby,
  BadgeDollarSign,
  Banknote,
  BedDouble,
  Bike,
  Bitcoin,
  BookOpen,
  BriefcaseBusiness,
  Building2,
  Bus,
  Calculator,
  Camera,
  Car,
  CircleDollarSign,
  CircleParking,
  Cloud,
  Coffee,
  Coins,
  CreditCard,
  Droplets,
  Dumbbell,
  Eye,
  Factory,
  FileText,
  Flame,
  Fuel,
  Gamepad2,
  Gem,
  Gift,
  GraduationCap,
  HandCoins,
  HeartPulse,
  Home,
  Hospital,
  Landmark,
  Laptop,
  Mail,
  Megaphone,
  Music,
  Package,
  Palette,
  PawPrint,
  Phone,
  PiggyBank,
  Pill,
  Plane,
  ReceiptText,
  RefreshCw,
  Route,
  Scale,
  Scissors,
  ShieldCheck,
  Shirt,
  ShoppingBag,
  ShoppingCart,
  Smartphone,
  Sparkles,
  Stethoscope,
  Ticket,
  Train,
  Trash2,
  TrendingUp,
  Truck,
  Tv,
  Users,
  Utensils,
  WalletCards,
  Wifi,
  Wine,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";
import { CATEGORY_ITEMS } from "@/lib/financialOptions";

export const DEFAULT_TRANSACTION_ICON: LucideIcon = CircleDollarSign;

/**
 * Canonical visual vocabulary for FICONTER transactions.
 *
 * Every category offered by financialOptions.ts is deliberately assigned an
 * icon here. The ledger must not infer icons from free-text descriptions.
 */
export const TRANSACTION_CATEGORY_ICON_BY_NAME: Record<string, LucideIcon> = {
  // Income and earnings
  "Salary": BriefcaseBusiness,
  "Wages": Banknote,
  "Overtime": BriefcaseBusiness,
  "Bonus": BadgeDollarSign,
  "Commission": HandCoins,
  "Tips": Coins,
  "Freelance": Laptop,
  "Consulting": Users,
  "Business revenue": BriefcaseBusiness,
  "Rental income": Home,
  "Interest": Landmark,
  "Dividends": TrendingUp,
  "Capital gains": TrendingUp,
  "Royalties": FileText,
  "Pension": PiggyBank,
  "Government benefits": Landmark,
  "Child benefit": Baby,
  "Unemployment benefit": Banknote,
  "Scholarship": GraduationCap,
  "Alimony received": HandCoins,
  "Child support received": Baby,
  "Gift received": Gift,
  "Inheritance": Gem,
  "Refund": RefreshCw,
  "Reimbursement": ReceiptText,
  "Cashback": CreditCard,
  "Insurance payout": ShieldCheck,
  "Other income": BadgeDollarSign,

  // Home and housing
  "Rent": Home,
  "Mortgage": Landmark,
  "Property tax": Calculator,
  "Home insurance": ShieldCheck,
  "Home repairs": Wrench,
  "Home maintenance": Wrench,
  "Furniture": Home,
  "Home appliances": Zap,
  "Home improvement": Wrench,
  "Cleaning supplies": Sparkles,
  "Cleaning service": Sparkles,
  "Garden": Home,
  "Security system": ShieldCheck,
  "Storage": Package,
  "HOA / service charges": Building2,
  "Moving costs": Truck,

  // Utilities and communications
  "Electricity": Zap,
  "Gas": Flame,
  "Water": Droplets,
  "Heating": Flame,
  "Waste / recycling": Trash2,
  "Internet": Wifi,
  "Mobile phone": Smartphone,
  "Landline": Phone,
  "TV licence": Tv,
  "Cable / satellite": Tv,
  "Cloud storage": Cloud,
  "Postage": Mail,

  // Food and drink
  "Groceries": ShoppingCart,
  "Restaurants": Utensils,
  "Takeaway / delivery": Truck,
  "Coffee": Coffee,
  "Work meals": Utensils,
  "Snacks": ShoppingBag,
  "Alcohol": Wine,
  "Meal subscriptions": ReceiptText,
  "Specialty food": Utensils,

  // Transport and mobility
  "Public transport": Bus,
  "Fuel": Fuel,
  "Car payment": Car,
  "Car insurance": ShieldCheck,
  "Car maintenance": Wrench,
  "Car repairs": Wrench,
  "Parking": CircleParking,
  "Tolls": Route,
  "Taxi / rideshare": Car,
  "Bicycle": Bike,
  "Scooter": Bike,
  "Vehicle registration": FileText,
  "Driving licence": FileText,
  "Car wash": Sparkles,
  "Rental car": Car,
  "Flights": Plane,
  "Rail travel": Train,

  // Health and wellbeing
  "Health insurance": ShieldCheck,
  "Doctor": Stethoscope,
  "Dentist": Stethoscope,
  "Hospital": Hospital,
  "Pharmacy": Pill,
  "Medication": Pill,
  "Therapy": HeartPulse,
  "Optician": Eye,
  "Physiotherapy": Activity,
  "Medical devices": Activity,
  "Gym": Dumbbell,
  "Fitness classes": Dumbbell,
  "Sports": Activity,
  "Wellness": HeartPulse,
  "Supplements": Pill,
  "Personal trainer": Dumbbell,

  // Personal care and clothing
  "Clothing": Shirt,
  "Shoes": ShoppingBag,
  "Accessories": ShoppingBag,
  "Haircut": Scissors,
  "Beauty": Sparkles,
  "Cosmetics": Sparkles,
  "Skincare": Sparkles,
  "Toiletries": ShoppingBag,
  "Laundry / dry cleaning": Shirt,
  "Jewellery": Gem,
  "Tailoring": Scissors,

  // Family and children
  "Childcare": Baby,
  "School fees": GraduationCap,
  "School supplies": BookOpen,
  "Children's clothing": Shirt,
  "Baby supplies": Baby,
  "Toys": Gamepad2,
  "Activities": Activity,
  "Pocket money": Coins,
  "Child support paid": Baby,
  "Alimony paid": HandCoins,
  "Elder care": HeartPulse,
  "Family support": Users,

  // Education and professional
  "Tuition": GraduationCap,
  "Courses": GraduationCap,
  "Books": BookOpen,
  "Software": Laptop,
  "Professional membership": Users,
  "Certification": FileText,
  "Conference": Users,
  "Work equipment": BriefcaseBusiness,
  "Office supplies": FileText,
  "Coworking": Building2,
  "Career coaching": Users,
  "Language learning": BookOpen,

  // Entertainment and lifestyle
  "Streaming": Tv,
  "Music": Music,
  "Cinema": Ticket,
  "Gaming": Gamepad2,
  "Books / magazines": BookOpen,
  "Hobbies": Palette,
  "Events": Ticket,
  "Concerts": Music,
  "Museums": Building2,
  "Nightlife": Wine,
  "Photography": Camera,
  "Crafts": Palette,
  "Electronics": Smartphone,
  "Apps": Smartphone,
  "Social clubs": Users,

  // Travel and holidays
  "Accommodation": BedDouble,
  "Train tickets": Train,
  "Local transport": Bus,
  "Travel insurance": ShieldCheck,
  "Food while travelling": Utensils,
  "Tours / attractions": Ticket,
  "Visa / passport": FileText,
  "Luggage": Package,
  "Currency exchange fee": ArrowLeftRight,
  "Holiday shopping": ShoppingBag,

  // Pets
  "Pet food": PawPrint,
  "Veterinary": Stethoscope,
  "Pet insurance": ShieldCheck,
  "Grooming": Scissors,
  "Pet supplies": PawPrint,
  "Pet care / boarding": PawPrint,
  "Pet training": Activity,

  // Financial obligations
  "Income tax": Calculator,
  "Business tax": Calculator,
  "Bank fees": Landmark,
  "Interest charges": BadgeDollarSign,
  "Credit-card payment": CreditCard,
  "Personal-loan payment": Landmark,
  "Student-loan payment": GraduationCap,
  "Mortgage principal": Home,
  "Debt repayment": Landmark,
  "Late fee": ReceiptText,
  "Fine / penalty": ReceiptText,
  "Legal fees": Scale,
  "Accounting fees": Calculator,

  // Saving and investing
  "Emergency fund": ShieldCheck,
  "General savings": PiggyBank,
  "Holiday savings": Plane,
  "House deposit": Home,
  "Retirement": PiggyBank,
  "Stocks": TrendingUp,
  "ETFs": TrendingUp,
  "Bonds": Landmark,
  "Mutual funds": TrendingUp,
  "Crypto": Bitcoin,
  "Precious metals": Coins,
  "Property investment": Building2,
  "Business investment": BriefcaseBusiness,
  "Education fund": GraduationCap,
  "Investment fees": ReceiptText,

  // Gifts, charity and community
  "Gifts": Gift,
  "Birthday": Gift,
  "Wedding": Gem,
  "Holiday gifts": Gift,
  "Charity": Gift,
  "Religious giving": Gift,
  "Community support": Users,
  "Political contribution": Landmark,

  // Business and self-employment
  "Inventory": Package,
  "Materials": Package,
  "Manufacturing": Factory,
  "Shipping": Truck,
  "Advertising": Megaphone,
  "Marketing": Megaphone,
  "Website": Laptop,
  "Domain / hosting": Cloud,
  "Business software": Laptop,
  "Contractors": Users,
  "Employee payroll": Banknote,
  "Business insurance": ShieldCheck,
  "Business travel": Plane,
  "Client entertainment": Utensils,
  "Equipment": Wrench,
  "Licences / permits": FileText,

  // Transfers and adjustments
  "Account transfer": ArrowLeftRight,
  "Cash deposit": Banknote,
  "Cash withdrawal": Banknote,
  "Opening balance": WalletCards,
  "Balance correction": Calculator,
  "Currency conversion": ArrowLeftRight,
  "Refund adjustment": RefreshCw,
  "Other / custom": CircleDollarSign,
};

export const TRANSACTION_TYPE_ICON_BY_VALUE: Record<string, LucideIcon> = {
  expense: ReceiptText,
  income: BadgeDollarSign,
  saving: PiggyBank,
};

const NORMALIZED_CATEGORY_ICON_BY_NAME = Object.fromEntries(
  Object.entries(TRANSACTION_CATEGORY_ICON_BY_NAME).map(([category, Icon]) => [
    category.trim().toLowerCase(),
    Icon,
  ]),
) as Record<string, LucideIcon>;

export const CANONICAL_TRANSACTION_ICON_COVERAGE = {
  total: CATEGORY_ITEMS.length,
  mapped: CATEGORY_ITEMS.filter((category) => Boolean(TRANSACTION_CATEGORY_ICON_BY_NAME[category])).length,
  missing: CATEGORY_ITEMS.filter((category) => !TRANSACTION_CATEGORY_ICON_BY_NAME[category]),
} as const;

export function transactionIconFor(input: {
  category?: string | null;
  type?: string | null;
}): LucideIcon {
  const category = String(input.category ?? "").trim();
  if (category) {
    const exact = TRANSACTION_CATEGORY_ICON_BY_NAME[category];
    if (exact) return exact;

    const normalized = NORMALIZED_CATEGORY_ICON_BY_NAME[category.toLowerCase()];
    if (normalized) return normalized;
  }

  const type = String(input.type ?? "").trim().toLowerCase();
  return TRANSACTION_TYPE_ICON_BY_VALUE[type] ?? DEFAULT_TRANSACTION_ICON;
}
