export type CommandPaletteItem = {
  id: string;
  label: string;
  description: string;
  href: string;
  group: "Quick actions" | "Money management" | "Financial progress" | "Intelligence" | "Account & settings";
  keywords: string[];
};

export const FICONTER_COMMANDS: CommandPaletteItem[] = [
  {
    id: "add-expense",
    label: "Add an expense",
    description: "Open Effortless Entry with Expense selected.",
    href: "/dashboard/transactions?setup=expense",
    group: "Quick actions",
    keywords: ["new", "transaction", "spending", "cost", "purchase"],
  },
  {
    id: "add-income",
    label: "Add income",
    description: "Record salary or another source of income.",
    href: "/dashboard/transactions?setup=income",
    group: "Quick actions",
    keywords: ["salary", "earnings", "money in", "revenue"],
  },
  {
    id: "add-saving",
    label: "Add a saving",
    description: "Record money allocated to savings.",
    href: "/dashboard/transactions?setup=saving",
    group: "Quick actions",
    keywords: ["save", "reserve", "emergency", "contribution"],
  },
  {
    id: "overview",
    label: "Overview",
    description: "Return to your financial command centre.",
    href: "/dashboard/overview",
    group: "Money management",
    keywords: ["home", "dashboard", "summary", "financial health"],
  },
  {
    id: "transactions",
    label: "Transactions",
    description: "Open entry tools, imports and your transaction ledger.",
    href: "/dashboard/transactions",
    group: "Money management",
    keywords: ["ledger", "import", "statement", "file", "activity", "payments"],
  },
  {
    id: "bills",
    label: "Bills",
    description: "Review recurring obligations, due dates and payment status.",
    href: "/dashboard/bills",
    group: "Money management",
    keywords: ["payment", "overdue", "subscription", "recurring", "due"],
  },
  {
    id: "credit-cards",
    label: "Credit Cards",
    description: "Manage card balances, statements, interest and payments.",
    href: "/dashboard/credit-cards",
    group: "Money management",
    keywords: ["card", "apr", "minimum payment", "statement", "interest", "credit"],
  },
  {
    id: "debt",
    label: "Debt",
    description: "Review balances, repayments and debt progress.",
    href: "/dashboard/debt",
    group: "Money management",
    keywords: ["loan", "credit", "repayment", "liability", "balance"],
  },
  {
    id: "cash-flow",
    label: "Cash flow",
    description: "Review money coming in, going out and available surplus.",
    href: "/dashboard/cash-flow",
    group: "Money management",
    keywords: ["income", "expenses", "surplus", "inflow", "outflow"],
  },
  {
    id: "planner",
    label: "Monthly planner",
    description: "Plan the month, obligations and available capital.",
    href: "/dashboard/budget",
    group: "Money management",
    keywords: ["budget", "month", "capital", "plan", "left after everything"],
  },
  {
    id: "savings",
    label: "Savings Intelligence",
    description: "Review savings consistency, rate and progress.",
    href: "/dashboard/savings",
    group: "Financial progress",
    keywords: ["saving", "rate", "contribution", "reserve"],
  },
  {
    id: "goals",
    label: "Goals",
    description: "Open financial targets, deadlines and contributions.",
    href: "/dashboard/goals",
    group: "Financial progress",
    keywords: ["target", "objective", "milestone", "future", "purchase"],
  },
  {
    id: "emergency-fund",
    label: "Emergency Fund",
    description: "Review financial protection, buffer and coverage.",
    href: "/dashboard/emergency-fund",
    group: "Financial progress",
    keywords: ["buffer", "reserve", "protection", "months", "safety"],
  },
  {
    id: "net-worth",
    label: "Net Worth",
    description: "Review assets, liabilities, capital and growth.",
    href: "/dashboard/net-worth",
    group: "Financial progress",
    keywords: ["wealth", "assets", "liabilities", "capital", "growth"],
  },
  {
    id: "gps",
    label: "Financial GPS",
    description: "Open your current financial priority and action path.",
    href: "/dashboard/gps",
    group: "Intelligence",
    keywords: ["guidance", "priority", "next action", "direction", "plan"],
  },
  {
    id: "financial-independence",
    label: "Financial Independence",
    description: "Review the long-term financial independence path.",
    href: "/dashboard/financial-independence",
    group: "Intelligence",
    keywords: ["freedom", "retirement", "future", "independence"],
  },
  {
    id: "insights",
    label: "Smart Insights",
    description: "Open deterministic financial priorities and opportunities.",
    href: "/dashboard/insights",
    group: "Intelligence",
    keywords: ["analysis", "recommendation", "intelligence", "smart", "insight"],
  },
  {
    id: "ask-ficonter",
    label: "Ask FICONTER",
    description: "Open financial decision intelligence based on your FICONTER data.",
    href: "/dashboard/insights/ask-ficonter",
    group: "Intelligence",
    keywords: ["ask", "car", "lease", "buy", "afford", "financing", "decision", "recommendation"],
  },
  {
    id: "documents",
    label: "Documents",
    description: "Open your private financial documents workspace.",
    href: "/dashboard/documents",
    group: "Account & settings",
    keywords: ["files", "document", "upload", "pdf", "statement"],
  },
  {
    id: "messages",
    label: "Messages",
    description: "Open your FICONTER inbox and support conversations.",
    href: "/dashboard/inbox",
    group: "Account & settings",
    keywords: ["inbox", "message", "support", "notification", "conversation"],
  },
  {
    id: "profile",
    label: "Profile",
    description: "Manage your identity and profile information.",
    href: "/dashboard/settings?section=profile",
    group: "Account & settings",
    keywords: ["name", "address", "birthday", "country", "city", "personal"],
  },
  {
    id: "security",
    label: "Account & Security",
    description: "Manage login, password and account security options.",
    href: "/dashboard/settings?section=security",
    group: "Account & settings",
    keywords: ["password", "security", "email", "login", "account", "vault"],
  },
  {
    id: "financial-preferences",
    label: "Financial Preferences",
    description: "Manage base currency and financial preferences.",
    href: "/dashboard/settings?section=financial",
    group: "Account & settings",
    keywords: ["currency", "financial", "preferences", "eur", "money"],
  },
  {
    id: "notifications",
    label: "Notifications",
    description: "Manage FICONTER notification preferences.",
    href: "/dashboard/settings?section=notifications",
    group: "Account & settings",
    keywords: ["alerts", "notifications", "reminder", "messages"],
  },
  {
    id: "appearance",
    label: "Appearance",
    description: "Manage theme, wallpaper, density and interface appearance.",
    href: "/dashboard/settings?section=appearance",
    group: "Account & settings",
    keywords: ["theme", "dark", "light", "wallpaper", "opacity", "density", "interface"],
  },
  {
    id: "privacy",
    label: "Data & Privacy",
    description: "Review privacy, data and account controls.",
    href: "/dashboard/settings?section=privacy",
    group: "Account & settings",
    keywords: ["privacy", "data", "delete", "export", "backup", "encryption"],
  },
  {
    id: "subscription",
    label: "Subscription",
    description: "Review your FICONTER plan and subscription options.",
    href: "/dashboard/settings?section=subscription",
    group: "Account & settings",
    keywords: ["plan", "free", "personal pro", "business pro", "billing", "upgrade"],
  },
  {
    id: "settings",
    label: "Settings",
    description: "Open all FICONTER account and interface preferences.",
    href: "/dashboard/settings",
    group: "Account & settings",
    keywords: ["theme", "layout", "account", "preferences", "settings"],
  },
  {
    id: "help",
    label: "Help & Support",
    description: "Open FICONTER help and support resources.",
    href: "/dashboard/help",
    group: "Account & settings",
    keywords: ["help", "support", "faq", "contact", "question"],
  },
];
