export type CommandPaletteItem = {
  id: string;
  label: string;
  description: string;
  href: string;
  group: "Quick actions" | "Money management" | "Financial progress" | "Account";
  keywords: string[];
};

export const FICONTER_COMMANDS: CommandPaletteItem[] = [
  {
    id: "add-expense",
    label: "Add an expense",
    description: "Open Effortless Entry with Expense selected.",
    href: "/dashboard/transactions?setup=expense",
    group: "Quick actions",
    keywords: ["new", "transaction", "spending", "cost"],
  },
  {
    id: "add-income",
    label: "Add income",
    description: "Record salary or another source of income.",
    href: "/dashboard/transactions?setup=income",
    group: "Quick actions",
    keywords: ["salary", "earnings", "money in"],
  },
  {
    id: "add-saving",
    label: "Add a saving",
    description: "Record money allocated to savings.",
    href: "/dashboard/transactions?setup=saving",
    group: "Quick actions",
    keywords: ["save", "reserve", "emergency"],
  },
  {
    id: "overview",
    label: "Overview",
    description: "Return to your financial command centre.",
    href: "/dashboard",
    group: "Money management",
    keywords: ["home", "dashboard", "summary"],
  },
  {
    id: "gps",
    label: "Financial GPS",
    description: "Open your current priority and action path.",
    href: "/dashboard/gps",
    group: "Money management",
    keywords: ["guidance", "priority", "next action"],
  },
  {
    id: "transactions",
    label: "Transactions",
    description: "Open entry tools, imports and your ledger.",
    href: "/dashboard/transactions",
    group: "Money management",
    keywords: ["ledger", "import", "statement", "file"],
  },
  {
    id: "cash-flow",
    label: "Cash flow",
    description: "Review money coming in and going out.",
    href: "/dashboard/cash-flow",
    group: "Money management",
    keywords: ["income", "expenses", "surplus"],
  },
  {
    id: "planner",
    label: "Monthly planner",
    description: "Plan the current month and available capital.",
    href: "/dashboard/budget",
    group: "Money management",
    keywords: ["budget", "month", "capital"],
  },
  {
    id: "bills",
    label: "Bills",
    description: "Review recurring obligations and due dates.",
    href: "/dashboard/bills",
    group: "Money management",
    keywords: ["payment", "overdue", "subscription"],
  },
  {
    id: "emergency-fund",
    label: "Emergency fund",
    description: "Review financial protection and coverage.",
    href: "/dashboard/emergency-fund",
    group: "Financial progress",
    keywords: ["buffer", "reserve", "protection"],
  },
  {
    id: "savings",
    label: "Savings intelligence",
    description: "Review savings consistency and progress.",
    href: "/dashboard/savings",
    group: "Financial progress",
    keywords: ["saving", "rate", "contribution"],
  },
  {
    id: "debt",
    label: "Debt",
    description: "Review balances, payments and progress.",
    href: "/dashboard/debt",
    group: "Financial progress",
    keywords: ["loan", "credit", "repayment"],
  },
  {
    id: "credit-cards",
    label: "Credit Cards",
    description: "Manage card balances, statements, interest and payments.",
    href: "/dashboard/credit-cards",
    group: "Financial progress",
    keywords: ["card", "apr", "minimum payment", "statement", "interest"],
  },
  {
    id: "goals",
    label: "Goals",
    description: "Open financial targets and contributions.",
    href: "/dashboard/goals",
    group: "Financial progress",
    keywords: ["target", "investment", "objective"],
  },
  {
    id: "net-worth",
    label: "Net worth",
    description: "Review capital, liabilities and growth.",
    href: "/dashboard/net-worth",
    group: "Financial progress",
    keywords: ["wealth", "assets", "liabilities"],
  },
  {
    id: "financial-independence",
    label: "Financial independence",
    description: "Review the long-term independence path.",
    href: "/dashboard/financial-independence",
    group: "Financial progress",
    keywords: ["freedom", "retirement", "future"],
  },
  {
    id: "insights",
    label: "Smart insights",
    description: "Open deterministic priorities and opportunities.",
    href: "/dashboard/insights",
    group: "Financial progress",
    keywords: ["analysis", "recommendation", "intelligence"],
  },
  {
    id: "documents",
    label: "Documents",
    description: "Open your private financial document vault.",
    href: "/dashboard/documents",
    group: "Account",
    keywords: ["files", "vault", "upload"],
  },
  {
    id: "settings",
    label: "Settings",
    description: "Manage profile, appearance and preferences.",
    href: "/dashboard/settings",
    group: "Account",
    keywords: ["theme", "layout", "account", "preferences"],
  },
];
