import type { FiconterLanguage } from "./config";

type NonEnglishLanguage = Exclude<FiconterLanguage, "en">;
type TranslationRow = Record<NonEnglishLanguage, string>;

function row(de: string, es: string, sq: string, ar: string, pt: string, it: string, ru: string): TranslationRow {
  return { de, es, sq, ar, pt, it, ru };
}

export const GOVERNANCE_UI_TRANSLATIONS_BATCH_3: Record<string, TranslationRow> = {
  "Opening encrypted Business Administration…": row("Verschlüsselte Unternehmensverwaltung wird geöffnet…", "Abriendo la administración empresarial cifrada…", "Po hapet administrimi i enkriptuar i biznesit…", "جارٍ فتح إدارة الأعمال المشفرة…", "A abrir a Administração Empresarial encriptada…", "Apertura dell'Amministrazione aziendale crittografata…", "Открывается зашифрованное управление бизнесом…"),
  "Business Cost Control could not be opened.": row("Business Cost Control konnte nicht geöffnet werden.", "No se pudo abrir el control de costes empresariales.", "Kontrolli i kostove të biznesit nuk mund të hapej.", "تعذر فتح التحكم في تكاليف الأعمال.", "Não foi possível abrir o Controlo de Custos Empresariais.", "Non è stato possibile aprire il Controllo costi aziendali.", "Не удалось открыть контроль расходов бизнеса."),
  "Unlock your Financial Vault to open encrypted Business Cost Control.": row("Entsperren Sie Ihren Finanz-Tresor, um das verschlüsselte Business Cost Control zu öffnen.", "Desbloquea tu bóveda financiera para abrir el control de costes empresariales cifrado.", "Zhbllokoni kasafortën tuaj financiare për të hapur kontrollin e enkriptuar të kostove të biznesit.", "افتح خزنتك المالية لفتح التحكم المشفر في تكاليف الأعمال.", "Desbloqueie o seu Cofre Financeiro para abrir o Controlo de Custos Empresariais encriptado.", "Sblocca il tuo Caveau Finanziario per aprire il Controllo costi aziendali crittografato.", "Разблокируйте финансовое хранилище, чтобы открыть зашифрованный контроль расходов бизнеса."),
  "Opening encrypted Business Cost Control…": row("Verschlüsseltes Business Cost Control wird geöffnet…", "Abriendo el control de costes empresariales cifrado…", "Po hapet kontrolli i enkriptuar i kostove të biznesit…", "جارٍ فتح التحكم المشفر في تكاليف الأعمال…", "A abrir o Controlo de Custos Empresariais encriptado…", "Apertura del Controllo costi aziendali crittografato…", "Открывается зашифрованный контроль расходов бизнеса…"),
  "Encrypted Inventory could not be opened.": row("Das verschlüsselte Inventar konnte nicht geöffnet werden.", "No se pudo abrir el inventario cifrado.", "Inventari i enkriptuar nuk mund të hapej.", "تعذر فتح المخزون المشفر.", "Não foi possível abrir o inventário encriptado.", "Non è stato possibile aprire l'inventario crittografato.", "Не удалось открыть зашифрованный инвентарь."),
  "Unlock your Financial Vault to open encrypted Business Inventory.": row("Entsperren Sie Ihren Finanz-Tresor, um das verschlüsselte Unternehmensinventar zu öffnen.", "Desbloquea tu bóveda financiera para abrir el inventario empresarial cifrado.", "Zhbllokoni kasafortën tuaj financiare për të hapur inventarin e enkriptuar të biznesit.", "افتح خزنتك المالية لفتح مخزون الأعمال المشفر.", "Desbloqueie o seu Cofre Financeiro para abrir o Inventário Empresarial encriptado.", "Sblocca il tuo Caveau Finanziario per aprire l'inventario aziendale crittografato.", "Разблокируйте финансовое хранилище, чтобы открыть зашифрованный инвентарь бизнеса."),
  "Opening encrypted Business Inventory…": row("Verschlüsseltes Unternehmensinventar wird geöffnet…", "Abriendo el inventario empresarial cifrado…", "Po hapet inventari i enkriptuar i biznesit…", "جارٍ فتح مخزون الأعمال المشفر…", "A abrir o Inventário Empresarial encriptado…", "Apertura dell'inventario aziendale crittografato…", "Открывается зашифрованный инвентарь бизнеса…"),
  "Encrypted Business Overview could not be opened.": row("Die verschlüsselte Unternehmensübersicht konnte nicht geöffnet werden.", "No se pudo abrir el resumen empresarial cifrado.", "Përmbledhja e enkriptuar e biznesit nuk mund të hapej.", "تعذر فتح نظرة عامة مشفرة للأعمال.", "Não foi possível abrir a Visão Geral Empresarial encriptada.", "Non è stato possibile aprire la Panoramica aziendale crittografata.", "Не удалось открыть зашифрованный обзор бизнеса."),
  "Unlock your Financial Vault to open encrypted Business Overview.": row("Entsperren Sie Ihren Finanz-Tresor, um die verschlüsselte Unternehmensübersicht zu öffnen.", "Desbloquea tu bóveda financiera para abrir el resumen empresarial cifrado.", "Zhbllokoni kasafortën tuaj financiare për të hapur përmbledhjen e enkriptuar të biznesit.", "افتح خزنتك المالية لفتح نظرة عامة مشفرة للأعمال.", "Desbloqueie o seu Cofre Financeiro para abrir a Visão Geral Empresarial encriptada.", "Sblocca il tuo Caveau Finanziario per aprire la Panoramica aziendale crittografata.", "Разблокируйте финансовое хранилище, чтобы открыть зашифрованный обзор бизнеса."),
  "Opening encrypted Business Overview…": row("Verschlüsselte Unternehmensübersicht wird geöffnet…", "Abriendo el resumen empresarial cifrado…", "Po hapet përmbledhja e enkriptuar e biznesit…", "جارٍ فتح نظرة عامة مشفرة للأعمال…", "A abrir a Visão Geral Empresarial encriptada…", "Apertura della Panoramica aziendale crittografata…", "Открывается зашифрованный обзор бизнеса…"),
  "Business report could not be opened.": row("Der Unternehmensbericht konnte nicht geöffnet werden.", "No se pudo abrir el informe empresarial.", "Raporti i biznesit nuk mund të hapej.", "تعذر فتح تقرير الأعمال.", "Não foi possível abrir o relatório empresarial.", "Non è stato possibile aprire il report aziendale.", "Не удалось открыть отчёт по бизнесу."),
  "Unlock your Financial Vault to open encrypted Business Reports.": row("Entsperren Sie Ihren Finanz-Tresor, um die verschlüsselten Unternehmensberichte zu öffnen.", "Desbloquea tu bóveda financiera para abrir los informes empresariales cifrados.", "Zhbllokoni kasafortën tuaj financiare për të hapur raportet e enkriptuara të biznesit.", "افتح خزنتك المالية لفتح تقارير الأعمال المشفرة.", "Desbloqueie o seu Cofre Financeiro para abrir os Relatórios Empresariais encriptados.", "Sblocca il tuo Caveau Finanziario per aprire i report aziendali crittografati.", "Разблокируйте финансовое хранилище, чтобы открыть зашифрованные отчёты бизнеса."),
  "Building encrypted Business report…": row("Verschlüsselter Unternehmensbericht wird erstellt…", "Generando el informe empresarial cifrado…", "Po ndërtohet raporti i enkriptuar i biznesit…", "جارٍ إعداد تقرير الأعمال المشفر…", "A criar o relatório empresarial encriptado…", "Creazione del report aziendale crittografato…", "Создаётся зашифрованный отчёт по бизнесу…"),
  "Encrypted Sales could not be opened.": row("Verschlüsselte Verkaufsdaten konnten nicht geöffnet werden.", "No se pudieron abrir las ventas cifradas.", "Shitjet e enkriptuara nuk mund të hapeshin.", "تعذر فتح المبيعات المشفرة.", "Não foi possível abrir as vendas encriptadas.", "Non è stato possibile aprire le vendite crittografate.", "Не удалось открыть зашифрованные продажи."),
  "Unlock your Financial Vault to open encrypted Business Sales.": row("Entsperren Sie Ihren Finanz-Tresor, um die verschlüsselten Unternehmensverkäufe zu öffnen.", "Desbloquea tu bóveda financiera para abrir las ventas empresariales cifradas.", "Zhbllokoni kasafortën tuaj financiare për të hapur shitjet e enkriptuara të biznesit.", "افتح خزنتك المالية لفتح مبيعات الأعمال المشفرة.", "Desbloqueie o seu Cofre Financeiro para abrir as Vendas Empresariais encriptadas.", "Sblocca il tuo Caveau Finanziario per aprire le vendite aziendali crittografate.", "Разблокируйте финансовое хранилище, чтобы открыть зашифрованные продажи бизнеса."),
  "Opening encrypted Business Sales…": row("Verschlüsselte Unternehmensverkäufe werden geöffnet…", "Abriendo las ventas empresariales cifradas…", "Po hapen shitjet e enkriptuara të biznesit…", "جارٍ فتح مبيعات الأعمال المشفرة…", "A abrir as Vendas Empresariais encriptadas…", "Apertura delle vendite aziendali crittografate…", "Открываются зашифрованные продажи бизнеса…"),
  "Business Suppliers could not be opened.": row("Die Unternehmenslieferanten konnten nicht geöffnet werden.", "No se pudieron abrir los proveedores empresariales.", "Furnitorët e biznesit nuk mund të hapeshin.", "تعذر فتح موردي الأعمال.", "Não foi possível abrir os fornecedores empresariais.", "Non è stato possibile aprire i fornitori aziendali.", "Не удалось открыть поставщиков бизнеса."),
  "Unlock your Financial Vault to open encrypted Business Suppliers.": row("Entsperren Sie Ihren Finanz-Tresor, um die verschlüsselten Unternehmenslieferanten zu öffnen.", "Desbloquea tu bóveda financiera para abrir los proveedores empresariales cifrados.", "Zhbllokoni kasafortën tuaj financiare për të hapur furnitorët e enkriptuar të biznesit.", "افتح خزنتك المالية لفتح موردي الأعمال المشفرين.", "Desbloqueie o seu Cofre Financeiro para abrir os Fornecedores Empresariais encriptados.", "Sblocca il tuo Caveau Finanziario per aprire i fornitori aziendali crittografati.", "Разблокируйте финансовое хранилище, чтобы открыть зашифрованных поставщиков бизнеса."),
  "Opening encrypted Business Suppliers…": row("Verschlüsselte Unternehmenslieferanten werden geöffnet…", "Abriendo los proveedores empresariales cifrados…", "Po hapen furnitorët e enkriptuar të biznesit…", "جارٍ فتح موردي الأعمال المشفرين…", "A abrir os Fornecedores Empresariais encriptados…", "Apertura dei fornitori aziendali crittografati…", "Открываются зашифрованные поставщики бизнеса…"),
  "Business data could not be opened.": row("Unternehmensdaten konnten nicht geöffnet werden.", "No se pudieron abrir los datos empresariales.", "Të dhënat e biznesit nuk mund të hapeshin.", "تعذر فتح بيانات الأعمال.", "Não foi possível abrir os dados empresariais.", "Non è stato possibile aprire i dati aziendali.", "Не удалось открыть данные бизнеса."),
  "Unlock your Financial Vault to open encrypted Business data.": row("Entsperren Sie Ihren Finanz-Tresor, um die verschlüsselten Unternehmensdaten zu öffnen.", "Desbloquea tu bóveda financiera para abrir los datos empresariales cifrados.", "Zhbllokoni kasafortën tuaj financiare për të hapur të dhënat e enkriptuara të biznesit.", "افتح خزنتك المالية لفتح بيانات الأعمال المشفرة.", "Desbloqueie o seu Cofre Financeiro para abrir os dados empresariais encriptados.", "Sblocca il tuo Caveau Finanziario per aprire i dati aziendali crittografati.", "Разблокируйте финансовое хранилище, чтобы открыть зашифрованные данные бизнеса."),
  "Opening encrypted Business data…": row("Verschlüsselte Unternehmensdaten werden geöffnet…", "Abriendo los datos empresariales cifrados…", "Po hapen të dhënat e enkriptuara të biznesit…", "جارٍ فتح بيانات الأعمال المشفرة…", "A abrir os dados empresariais encriptados…", "Apertura dei dati aziendali crittografati…", "Открываются зашифрованные данные бизнеса…"),
  "Unlock your Financial Vault to open Cash Flow.": row("Entsperren Sie Ihren Finanz-Tresor, um den Cashflow zu öffnen.", "Desbloquea tu bóveda financiera para abrir el flujo de caja.", "Zhbllokoni kasafortën tuaj financiare për të hapur fluksin e parasë.", "افتح خزنتك المالية لفتح التدفق النقدي.", "Desbloqueie o seu Cofre Financeiro para abrir o Fluxo de Caixa.", "Sblocca il tuo Caveau Finanziario per aprire il flusso di cassa.", "Разблокируйте финансовое хранилище, чтобы открыть денежный поток."),
  "Opening Cash Flow…": row("Cashflow wird geöffnet…", "Abriendo flujo de caja…", "Po hapet fluksi i parasë…", "جارٍ فتح التدفق النقدي…", "A abrir o Fluxo de Caixa…", "Apertura del flusso di cassa…", "Открывается денежный поток…"),
  "Credit Card data could not be opened.": row("Kreditkartendaten konnten nicht geöffnet werden.", "No se pudieron abrir los datos de las tarjetas de crédito.", "Të dhënat e kartës së kreditit nuk mund të hapeshin.", "تعذر فتح بيانات بطاقة الائتمان.", "Não foi possível abrir os dados dos cartões de crédito.", "Non è stato possibile aprire i dati delle carte di credito.", "Не удалось открыть данные кредитных карт."),
  "Unlock your Financial Vault to open Credit Cards.": row("Entsperren Sie Ihren Finanz-Tresor, um Kreditkarten zu öffnen.", "Desbloquea tu bóveda financiera para abrir las tarjetas de crédito.", "Zhbllokoni kasafortën tuaj financiare për të hapur kartat e kreditit.", "افتح خزنتك المالية لفتح بطاقات الائتمان.", "Desbloqueie o seu Cofre Financeiro para abrir os Cartões de Crédito.", "Sblocca il tuo Caveau Finanziario per aprire le carte di credito.", "Разблокируйте финансовое хранилище, чтобы открыть кредитные карты."),
  "Opening Credit Card data…": row("Kreditkartendaten werden geöffnet…", "Abriendo los datos de las tarjetas de crédito…", "Po hapen të dhënat e kartës së kreditit…", "جارٍ فتح بيانات بطاقة الائتمان…", "A abrir os dados dos cartões de crédito…", "Apertura dei dati delle carte di credito…", "Открываются данные кредитных карт…"),
  "Encrypted Debt data could not be opened.": row("Verschlüsselte Schuldendaten konnten nicht geöffnet werden.", "No se pudieron abrir los datos de deuda cifrados.", "Të dhënat e enkriptuara të borxhit nuk mund të hapeshin.", "تعذر فتح بيانات الديون المشفرة.", "Não foi possível abrir os dados de dívida encriptados.", "Non è stato possibile aprire i dati dei debiti crittografati.", "Не удалось открыть зашифрованные данные долгов."),
  "Unlock your Financial Vault to open Debt.": row("Entsperren Sie Ihren Finanz-Tresor, um Schulden zu öffnen.", "Desbloquea tu bóveda financiera para abrir Deudas.", "Zhbllokoni kasafortën tuaj financiare për të hapur Borxhet.", "افتح خزنتك المالية لفتح الديون.", "Desbloqueie o seu Cofre Financeiro para abrir Dívidas.", "Sblocca il tuo Caveau Finanziario per aprire i debiti.", "Разблокируйте финансовое хранилище, чтобы открыть долги."),
  "Opening encrypted Debt data…": row("Verschlüsselte Schuldendaten werden geöffnet…", "Abriendo los datos de deuda cifrados…", "Po hapen të dhënat e enkriptuara të borxhit…", "جارٍ فتح بيانات الديون المشفرة…", "A abrir os dados de dívida encriptados…", "Apertura dei dati dei debiti crittografati…", "Открываются зашифрованные данные долгов…"),
  "Unlock your Financial Vault to open Document Vault.": row("Entsperren Sie Ihren Finanz-Tresor, um den Dokumenten-Tresor zu öffnen.", "Desbloquea tu bóveda financiera para abrir la bóveda de documentos.", "Zhbllokoni kasafortën tuaj financiare për të hapur kasafortën e dokumenteve.", "افتح خزنتك المالية لفتح خزنة المستندات.", "Desbloqueie o seu Cofre Financeiro para abrir o Cofre de Documentos.", "Sblocca il tuo Caveau Finanziario per aprire il Caveau Documenti.", "Разблокируйте финансовое хранилище, чтобы открыть хранилище документов."),
  "Opening Emergency Fund…": row("Notfallfonds wird geöffnet…", "Abriendo fondo de emergencia…", "Po hapet fondi i emergjencës…", "جارٍ فتح صندوق الطوارئ…", "A abrir o Fundo de Emergência…", "Apertura del fondo di emergenza…", "Открывается резервный фонд…"),
  "Financial GPS could not be opened.": row("Financial GPS konnte nicht geöffnet werden.", "No se pudo abrir Financial GPS.", "Financial GPS nuk mund të hapej.", "تعذر فتح Financial GPS.", "Não foi possível abrir o Financial GPS.", "Non è stato possibile aprire Financial GPS.", "Не удалось открыть Financial GPS."),
  "Unlock your Financial Vault to open Financial GPS.": row("Entsperren Sie Ihren Finanz-Tresor, um Financial GPS zu öffnen.", "Desbloquea tu bóveda financiera para abrir Financial GPS.", "Zhbllokoni kasafortën tuaj financiare për të hapur Financial GPS.", "افتح خزنتك المالية لفتح Financial GPS.", "Desbloqueie o seu Cofre Financeiro para abrir o Financial GPS.", "Sblocca il tuo Caveau Finanziario per aprire Financial GPS.", "Разблокируйте финансовое хранилище, чтобы открыть Financial GPS."),
  "Unlock your Financial Vault to open Financial Independence.": row("Entsperren Sie Ihren Finanz-Tresor, um Finanzielle Unabhängigkeit zu öffnen.", "Desbloquea tu bóveda financiera para abrir Independencia Financiera.", "Zhbllokoni kasafortën tuaj financiare për të hapur Pavarësinë Financiare.", "افتح خزنتك المالية لفتح الاستقلال المالي.", "Desbloqueie o seu Cofre Financeiro para abrir Independência Financeira.", "Sblocca il tuo Caveau Finanziario per aprire Indipendenza Finanziaria.", "Разблокируйте финансовое хранилище, чтобы открыть Финансовую независимость."),
  "Opening Financial Independence…": row("Finanzielle Unabhängigkeit wird geöffnet…", "Abriendo Independencia Financiera…", "Po hapet Pavarësia Financiare…", "جارٍ فتح الاستقلال المالي…", "A abrir Independência Financeira…", "Apertura di Indipendenza Finanziaria…", "Открывается Финансовая независимость…"),
  "Opening Financial setup…": row("Finanz-Setup wird geöffnet…", "Abriendo configuración financiera…", "Po hapet konfigurimi financiar…", "جارٍ فتح الإعداد المالي…", "A abrir a configuração financeira…", "Apertura della configurazione finanziaria…", "Открывается финансовая настройка…"),
  "Goals could not be opened.": row("Ziele konnten nicht geöffnet werden.", "No se pudieron abrir los objetivos.", "Objektivat nuk mund të hapeshin.", "تعذر فتح الأهداف.", "Não foi possível abrir os Objetivos.", "Non è stato possibile aprire gli obiettivi.", "Не удалось открыть цели."),
  "Unlock your Financial Vault to open Goals.": row("Entsperren Sie Ihren Finanz-Tresor, um Ziele zu öffnen.", "Desbloquea tu bóveda financiera para abrir Objetivos.", "Zhbllokoni kasafortën tuaj financiare për të hapur Objektivat.", "افتح خزنتك المالية لفتح الأهداف.", "Desbloqueie o seu Cofre Financeiro para abrir Objetivos.", "Sblocca il tuo Caveau Finanziario per aprire gli obiettivi.", "Разблокируйте финансовое хранилище, чтобы открыть цели."),
  "Opening Goals…": row("Ziele werden geöffnet…", "Abriendo Objetivos…", "Po hapen Objektivat…", "جارٍ فتح الأهداف…", "A abrir Objetivos…", "Apertura degli obiettivi…", "Открываются цели…"),
  "Monthly Planner data could not be opened.": row("Daten des Monatsplaners konnten nicht geöffnet werden.", "No se pudieron abrir los datos del planificador mensual.", "Të dhënat e planifikuesit mujor nuk mund të hapeshin.", "تعذر فتح بيانات المخطط الشهري.", "Não foi possível abrir os dados do Planeador Mensal.", "Non è stato possibile aprire i dati del Pianificatore mensile.", "Не удалось открыть данные ежемесячного планировщика."),
  "Unlock your Financial Vault to open Monthly Planner.": row("Entsperren Sie Ihren Finanz-Tresor, um den Monatsplaner zu öffnen.", "Desbloquea tu bóveda financiera para abrir el Planificador Mensual.", "Zhbllokoni kasafortën tuaj financiare për të hapur Planifikuesin Mujor.", "افتح خزنتك المالية لفتح المخطط الشهري.", "Desbloqueie o seu Cofre Financeiro para abrir o Planeador Mensal.", "Sblocca il tuo Caveau Finanziario per aprire il Pianificatore mensile.", "Разблокируйте финансовое хранилище, чтобы открыть ежемесячный планировщик."),
  "Opening Monthly Planner…": row("Monatsplaner wird geöffnet…", "Abriendo Planificador Mensual…", "Po hapet Planifikuesi Mujor…", "جارٍ فتح المخطط الشهري…", "A abrir o Planeador Mensal…", "Apertura del Pianificatore mensile…", "Открывается ежемесячный планировщик…"),
  "Opening Savings Intelligence…": row("Savings Intelligence wird geöffnet…", "Abriendo Inteligencia de Ahorro…", "Po hapet Inteligjenca e Kursimeve…", "جارٍ فتح ذكاء الادخار…", "A abrir Inteligência de Poupança…", "Apertura di Savings Intelligence…", "Открывается Savings Intelligence…"),
  "Encrypted transactions could not be opened.": row("Verschlüsselte Transaktionen konnten nicht geöffnet werden.", "No se pudieron abrir las transacciones cifradas.", "Transaksionet e enkriptuara nuk mund të hapeshin.", "تعذر فتح المعاملات المشفرة.", "Não foi possível abrir as transações encriptadas.", "Non è stato possibile aprire le transazioni crittografate.", "Не удалось открыть зашифрованные транзакции.")
};

export function translateGovernancePhraseBatch3(language: FiconterLanguage, source: string): string | null {
  if (language === "en") return source;
  return GOVERNANCE_UI_TRANSLATIONS_BATCH_3[source]?.[language] ?? null;
}
