import type { FiconterLanguage } from "./config";

type NonEnglishLanguage = Exclude<FiconterLanguage, "en">;
type TranslationRow = Record<NonEnglishLanguage, string>;

function row(de: string, es: string, sq: string, ar: string, pt: string, it: string, ru: string): TranslationRow {
  return { de, es, sq, ar, pt, it, ru };
}

export const GOVERNANCE_UI_TRANSLATIONS_BATCH_5: Record<string, TranslationRow> = {
  "Your encryption key is available only inside this browser session.": row("Dein Verschlüsselungsschlüssel ist nur innerhalb dieser Browsersitzung verfügbar.", "Tu clave de cifrado solo está disponible dentro de esta sesión del navegador.", "Çelësi yt i enkriptimit është i disponueshëm vetëm brenda këtij sesioni të shfletuesit.", "مفتاح التشفير الخاص بك متاح فقط داخل جلسة المتصفح هذه.", "A sua chave de encriptação está disponível apenas nesta sessão do navegador.", "La tua chiave di crittografia è disponibile solo all'interno di questa sessione del browser.", "Ваш ключ шифрования доступен только в рамках этой сессии браузера."),
  "Save your recovery code now": row("Speichere jetzt deinen Wiederherstellungscode", "Guarda ahora tu código de recuperación", "Ruaje tani kodin tënd të rikuperimit", "احفظ رمز الاسترداد الآن", "Guarde agora o seu código de recuperação", "Salva ora il tuo codice di recupero", "Сохраните код восстановления сейчас"),
  "You may need this code to unlock your financial vault on another device or after losing browser access.": row("Du benötigst diesen Code möglicherweise, um deinen Finanz-Tresor auf einem anderen Gerät oder nach dem Verlust des Browserzugriffs zu entsperren.", "Es posible que necesites este código para desbloquear tu Bóveda Financiera en otro dispositivo o si pierdes el acceso al navegador.", "Mund të të duhet ky kod për të zhbllokuar Kasafortën Financiare në një pajisje tjetër ose nëse humbet qasjen në shfletues.", "قد تحتاج إلى هذا الرمز لفتح خزنتك المالية على جهاز آخر أو بعد فقدان الوصول إلى المتصفح.", "Pode precisar deste código para desbloquear o seu Cofre Financeiro noutro dispositivo ou após perder o acesso ao navegador.", "Potresti aver bisogno di questo codice per sbloccare il tuo Caveau Finanziario su un altro dispositivo o dopo aver perso l'accesso al browser.", "Этот код может понадобиться для разблокировки Финансового хранилища на другом устройстве или после потери доступа к браузеру."),
  "Copied": row("Kopiert", "Copiado", "U kopjua", "تم النسخ", "Copiado", "Copiato", "Скопировано"),
  "Copy code": row("Code kopieren", "Copiar código", "Kopjo kodin", "نسخ الرمز", "Copiar código", "Copia codice", "Копировать код"),
  "I saved my recovery code": row("Ich habe meinen Wiederherstellungscode gespeichert", "He guardado mi código de recuperación", "E kam ruajtur kodin tim të rikuperimit", "لقد حفظت رمز الاسترداد الخاص بي", "Guardei o meu código de recuperação", "Ho salvato il mio codice di recupero", "Я сохранил код восстановления"),
  "Keep it somewhere private. FICONTER should not be able to recreate this code for you.": row("Bewahre ihn an einem privaten Ort auf. FICONTER sollte diesen Code nicht für dich neu erstellen können.", "Guárdalo en un lugar privado. FICONTER no debería poder recrear este código por ti.", "Mbaje në një vend privat. FICONTER nuk duhet të jetë në gjendje ta rikrijojë këtë kod për ty.", "احتفظ به في مكان خاص. يجب ألا يتمكن FICONTER من إعادة إنشاء هذا الرمز لك.", "Guarde-o num local privado. A FICONTER não deve conseguir recriar este código para si.", "Conservalo in un luogo privato. FICONTER non dovrebbe poter ricreare questo codice per te.", "Храните его в безопасном месте. FICONTER не должен иметь возможности восстановить этот код за вас."),
  "Lock vault": row("Tresor sperren", "Bloquear bóveda", "Kyç kasafortën", "قفل الخزنة", "Bloquear cofre", "Blocca caveau", "Заблокировать хранилище"),
  "Financial Vault Error": row("Fehler im Finanz-Tresor", "Error de la Bóveda Financiera", "Gabim i Kasafortës Financiare", "خطأ في الخزنة المالية", "Erro do Cofre Financeiro", "Errore del Caveau Finanziario", "Ошибка Финансового хранилища"),
  "Vault": row("Tresor", "Bóveda", "Kasaforta", "الخزنة", "Cofre", "Caveau", "Хранилище"),
  "Create your private encrypted vault.": row("Erstelle deinen privaten verschlüsselten Tresor.", "Crea tu bóveda privada cifrada.", "Krijo kasafortën tënde private të enkriptuar.", "أنشئ خزنتك الخاصة المشفرة.", "Crie o seu cofre privado encriptado.", "Crea il tuo caveau privato crittografato.", "Создайте личное зашифрованное хранилище."),
  "Your encrypted financial data is available on this device.": row("Deine verschlüsselten Finanzdaten sind auf diesem Gerät verfügbar.", "Tus datos financieros cifrados están disponibles en este dispositivo.", "Të dhënat e tua financiare të enkriptuara janë të disponueshme në këtë pajisje.", "بياناتك المالية المشفرة متاحة على هذا الجهاز.", "Os seus dados financeiros encriptados estão disponíveis neste dispositivo.", "I tuoi dati finanziari crittografati sono disponibili su questo dispositivo.", "Ваши зашифрованные финансовые данные доступны на этом устройстве."),
  "Unlock your encrypted financial data.": row("Entsperre deine verschlüsselten Finanzdaten.", "Desbloquea tus datos financieros cifrados.", "Zhblloko të dhënat e tua financiare të enkriptuara.", "افتح بياناتك المالية المشفرة.", "Desbloqueie os seus dados financeiros encriptados.", "Sblocca i tuoi dati finanziari crittografati.", "Разблокируйте зашифрованные финансовые данные."),
  "FICONTER creates the encryption key inside your browser. The readable vault key is never stored in the database.": row("FICONTER erstellt den Verschlüsselungsschlüssel in deinem Browser. Der lesbare Tresorschlüssel wird niemals in der Datenbank gespeichert.", "FICONTER crea la clave de cifrado dentro de tu navegador. La clave legible de la bóveda nunca se almacena en la base de datos.", "FICONTER krijon çelësin e enkriptimit brenda shfletuesit tënd. Çelësi i lexueshëm i kasafortës nuk ruhet kurrë në bazën e të dhënave.", "ينشئ FICONTER مفتاح التشفير داخل متصفحك. ولا يتم تخزين مفتاح الخزنة القابل للقراءة في قاعدة البيانات مطلقًا.", "A FICONTER cria a chave de encriptação no seu navegador. A chave legível do cofre nunca é guardada na base de dados.", "FICONTER crea la chiave di crittografia nel tuo browser. La chiave leggibile del caveau non viene mai memorizzata nel database.", "FICONTER создаёт ключ шифрования в вашем браузере. Читаемый ключ хранилища никогда не сохраняется в базе данных."),
  "Enter your 6-digit FICONTER PIN": row("Gib deine 6-stellige FICONTER-PIN ein", "Introduce tu PIN de FICONTER de 6 dígitos", "Vendos PIN-in 6-shifror të FICONTER", "أدخل رمز PIN الخاص بـ FICONTER المكوّن من 6 أرقام", "Introduza o PIN FICONTER de 6 dígitos", "Inserisci il PIN FICONTER a 6 cifre", "Введите 6-значный PIN FICONTER"),
  "6-digit FICONTER PIN": row("6-stellige FICONTER-PIN", "PIN de FICONTER de 6 dígitos", "PIN 6-shifror i FICONTER", "رمز PIN لـ FICONTER من 6 أرقام", "PIN FICONTER de 6 dígitos", "PIN FICONTER a 6 cifre", "6-значный PIN FICONTER"),
  "Forgot PIN? Use recovery code": row("PIN vergessen? Wiederherstellungscode verwenden", "¿Olvidaste el PIN? Usa el código de recuperación", "Harrove PIN-in? Përdor kodin e rikuperimit", "هل نسيت رمز PIN؟ استخدم رمز الاسترداد", "Esqueceu o PIN? Use o código de recuperação", "PIN dimenticato? Usa il codice di recupero", "Забыли PIN? Используйте код восстановления"),
  "Your recovery code stays exactly the same.": row("Dein Wiederherstellungscode bleibt exakt unverändert.", "Tu código de recuperación permanece exactamente igual.", "Kodi yt i rikuperimit mbetet saktësisht i njëjtë.", "يبقى رمز الاسترداد الخاص بك كما هو تمامًا.", "O seu código de recuperação permanece exatamente igual.", "Il tuo codice di recupero rimane esattamente lo stesso.", "Ваш код восстановления остаётся без изменений."),
  "Enter it once to verify this device and, if Quick Unlock is not enabled yet, create your 6-digit PIN next.": row("Gib ihn einmal ein, um dieses Gerät zu verifizieren. Falls Quick Unlock noch nicht aktiviert ist, kannst du anschließend deine 6-stellige PIN erstellen.", "Introdúcelo una vez para verificar este dispositivo y, si Quick Unlock aún no está activado, crea después tu PIN de 6 dígitos.", "Vendose një herë për të verifikuar këtë pajisje dhe, nëse Quick Unlock nuk është aktivizuar ende, krijo më pas PIN-in tënd 6-shifror.", "أدخله مرة واحدة للتحقق من هذا الجهاز، وإذا لم يكن الفتح السريع مفعّلًا بعد فأنشئ بعد ذلك رمز PIN المكوّن من 6 أرقام.", "Introduza-o uma vez para verificar este dispositivo e, se o Quick Unlock ainda não estiver ativado, crie depois o seu PIN de 6 dígitos.", "Inseriscilo una volta per verificare questo dispositivo e, se Quick Unlock non è ancora attivo, crea poi il tuo PIN a 6 cifre.", "Введите его один раз для проверки этого устройства, а затем, если Quick Unlock ещё не включён, создайте 6-значный PIN."),
  "Unlock with recovery code": row("Mit Wiederherstellungscode entsperren", "Desbloquear con código de recuperación", "Zhblloko me kodin e rikuperimit", "فتح باستخدام رمز الاسترداد", "Desbloquear com código de recuperação", "Sblocca con codice di recupero", "Разблокировать кодом восстановления"),
  "Verify recovery code": row("Wiederherstellungscode verifizieren", "Verificar código de recuperación", "Verifiko kodin e rikuperimit", "التحقق من رمز الاسترداد", "Verificar código de recuperação", "Verifica codice di recupero", "Проверить код восстановления"),
  "Back to PIN": row("Zurück zur PIN", "Volver al PIN", "Kthehu te PIN-i", "العودة إلى رمز PIN", "Voltar ao PIN", "Torna al PIN", "Назад к PIN"),
  "Vault unlocked": row("Tresor entsperrt", "Bóveda desbloqueada", "Kasaforta u zhbllokua", "تم فتح الخزنة", "Cofre desbloqueado", "Caveau sbloccato", "Хранилище разблокировано"),
  "Your active encryption key remains inside this browser session.": row("Dein aktiver Verschlüsselungsschlüssel bleibt innerhalb dieser Browsersitzung.", "Tu clave de cifrado activa permanece dentro de esta sesión del navegador.", "Çelësi yt aktiv i enkriptimit mbetet brenda këtij sesioni të shfletuesit.", "يبقى مفتاح التشفير النشط داخل جلسة المتصفح هذه.", "A sua chave de encriptação ativa permanece nesta sessão do navegador.", "La tua chiave di crittografia attiva rimane all'interno di questa sessione del browser.", "Активный ключ шифрования остаётся в рамках этой сессии браузера."),
  "Save your recovery code now.": row("Speichere jetzt deinen Wiederherstellungscode.", "Guarda ahora tu código de recuperación.", "Ruaje tani kodin tënd të rikuperimit.", "احفظ رمز الاسترداد الآن.", "Guarde agora o seu código de recuperação.", "Salva ora il tuo codice di recupero.", "Сохраните код восстановления сейчас."),
  "You may need it on another device or if Quick Unlock is unavailable.": row("Du benötigst ihn möglicherweise auf einem anderen Gerät oder wenn Quick Unlock nicht verfügbar ist.", "Puede que lo necesites en otro dispositivo o si Quick Unlock no está disponible.", "Mund të të duhet në një pajisje tjetër ose nëse Quick Unlock nuk është i disponueshëm.", "قد تحتاج إليه على جهاز آخر أو إذا لم يكن الفتح السريع متاحًا.", "Pode precisar dele noutro dispositivo ou se o Quick Unlock não estiver disponível.", "Potresti averne bisogno su un altro dispositivo o se Quick Unlock non è disponibile.", "Он может понадобиться на другом устройстве или если Quick Unlock недоступен."),
  "I saved it": row("Ich habe ihn gespeichert", "Lo he guardado", "E ruajta", "لقد حفظته", "Guardei-o", "L'ho salvato", "Я сохранил"),
  "Set a 6-digit Quick Unlock PIN for this device": row("Lege für dieses Gerät eine 6-stellige Quick-Unlock-PIN fest", "Configura un PIN de Quick Unlock de 6 dígitos para este dispositivo", "Vendos një PIN 6-shifror Quick Unlock për këtë pajisje", "عيّن رمز PIN للفتح السريع من 6 أرقام لهذا الجهاز", "Defina um PIN de Quick Unlock de 6 dígitos para este dispositivo", "Imposta un PIN Quick Unlock a 6 cifre per questo dispositivo", "Установите 6-значный PIN Quick Unlock для этого устройства"),
  "This PIN is an extra device shortcut. It does not replace, reset, or modify your recovery code.": row("Diese PIN ist eine zusätzliche Geräteabkürzung. Sie ersetzt, setzt oder verändert deinen Wiederherstellungscode nicht.", "Este PIN es un acceso rápido adicional para el dispositivo. No sustituye, restablece ni modifica tu código de recuperación.", "Ky PIN është një shkurtore shtesë për këtë pajisje. Ai nuk e zëvendëson, rivendos apo ndryshon kodin tënd të rikuperimit.", "رمز PIN هذا اختصار إضافي خاص بالجهاز. ولا يستبدل رمز الاسترداد أو يعيد تعيينه أو يعدّله.", "Este PIN é um atalho adicional para o dispositivo. Não substitui, repõe nem altera o seu código de recuperação.", "Questo PIN è una scorciatoia aggiuntiva per il dispositivo. Non sostituisce, reimposta o modifica il tuo codice di recupero.", "Этот PIN — дополнительный быстрый способ доступа на устройстве. Он не заменяет, не сбрасывает и не изменяет код восстановления."),
  "Create 6-digit FICONTER PIN": row("6-stellige FICONTER-PIN erstellen", "Crear PIN de FICONTER de 6 dígitos", "Krijo PIN 6-shifror të FICONTER", "إنشاء رمز PIN لـ FICONTER من 6 أرقام", "Criar PIN FICONTER de 6 dígitos", "Crea PIN FICONTER a 6 cifre", "Создать 6-значный PIN FICONTER"),
  "Create 6-digit PIN": row("6-stellige PIN erstellen", "Crear PIN de 6 dígitos", "Krijo PIN 6-shifror", "إنشاء رمز PIN من 6 أرقام", "Criar PIN de 6 dígitos", "Crea PIN a 6 cifre", "Создать 6-значный PIN"),
  "Your recovery code will remain unchanged. Verify it once to authorize Quick Unlock on this device.": row("Dein Wiederherstellungscode bleibt unverändert. Verifiziere ihn einmal, um Quick Unlock auf diesem Gerät zu autorisieren.", "Tu código de recuperación permanecerá sin cambios. Verifícalo una vez para autorizar Quick Unlock en este dispositivo.", "Kodi yt i rikuperimit do të mbetet i pandryshuar. Verifikoje një herë për të autorizuar Quick Unlock në këtë pajisje.", "سيبقى رمز الاسترداد دون تغيير. تحقّق منه مرة واحدة للسماح بالفتح السريع على هذا الجهاز.", "O seu código de recuperação permanecerá inalterado. Verifique-o uma vez para autorizar o Quick Unlock neste dispositivo.", "Il tuo codice di recupero rimarrà invariato. Verificalo una volta per autorizzare Quick Unlock su questo dispositivo.", "Код восстановления останется без изменений. Проверьте его один раз, чтобы разрешить Quick Unlock на этом устройстве."),
  "Set up 6-digit PIN": row("6-stellige PIN einrichten", "Configurar PIN de 6 dígitos", "Konfiguro PIN 6-shifror", "إعداد رمز PIN من 6 أرقام", "Configurar PIN de 6 dígitos", "Configura PIN a 6 cifre", "Настроить 6-значный PIN"),
  "Remove Quick Unlock from this device": row("Quick Unlock von diesem Gerät entfernen", "Eliminar Quick Unlock de este dispositivo", "Hiq Quick Unlock nga kjo pajisje", "إزالة الفتح السريع من هذا الجهاز", "Remover Quick Unlock deste dispositivo", "Rimuovi Quick Unlock da questo dispositivo", "Удалить Quick Unlock с этого устройства"),
  "Lock vault now": row("Tresor jetzt sperren", "Bloquear bóveda ahora", "Kyç kasafortën tani", "قفل الخزنة الآن", "Bloquear cofre agora", "Blocca il caveau ora", "Заблокировать хранилище сейчас"),
};

export function translateGovernancePhraseBatch5(language: FiconterLanguage, source: string): string | null {
  if (language === "en") return source;
  return GOVERNANCE_UI_TRANSLATIONS_BATCH_5[source]?.[language] ?? null;
}
