import type { FiconterLanguage } from "./config";

type NonEnglishLanguage = Exclude<FiconterLanguage, "en">;
type TranslationRow = Record<NonEnglishLanguage, string>;

function row(de: string, es: string, sq: string, ar: string, pt: string, it: string, ru: string): TranslationRow {
  return { de, es, sq, ar, pt, it, ru };
}

export const GOVERNANCE_UI_TRANSLATIONS_BATCH_6: Record<string, TranslationRow> = {
  "Unable to check vault status.": row("Tresorstatus konnte nicht geprüft werden.", "No se pudo comprobar el estado de la bóveda.", "Statusi i kasafortës nuk mund të kontrollohej.", "تعذر التحقق من حالة الخزنة.", "Não foi possível verificar o estado do cofre.", "Impossibile verificare lo stato del caveau.", "Не удалось проверить состояние хранилища."),
  "Could not refresh recovery cases.": row("Wiederherstellungsfälle konnten nicht aktualisiert werden.", "No se pudieron actualizar los casos de recuperación.", "Rastet e rikuperimit nuk mund të rifreskoheshin.", "تعذر تحديث حالات الاسترداد.", "Não foi possível atualizar os casos de recuperação.", "Impossibile aggiornare i casi di recupero.", "Не удалось обновить случаи восстановления."),
  "Could not generate recovery document.": row("Wiederherstellungsdokument konnte nicht erstellt werden.", "No se pudo generar el documento de recuperación.", "Dokumenti i rikuperimit nuk mund të gjenerohej.", "تعذر إنشاء مستند الاسترداد.", "Não foi possível gerar o documento de recuperação.", "Impossibile generare il documento di recupero.", "Не удалось создать документ восстановления."),
  "Could not update recovery case.": row("Wiederherstellungsfall konnte nicht aktualisiert werden.", "No se pudo actualizar el caso de recuperación.", "Rasti i rikuperimit nuk mund të përditësohej.", "تعذر تحديث حالة الاسترداد.", "Não foi possível atualizar o caso de recuperação.", "Impossibile aggiornare il caso di recupero.", "Не удалось обновить случай восстановления."),
  "Could not delete recovery case.": row("Wiederherstellungsfall konnte nicht gelöscht werden.", "No se pudo eliminar el caso de recuperación.", "Rasti i rikuperimit nuk mund të fshihej.", "تعذر حذف حالة الاسترداد.", "Não foi possível eliminar o caso de recuperação.", "Impossibile eliminare il caso di recupero.", "Не удалось удалить случай восстановления."),
  "Could not generate consent document.": row("Einwilligungsdokument konnte nicht erstellt werden.", "No se pudo generar el documento de consentimiento.", "Dokumenti i pëlqimit nuk mund të gjenerohej.", "تعذر إنشاء مستند الموافقة.", "Não foi possível gerar o documento de consentimento.", "Impossibile generare il documento di consenso.", "Не удалось создать документ согласия."),
  "Could not send the consent document.": row("Das Einwilligungsdokument konnte nicht gesendet werden.", "No se pudo enviar el documento de consentimiento.", "Dokumenti i pëlqimit nuk mund të dërgohej.", "تعذر إرسال مستند الموافقة.", "Não foi possível enviar o documento de consentimento.", "Impossibile inviare il documento di consenso.", "Не удалось отправить документ согласия."),
  "Could not upload signed consent.": row("Die unterzeichnete Einwilligung konnte nicht hochgeladen werden.", "No se pudo subir el consentimiento firmado.", "Pëlqimi i nënshkruar nuk mund të ngarkohej.", "تعذر رفع الموافقة الموقّعة.", "Não foi possível carregar o consentimento assinado.", "Impossibile caricare il consenso firmato.", "Не удалось загрузить подписанное согласие."),
  "Could not issue Recovery Access.": row("Wiederherstellungszugang konnte nicht ausgestellt werden.", "No se pudo emitir el Acceso de Recuperación.", "Qasja e Rikuperimit nuk mund të lëshohej.", "تعذر إصدار وصول الاسترداد.", "Não foi possível emitir o Acesso de Recuperação.", "Impossibile emettere l'Accesso di Recupero.", "Не удалось выдать доступ для восстановления."),
  "Could not revoke Recovery Access.": row("Wiederherstellungszugang konnte nicht widerrufen werden.", "No se pudo revocar el Acceso de Recuperación.", "Qasja e Rikuperimit nuk mund të revokohej.", "تعذر إلغاء وصول الاسترداد.", "Não foi possível revogar o Acesso de Recuperação.", "Impossibile revocare l'Accesso di Recupero.", "Не удалось отозвать доступ для восстановления."),
  "Start verification": row("Verifizierung starten", "Iniciar verificación", "Fillo verifikimin", "بدء التحقق", "Iniciar verificação", "Avvia verifica", "Начать проверку"),
  "Generate consent document": row("Einwilligungsdokument erstellen", "Generar documento de consentimiento", "Gjenero dokumentin e pëlqimit", "إنشاء مستند الموافقة", "Gerar documento de consentimento", "Genera documento di consenso", "Создать документ согласия"),
  "Send document for signature": row("Dokument zur Unterschrift senden", "Enviar documento para firma", "Dërgo dokumentin për nënshkrim", "إرسال المستند للتوقيع", "Enviar documento para assinatura", "Invia documento per la firma", "Отправить документ на подпись"),
  "Document sent · awaiting signature": row("Dokument gesendet · Unterschrift ausstehend", "Documento enviado · esperando firma", "Dokumenti u dërgua · në pritje të nënshkrimit", "تم إرسال المستند · بانتظار التوقيع", "Documento enviado · a aguardar assinatura", "Documento inviato · in attesa di firma", "Документ отправлен · ожидается подпись"),
  "Manual signed-copy fallback": row("Manuelle Ersatzoption für signierte Kopie", "Alternativa manual para copia firmada", "Alternativë manuale për kopjen e nënshkruar", "خيار يدوي احتياطي للنسخة الموقّعة", "Alternativa manual para cópia assinada", "Alternativa manuale per copia firmata", "Ручной резервный вариант для подписанной копии"),
  "Approve recovery": row("Wiederherstellung genehmigen", "Aprobar recuperación", "Mirato rikuperimin", "الموافقة على الاسترداد", "Aprovar recuperação", "Approva recupero", "Одобрить восстановление"),
  "Generate new recovery access": row("Neuen Wiederherstellungszugang erstellen", "Generar nuevo acceso de recuperación", "Gjenero qasje të re rikuperimi", "إنشاء وصول استرداد جديد", "Gerar novo acesso de recuperação", "Genera nuovo accesso di recupero", "Создать новый доступ для восстановления"),
  "Generate recovery access": row("Wiederherstellungszugang erstellen", "Generar acceso de recuperación", "Gjenero qasje rikuperimi", "إنشاء وصول الاسترداد", "Gerar acesso de recuperação", "Genera accesso di recupero", "Создать доступ для восстановления"),
  "Recovery access active · expires": row("Wiederherstellungszugang aktiv · läuft ab", "Acceso de recuperación activo · caduca", "Qasja e rikuperimit aktive · skadon", "وصول الاسترداد نشط · تنتهي صلاحيته", "Acesso de recuperação ativo · expira", "Accesso di recupero attivo · scade", "Доступ для восстановления активен · истекает"),
  "Revoke recovery access": row("Wiederherstellungszugang widerrufen", "Revocar acceso de recuperación", "Revoko qasjen e rikuperimit", "إلغاء وصول الاسترداد", "Revogar acesso de recuperação", "Revoca accesso di recupero", "Отозвать доступ для восстановления"),
  "Account ID": row("Konto-ID", "ID de cuenta", "ID e llogarisë", "معرّف الحساب", "ID da conta", "ID account", "ID аккаунта"),
  "Opened": row("Geöffnet", "Abierto", "U hap", "تم الفتح", "Aberto", "Aperto", "Открыто"),
  "Sent to customer": row("An Kunden gesendet", "Enviado al cliente", "U dërgua te klienti", "تم الإرسال إلى العميل", "Enviado ao cliente", "Inviato al cliente", "Отправлено клиенту"),
  "View signed consent": row("Unterzeichnete Einwilligung anzeigen", "Ver consentimiento firmado", "Shiko pëlqimin e nënshkruar", "عرض الموافقة الموقّعة", "Ver consentimento assinado", "Visualizza consenso firmato", "Просмотреть подписанное согласие"),
  "Open signed copy": row("Unterzeichnete Kopie öffnen", "Abrir copia firmada", "Hap kopjen e nënshkruar", "فتح النسخة الموقّعة", "Abrir cópia assinada", "Apri copia firmata", "Открыть подписанную копию"),
  "Open consent document": row("Einwilligungsdokument öffnen", "Abrir documento de consentimiento", "Hap dokumentin e pëlqimit", "فتح مستند الموافقة", "Abrir documento de consentimento", "Apri documento di consenso", "Открыть документ согласия"),
  "Expires": row("Läuft ab", "Caduca", "Skadon", "تنتهي الصلاحية", "Expira", "Scade", "Истекает"),
  "Access ID": row("Zugangs-ID", "ID de acceso", "ID e qasjes", "معرّف الوصول", "ID de acesso", "ID accesso", "ID доступа"),
  "NEXT STEP": row("NÄCHSTER SCHRITT", "SIGUIENTE PASO", "HAPI TJETËR", "الخطوة التالية", "PRÓXIMO PASSO", "PASSO SUCCESSIVO", "СЛЕДУЮЩИЙ ШАГ"),
  "Reject": row("Ablehnen", "Rechazar", "Refuzo", "رفض", "Rejeitar", "Rifiuta", "Отклонить"),
  "Vault recovery": row("Tresor-Wiederherstellung", "Recuperación de la bóveda", "Rikuperimi i kasafortës", "استرداد الخزنة", "Recuperação do cofre", "Recupero del caveau", "Восстановление хранилища"),
  "Find a customer, generate consent, send it to their FICONTER Inbox, approve the request, and issue time-limited Recovery Access.": row("Finde einen Kunden, erstelle die Einwilligung, sende sie an seinen FICONTER-Posteingang, genehmige die Anfrage und erteile zeitlich begrenzten Wiederherstellungszugang.", "Busca un cliente, genera el consentimiento, envíalo a su Bandeja de entrada de FICONTER, aprueba la solicitud y emite un Acceso de Recuperación temporal.", "Gjej një klient, gjenero pëlqimin, dërgoje në Inbox-in e tij FICONTER, mirato kërkesën dhe lësho Qasje Rikuperimi me afat.", "ابحث عن عميل، وأنشئ الموافقة، وأرسلها إلى صندوق وارد FICONTER الخاص به، ثم وافق على الطلب وأصدر وصول استرداد محدود المدة.", "Encontre um cliente, gere o consentimento, envie-o para a Caixa de Entrada FICONTER, aprove o pedido e emita Acesso de Recuperação com prazo limitado.", "Trova un cliente, genera il consenso, invialo alla sua Posta in arrivo FICONTER, approva la richiesta ed emetti un Accesso di Recupero a tempo.", "Найдите клиента, создайте согласие, отправьте его во Входящие FICONTER, одобрите запрос и выдайте временный доступ для восстановления."),
  "Find customer": row("Kunden finden", "Buscar cliente", "Gjej klientin", "البحث عن عميل", "Encontrar cliente", "Trova cliente", "Найти клиента"),
  "Search by full name, email address, existing recovery request ID, or birthdate.": row("Suche nach vollständigem Namen, E-Mail-Adresse, vorhandener Wiederherstellungsanfrage-ID oder Geburtsdatum.", "Busca por nombre completo, correo electrónico, ID de solicitud de recuperación existente o fecha de nacimiento.", "Kërko sipas emrit të plotë, adresës së email-it, ID-së ekzistuese të kërkesës së rikuperimit ose datëlindjes.", "ابحث بالاسم الكامل أو البريد الإلكتروني أو معرّف طلب الاسترداد الحالي أو تاريخ الميلاد.", "Pesquise por nome completo, endereço de email, ID de pedido de recuperação existente ou data de nascimento.", "Cerca per nome completo, indirizzo email, ID richiesta di recupero esistente o data di nascita.", "Ищите по полному имени, адресу электронной почты, ID существующего запроса на восстановление или дате рождения."),
  "Full name, email, RCV-2026-..., or YYYY-MM-DD": row("Vollständiger Name, E-Mail, RCV-2026-... oder YYYY-MM-DD", "Nombre completo, correo, RCV-2026-... o YYYY-MM-DD", "Emri i plotë, email-i, RCV-2026-... ose YYYY-MM-DD", "الاسم الكامل أو البريد الإلكتروني أو RCV-2026-... أو YYYY-MM-DD", "Nome completo, email, RCV-2026-... ou YYYY-MM-DD", "Nome completo, email, RCV-2026-... o YYYY-MM-DD", "Полное имя, email, RCV-2026-... или YYYY-MM-DD"),
};

export function translateGovernancePhraseBatch6(language: FiconterLanguage, source: string): string | null {
  if (language === "en") return source;
  return GOVERNANCE_UI_TRANSLATIONS_BATCH_6[source]?.[language] ?? null;
}
