import type { FiconterLanguage } from "./config";

type NonEnglishLanguage = Exclude<FiconterLanguage, "en">;
type TranslationRow = Record<NonEnglishLanguage, string>;

function row(de: string, es: string, sq: string, ar: string, pt: string, it: string, ru: string): TranslationRow {
  return { de, es, sq, ar, pt, it, ru };
}

export const GOVERNANCE_UI_TRANSLATIONS_BATCH_2: Record<string, TranslationRow> = {
  "Recovery Access claimed": row("Wiederherstellungszugang beansprucht", "Acceso de recuperación reclamado", "Qasja e rikuperimit u përdor", "تم استخدام وصول الاستعادة", "Acesso de recuperação utilizado", "Accesso di recupero utilizzato", "Доступ для восстановления активирован"),
  "Vault Recovery Access approved": row("Tresor-Wiederherstellungszugang genehmigt", "Acceso de recuperación de la bóveda aprobado", "Qasja për rikuperimin e kasafortës u miratua", "تمت الموافقة على وصول استعادة الخزنة", "Acesso de recuperação do cofre aprovado", "Accesso al recupero del caveau approvato", "Доступ к восстановлению хранилища одобрен"),
  "Issued": row("Ausgestellt", "Emitido", "Lëshuar", "تم الإصدار", "Emitido", "Emesso", "Выдано"),
  "· Expires": row("· Läuft ab", "· Caduca", "· Skadon", "· تنتهي الصلاحية", "· Expira", "· Scade", "· Истекает"),
  "View status": row("Status anzeigen", "Ver estado", "Shiko statusin", "عرض الحالة", "Ver estado", "Visualizza stato", "Посмотреть статус"),
  "Continue recovery": row("Wiederherstellung fortsetzen", "Continuar recuperación", "Vazhdo rikuperimin", "متابعة الاستعادة", "Continuar recuperação", "Continua recupero", "Продолжить восстановление"),
  "Begin secure recovery": row("Sichere Wiederherstellung starten", "Iniciar recuperación segura", "Fillo rikuperimin e sigurt", "بدء الاستعادة الآمنة", "Iniciar recuperação segura", "Avvia recupero sicuro", "Начать безопасное восстановление"),
  "Vault recovery documents": row("Dokumente zur Tresor-Wiederherstellung", "Documentos de recuperación de la bóveda", "Dokumentet e rikuperimit të kasafortës", "مستندات استعادة الخزنة", "Documentos de recuperação do cofre", "Documenti di recupero del caveau", "Документы восстановления хранилища"),
  "Signed Vault recovery consent": row("Unterzeichnete Einwilligung zur Tresor-Wiederherstellung", "Consentimiento firmado para la recuperación de la bóveda", "Pëlqimi i nënshkruar për rikuperimin e kasafortës", "موافقة موقعة لاستعادة الخزنة", "Consentimento assinado para recuperação do cofre", "Consenso firmato per il recupero del caveau", "Подписанное согласие на восстановление хранилища"),
  "Signature required: Vault recovery consent": row("Unterschrift erforderlich: Einwilligung zur Tresor-Wiederherstellung", "Firma requerida: consentimiento para la recuperación de la bóveda", "Kërkohet nënshkrim: pëlqimi për rikuperimin e kasafortës", "التوقيع مطلوب: موافقة استعادة الخزنة", "Assinatura necessária: consentimento para recuperação do cofre", "Firma richiesta: consenso al recupero del caveau", "Требуется подпись: согласие на восстановление хранилища"),
  "Sent": row("Gesendet", "Enviado", "Dërguar", "تم الإرسال", "Enviado", "Inviato", "Отправлено"),
  "View document": row("Dokument anzeigen", "Ver documento", "Shiko dokumentin", "عرض المستند", "Ver documento", "Visualizza documento", "Посмотреть документ"),
  "Review & sign": row("Prüfen & unterschreiben", "Revisar y firmar", "Shqyrto dhe nënshkruaj", "المراجعة والتوقيع", "Rever e assinar", "Rivedi e firma", "Просмотреть и подписать"),
  "Sent to you:": row("An Sie gesendet:", "Enviado a ti:", "Dërguar për ju:", "أُرسل إليك:", "Enviado para si:", "Inviato a te:", "Отправлено вам:"),
  "This document records your authorization for FICONTER to process this specific last-resort Vault recovery request.": row("Dieses Dokument hält Ihre Genehmigung fest, dass FICONTER diese konkrete Tresor-Wiederherstellungsanfrage als letztes Mittel bearbeiten darf.", "Este documento registra tu autorización para que FICONTER procese esta solicitud específica de recuperación de la bóveda como último recurso.", "Ky dokument regjistron autorizimin tuaj që FICONTER të përpunojë këtë kërkesë specifike për rikuperimin e kasafortës si mjet i fundit.", "يسجل هذا المستند تفويضك لـ FICONTER لمعالجة طلب استعادة الخزنة المحدد هذا كحل أخير.", "Este documento regista a sua autorização para a FICONTER processar este pedido específico de recuperação do cofre como último recurso.", "Questo documento registra la tua autorizzazione affinché FICONTER elabori questa specifica richiesta di recupero del caveau come ultima risorsa.", "Этот документ фиксирует ваше разрешение FICONTER обработать данный конкретный запрос на восстановление хранилища как крайнюю меру."),
  "I understand that this process is limited to restoring access to my Vault and does not authorize FICONTER personnel to inspect, use, copy, export, or otherwise access my decrypted financial records except to the extent strictly required by the approved recovery process.": row("Ich verstehe, dass dieser Prozess ausschließlich der Wiederherstellung des Zugriffs auf meinen Tresor dient und FICONTER-Mitarbeiter nicht dazu berechtigt, meine entschlüsselten Finanzdaten einzusehen, zu verwenden, zu kopieren, zu exportieren oder anderweitig darauf zuzugreifen, außer soweit dies für den genehmigten Wiederherstellungsprozess unbedingt erforderlich ist.", "Entiendo que este proceso se limita a restaurar el acceso a mi bóveda y no autoriza al personal de FICONTER a inspeccionar, usar, copiar, exportar ni acceder de otro modo a mis registros financieros descifrados, salvo en la medida estrictamente necesaria para el proceso de recuperación aprobado.", "E kuptoj se ky proces kufizohet në rikthimin e qasjes në kasafortën time dhe nuk autorizon personelin e FICONTER të kontrollojë, përdorë, kopjojë, eksportojë ose ndryshe të ketë qasje në të dhënat e mia financiare të deshifruara, përveçse në masën rreptësisht të nevojshme për procesin e miratuar të rikuperimit.", "أفهم أن هذه العملية تقتصر على استعادة الوصول إلى خزنَتي ولا تمنح موظفي FICONTER تفويضًا لفحص سجلاتي المالية المفكوكة التشفير أو استخدامها أو نسخها أو تصديرها أو الوصول إليها بأي طريقة أخرى إلا بالقدر الضروري تمامًا لعملية الاستعادة المعتمدة.", "Compreendo que este processo se limita a restaurar o acesso ao meu cofre e não autoriza o pessoal da FICONTER a inspecionar, utilizar, copiar, exportar ou aceder de qualquer outra forma aos meus registos financeiros desencriptados, exceto na medida estritamente necessária ao processo de recuperação aprovado.", "Comprendo che questa procedura è limitata al ripristino dell'accesso al mio caveau e non autorizza il personale FICONTER a esaminare, utilizzare, copiare, esportare o accedere in altro modo ai miei dati finanziari decifrati, salvo nella misura strettamente necessaria al processo di recupero approvato.", "Я понимаю, что этот процесс ограничен восстановлением доступа к моему хранилищу и не разрешает сотрудникам FICONTER просматривать, использовать, копировать, экспортировать или иным образом получать доступ к моим расшифрованным финансовым данным, кроме случаев, строго необходимых для утверждённого процесса восстановления."),
  "3. Mandatory consent and authorization": row("3. Erforderliche Einwilligung und Genehmigung", "3. Consentimiento y autorización obligatorios", "3. Pëlqimi dhe autorizimi i detyrueshëm", "3. الموافقة والتفويض الإلزاميان", "3. Consentimento e autorização obrigatórios", "3. Consenso e autorizzazione obbligatori", "3. Обязательные согласие и разрешение"),
  "By electronically signing and submitting this document, I confirm all of the following:": row("Durch die elektronische Unterzeichnung und Einreichung dieses Dokuments bestätige ich Folgendes:", "Al firmar y enviar electrónicamente este documento, confirmo todo lo siguiente:", "Duke nënshkruar dhe dorëzuar elektronikisht këtë dokument, konfirmoj të gjitha sa vijojnë:", "من خلال توقيع هذا المستند وإرساله إلكترونيًا، أؤكد كل ما يلي:", "Ao assinar e submeter eletronicamente este documento, confirmo o seguinte:", "Firmando e inviando elettronicamente questo documento, confermo quanto segue:", "Электронно подписывая и отправляя этот документ, я подтверждаю следующее:"),
  "I authorize FICONTER to process this specific Assisted Recovery request.": row("Ich autorisiere FICONTER, diese konkrete Anfrage zur unterstützten Wiederherstellung zu bearbeiten.", "Autorizo a FICONTER a procesar esta solicitud específica de recuperación asistida.", "Autorizoj FICONTER të përpunojë këtë kërkesë specifike për rikuperim të asistuar.", "أفوض FICONTER لمعالجة طلب الاستعادة المساعدة المحدد هذا.", "Autorizo a FICONTER a processar este pedido específico de recuperação assistida.", "Autorizzo FICONTER a elaborare questa specifica richiesta di recupero assistito.", "Я разрешаю FICONTER обработать этот конкретный запрос на вспомогательное восстановление."),
  "My normal recovery methods have failed or are no longer available to me.": row("Meine normalen Wiederherstellungsmethoden sind fehlgeschlagen oder stehen mir nicht mehr zur Verfügung.", "Mis métodos normales de recuperación han fallado o ya no están disponibles.", "Metodat e mia normale të rikuperimit kanë dështuar ose nuk janë më të disponueshme për mua.", "لقد فشلت طرق الاستعادة العادية الخاصة بي أو لم تعد متاحة لي.", "Os meus métodos normais de recuperação falharam ou já não estão disponíveis.", "I miei normali metodi di recupero non hanno funzionato o non sono più disponibili.", "Мои обычные способы восстановления не сработали или больше мне недоступны."),
  "I understand that a previous recovery credential may be invalidated and replaced after successful recovery.": row("Ich verstehe, dass frühere Wiederherstellungsdaten nach erfolgreicher Wiederherstellung ungültig gemacht und ersetzt werden können.", "Entiendo que una credencial de recuperación anterior puede quedar invalidada y ser sustituida tras una recuperación satisfactoria.", "E kuptoj se një kredencial i mëparshëm rikuperimi mund të çaktivizohet dhe zëvendësohet pas rikuperimit të suksesshëm.", "أفهم أن بيانات اعتماد استعادة سابقة قد يتم إبطالها واستبدالها بعد نجاح الاستعادة.", "Compreendo que uma credencial de recuperação anterior poderá ser invalidada e substituída após uma recuperação bem-sucedida.", "Comprendo che una precedente credenziale di recupero possa essere invalidata e sostituita dopo un recupero riuscito.", "Я понимаю, что прежние учётные данные восстановления могут быть аннулированы и заменены после успешного восстановления."),
  "I have read and understood FICONTER&apos;s Security & Data Protection Commitment.": row("Ich habe die Verpflichtung von FICONTER zu Sicherheit und Datenschutz gelesen und verstanden.", "He leído y comprendido el Compromiso de Seguridad y Protección de Datos de FICONTER.", "Kam lexuar dhe kuptuar angazhimin e FICONTER për sigurinë dhe mbrojtjen e të dhënave.", "لقد قرأت وفهمت التزام FICONTER بالأمان وحماية البيانات.", "Li e compreendi o Compromisso de Segurança e Proteção de Dados da FICONTER.", "Ho letto e compreso l'Impegno FICONTER per la sicurezza e la protezione dei dati.", "Я прочитал(а) и понял(а) обязательство FICONTER по безопасности и защите данных."),
  "FICONTER is designed to protect customer financial information through strong encryption and strict access controls. Assisted Recovery is intended only to restore customer access to the Vault.": row("FICONTER wurde entwickelt, um Finanzinformationen von Kunden durch starke Verschlüsselung und strenge Zugriffskontrollen zu schützen. Die unterstützte Wiederherstellung dient ausschließlich dazu, den Kundenzugriff auf den Tresor wiederherzustellen.", "FICONTER está diseñado para proteger la información financiera del cliente mediante un cifrado sólido y estrictos controles de acceso. La recuperación asistida está destinada únicamente a restaurar el acceso del cliente a la bóveda.", "FICONTER është projektuar për të mbrojtur informacionin financiar të klientit përmes enkriptimit të fortë dhe kontrolleve të rrepta të qasjes. Rikuperimi i asistuar synon vetëm rikthimin e qasjes së klientit në kasafortë.", "تم تصميم FICONTER لحماية المعلومات المالية للعملاء عبر تشفير قوي وضوابط وصول صارمة. وتهدف الاستعادة المساعدة فقط إلى استعادة وصول العميل إلى الخزنة.", "A FICONTER foi concebida para proteger as informações financeiras dos clientes através de encriptação forte e controlos de acesso rigorosos. A recuperação assistida destina-se apenas a restaurar o acesso do cliente ao cofre.", "FICONTER è progettata per proteggere le informazioni finanziarie dei clienti tramite crittografia robusta e rigorosi controlli di accesso. Il recupero assistito serve esclusivamente a ripristinare l'accesso del cliente al caveau.", "FICONTER разработан для защиты финансовой информации клиентов с помощью надёжного шифрования и строгого контроля доступа. Вспомогательное восстановление предназначено только для восстановления доступа клиента к хранилищу."),
  "Back to Inbox": row("Zurück zum Posteingang", "Volver a la bandeja de entrada", "Kthehu te kutia hyrëse", "العودة إلى صندوق الوارد", "Voltar à caixa de entrada", "Torna alla posta in arrivo", "Назад во входящие"),
  "SECURE CUSTOMER RECOVERY": row("SICHERE KUNDENWIEDERHERSTELLUNG", "RECUPERACIÓN SEGURA DEL CLIENTE", "RIKUPERIM I SIGURT I KLIENTIT", "استعادة آمنة للعميل", "RECUPERAÇÃO SEGURA DO CLIENTE", "RECUPERO SICURO DEL CLIENTE", "БЕЗОПАСНОЕ ВОССТАНОВЛЕНИЕ КЛИЕНТА"),
  "Vault Recovery Center": row("Tresor-Wiederherstellungscenter", "Centro de recuperación de la bóveda", "Qendra e rikuperimit të kasafortës", "مركز استعادة الخزنة", "Centro de recuperação do cofre", "Centro recupero del caveau", "Центр восстановления хранилища"),
  "Account protected": row("Konto geschützt", "Cuenta protegida", "Llogaria e mbrojtur", "الحساب محمي", "Conta protegida", "Account protetto", "Аккаунт защищён"),
  "Your approved Assisted Recovery authorization is separate from your encrypted Financial Vault. FICONTER personnel cannot use this page to view your decrypted financial records or your permanent recovery credential.": row("Ihre genehmigte Autorisierung zur unterstützten Wiederherstellung ist von Ihrem verschlüsselten Finanz-Tresor getrennt. FICONTER-Mitarbeiter können diese Seite nicht verwenden, um Ihre entschlüsselten Finanzdaten oder Ihre dauerhaften Wiederherstellungsdaten einzusehen.", "Tu autorización aprobada de recuperación asistida está separada de tu bóveda financiera cifrada. El personal de FICONTER no puede usar esta página para ver tus registros financieros descifrados ni tu credencial de recuperación permanente.", "Autorizimi juaj i miratuar për rikuperim të asistuar është i ndarë nga kasaforta juaj financiare e enkriptuar. Personeli i FICONTER nuk mund ta përdorë këtë faqe për të parë të dhënat tuaja financiare të deshifruara ose kredencialin tuaj të përhershëm të rikuperimit.", "تفويض الاستعادة المساعدة المعتمد الخاص بك منفصل عن الخزنة المالية المشفرة. لا يمكن لموظفي FICONTER استخدام هذه الصفحة لعرض سجلاتك المالية المفكوكة التشفير أو بيانات اعتماد الاستعادة الدائمة الخاصة بك.", "A sua autorização aprovada de Recuperação Assistida é separada do seu Cofre Financeiro encriptado. O pessoal da FICONTER não pode utilizar esta página para ver os seus registos financeiros desencriptados nem a sua credencial permanente de recuperação.", "La tua autorizzazione approvata al Recupero Assistito è separata dal tuo Caveau Finanziario crittografato. Il personale FICONTER non può usare questa pagina per visualizzare i tuoi dati finanziari decifrati o la tua credenziale di recupero permanente.", "Ваше одобренное разрешение на вспомогательное восстановление отделено от зашифрованного финансового хранилища. Сотрудники FICONTER не могут использовать эту страницу для просмотра ваших расшифрованных финансовых данных или постоянных учётных данных восстановления."),
  "What happens next?": row("Wie geht es weiter?", "¿Qué ocurre después?", "Çfarë ndodh më pas?", "ماذا يحدث بعد ذلك؟", "O que acontece a seguir?", "Cosa succede ora?", "Что произойдёт дальше?"),
  "After the temporary authorization is claimed, FICONTER must restore access to the same encrypted Vault key through the protected recovery-key mechanism. Your replacement recovery credential will be generated on your device, not by an administrator.": row("Nachdem die temporäre Autorisierung beansprucht wurde, muss FICONTER den Zugriff auf denselben verschlüsselten Tresorschlüssel über den geschützten Wiederherstellungsschlüssel-Mechanismus wiederherstellen. Ihre neuen Wiederherstellungsdaten werden auf Ihrem Gerät und nicht von einem Administrator erzeugt.", "Una vez utilizada la autorización temporal, FICONTER debe restaurar el acceso a la misma clave cifrada de la bóveda mediante el mecanismo protegido de clave de recuperación. Tu nueva credencial de recuperación se generará en tu dispositivo, no por un administrador.", "Pasi të përdoret autorizimi i përkohshëm, FICONTER duhet të rikthejë qasjen në të njëjtin çelës të enkriptuar të kasafortës përmes mekanizmit të mbrojtur të çelësit të rikuperimit. Kredenciali juaj zëvendësues i rikuperimit do të gjenerohet në pajisjen tuaj, jo nga një administrator.", "بعد استخدام التفويض المؤقت، يجب على FICONTER استعادة الوصول إلى مفتاح الخزنة المشفر نفسه عبر آلية مفتاح الاستعادة المحمية. سيتم إنشاء بيانات اعتماد الاستعادة البديلة على جهازك، وليس بواسطة مسؤول.", "Depois de a autorização temporária ser utilizada, a FICONTER tem de restaurar o acesso à mesma chave encriptada do cofre através do mecanismo protegido de chave de recuperação. A credencial de recuperação de substituição será gerada no seu dispositivo, não por um administrador.", "Dopo l'utilizzo dell'autorizzazione temporanea, FICONTER deve ripristinare l'accesso alla stessa chiave crittografata del caveau tramite il meccanismo protetto della chiave di recupero. La nuova credenziale di recupero verrà generata sul tuo dispositivo, non da un amministratore.", "После активации временного разрешения FICONTER должен восстановить доступ к тому же зашифрованному ключу хранилища через защищённый механизм ключа восстановления. Новые учётные данные восстановления будут созданы на вашем устройстве, а не администратором."),
  "One email address can belong to only one FICONTER account. If this email is already registered, use the existing account instead.": row("Eine E-Mail-Adresse kann nur zu einem FICONTER-Konto gehören. Wenn diese E-Mail bereits registriert ist, verwenden Sie stattdessen das bestehende Konto.", "Una dirección de correo electrónico solo puede pertenecer a una cuenta de FICONTER. Si este correo ya está registrado, utiliza la cuenta existente.", "Një adresë emaili mund t'i përkasë vetëm një llogarie FICONTER. Nëse ky email është regjistruar tashmë, përdorni llogarinë ekzistuese.", "يمكن لعنوان بريد إلكتروني واحد أن ينتمي إلى حساب FICONTER واحد فقط. إذا كان هذا البريد مسجلًا بالفعل، فاستخدم الحساب الحالي بدلًا من ذلك.", "Um endereço de email só pode pertencer a uma conta FICONTER. Se este email já estiver registado, utilize a conta existente.", "Un indirizzo email può appartenere a un solo account FICONTER. Se questa email è già registrata, usa l'account esistente.", "Один адрес электронной почты может принадлежать только одному аккаунту FICONTER. Если этот адрес уже зарегистрирован, используйте существующий аккаунт."),
  "Unlock your Financial Vault before creating an encrypted business workspace.": row("Entsperren Sie Ihren Finanz-Tresor, bevor Sie einen verschlüsselten Unternehmensarbeitsbereich erstellen.", "Desbloquea tu bóveda financiera antes de crear un espacio de trabajo empresarial cifrado.", "Zhbllokoni kasafortën tuaj financiare përpara se të krijoni një hapësirë pune biznesi të enkriptuar.", "افتح خزنتك المالية قبل إنشاء مساحة عمل أعمال مشفرة.", "Desbloqueie o seu Cofre Financeiro antes de criar um espaço de trabalho empresarial encriptado.", "Sblocca il tuo Caveau Finanziario prima di creare un'area di lavoro aziendale crittografata.", "Разблокируйте финансовое хранилище перед созданием зашифрованного рабочего пространства для бизнеса."),
  "The business workspace could not be created.": row("Der Unternehmensarbeitsbereich konnte nicht erstellt werden.", "No se pudo crear el espacio de trabajo empresarial.", "Hapësira e punës së biznesit nuk mund të krijohej.", "تعذر إنشاء مساحة عمل الأعمال.", "Não foi possível criar o espaço de trabalho empresarial.", "Non è stato possibile creare l'area di lavoro aziendale.", "Не удалось создать рабочее пространство для бизнеса."),
  "Protected with Business Vault encryption and membership access.": row("Geschützt durch Business-Vault-Verschlüsselung und Mitgliederzugriff.", "Protegido con cifrado de Business Vault y acceso por membresía.", "E mbrojtur me enkriptimin e Business Vault dhe qasje sipas anëtarësimit.", "محمي بتشفير Business Vault ووصول العضوية.", "Protegido com encriptação Business Vault e acesso por associação.", "Protetto con crittografia Business Vault e accesso dei membri.", "Защищено шифрованием Business Vault и доступом по членству."),
  "Business vault could not be opened.": row("Der Business-Tresor konnte nicht geöffnet werden.", "No se pudo abrir la bóveda empresarial.", "Kasaforta e biznesit nuk mund të hapej.", "تعذر فتح خزنة الأعمال.", "Não foi possível abrir o cofre empresarial.", "Non è stato possibile aprire il caveau aziendale.", "Не удалось открыть бизнес-хранилище."),
  "Credit card interest estimator": row("Kreditkarten-Zinsrechner", "Estimador de intereses de tarjeta de crédito", "Llogaritësi i interesit të kartës së kreditit", "حاسبة تقديرية لفائدة بطاقة الائتمان", "Estimador de juros do cartão de crédito", "Stimatore degli interessi della carta di credito", "Калькулятор процентов по кредитной карте"),
  "Credit Card Interest Estimator": row("Kreditkarten-Zinsrechner", "Estimador de intereses de tarjeta de crédito", "Llogaritësi i interesit të kartës së kreditit", "حاسبة تقديرية لفائدة بطاقة الائتمان", "Estimador de juros do cartão de crédito", "Stimatore degli interessi della carta di credito", "Калькулятор процентов по кредитной карте"),
  "Approximate only. Your issuer may calculate interest differently.": row("Nur Näherungswert. Ihr Kartenanbieter kann Zinsen anders berechnen.", "Solo aproximado. Tu emisor puede calcular los intereses de forma diferente.", "Vetëm përafërsisht. Lëshuesi i kartës mund ta llogarisë interesin ndryshe.", "تقديري فقط. قد تحسب جهة إصدار البطاقة الفائدة بطريقة مختلفة.", "Apenas aproximado. O emissor do cartão pode calcular os juros de forma diferente.", "Solo una stima. L'emittente della carta può calcolare gli interessi diversamente.", "Только приблизительная оценка. Эмитент карты может рассчитывать проценты иначе."),
  "Planned purchase": row("Geplanter Kauf", "Compra planificada", "Blerje e planifikuar", "شراء مخطط", "Compra planeada", "Acquisto pianificato", "Запланированная покупка"),
  "Estimated monthly interest now": row("Geschätzte monatliche Zinsen aktuell", "Interés mensual estimado actual", "Interesi mujor i vlerësuar tani", "الفائدة الشهرية التقديرية الآن", "Juros mensais estimados agora", "Interessi mensili stimati attuali", "Текущие расчётные проценты за месяц"),
  "Extra interest from purchase": row("Zusätzliche Zinsen durch den Kauf", "Interés adicional por la compra", "Interes shtesë nga blerja", "فائدة إضافية بسبب الشراء", "Juros adicionais da compra", "Interessi aggiuntivi dovuti all'acquisto", "Дополнительные проценты из-за покупки"),
  "Projected balance": row("Voraussichtlicher Saldo", "Saldo previsto", "Bilanci i parashikuar", "الرصيد المتوقع", "Saldo projetado", "Saldo previsto", "Прогнозируемый баланс"),
  "Projected monthly interest": row("Voraussichtliche monatliche Zinsen", "Interés mensual previsto", "Interesi mujor i parashikuar", "الفائدة الشهرية المتوقعة", "Juros mensais projetados", "Interessi mensili previsti", "Прогнозируемые проценты за месяц"),
  "Estimate uses balance × APR ÷ 12. It does not post interest or change your card balance. Actual bank interest remains editable when the statement arrives.": row("Die Schätzung verwendet Saldo × effektiven Jahreszins ÷ 12. Sie verbucht keine Zinsen und ändert Ihren Kartensaldo nicht. Die tatsächlichen Bankzinsen bleiben bearbeitbar, sobald die Abrechnung vorliegt.", "La estimación usa saldo × TAE ÷ 12. No contabiliza intereses ni modifica el saldo de tu tarjeta. Los intereses reales del banco siguen siendo editables cuando llegue el extracto.", "Vlerësimi përdor bilancin × APR ÷ 12. Nuk regjistron interes dhe nuk ndryshon bilancin e kartës. Interesi real i bankës mbetet i redaktueshëm kur të mbërrijë pasqyra.", "يستخدم التقدير الرصيد × معدل النسبة السنوية ÷ 12. ولا يسجل الفائدة أو يغير رصيد البطاقة. تبقى فائدة البنك الفعلية قابلة للتعديل عند وصول كشف الحساب.", "A estimativa utiliza saldo × TAEG ÷ 12. Não lança juros nem altera o saldo do cartão. Os juros reais do banco continuam editáveis quando o extrato chegar.", "La stima usa saldo × TAEG ÷ 12. Non registra interessi né modifica il saldo della carta. Gli interessi bancari effettivi restano modificabili quando arriva l'estratto conto.", "Расчёт использует баланс × годовую процентную ставку ÷ 12. Он не начисляет проценты и не изменяет баланс карты. Фактические банковские проценты можно редактировать после получения выписки."),
  "Smart Insights could not be opened.": row("Smart Insights konnte nicht geöffnet werden.", "No se pudo abrir Smart Insights.", "Smart Insights nuk mund të hapej.", "تعذر فتح Smart Insights.", "Não foi possível abrir o Smart Insights.", "Non è stato possibile aprire Smart Insights.", "Не удалось открыть Smart Insights."),
  "Unlock your Financial Vault to open Smart Insights.": row("Entsperren Sie Ihren Finanz-Tresor, um Smart Insights zu öffnen.", "Desbloquea tu bóveda financiera para abrir Smart Insights.", "Zhbllokoni kasafortën tuaj financiare për të hapur Smart Insights.", "افتح خزنتك المالية لفتح Smart Insights.", "Desbloqueie o seu Cofre Financeiro para abrir o Smart Insights.", "Sblocca il tuo Caveau Finanziario per aprire Smart Insights.", "Разблокируйте финансовое хранилище, чтобы открыть Smart Insights."),
  "Encrypted Bills could not be opened.": row("Verschlüsselte Rechnungen konnten nicht geöffnet werden.", "No se pudieron abrir las facturas cifradas.", "Faturat e enkriptuara nuk mund të hapeshin.", "تعذر فتح الفواتير المشفرة.", "Não foi possível abrir as faturas encriptadas.", "Non è stato possibile aprire le fatture crittografate.", "Не удалось открыть зашифрованные счета."),
  "Business Administration could not be opened.": row("Die Unternehmensverwaltung konnte nicht geöffnet werden.", "No se pudo abrir la administración empresarial.", "Administrimi i biznesit nuk mund të hapej.", "تعذر فتح إدارة الأعمال.", "Não foi possível abrir a Administração Empresarial.", "Non è stato possibile aprire l'Amministrazione aziendale.", "Не удалось открыть управление бизнесом."),
  "Unlock your Financial Vault to open encrypted Business Administration.": row("Entsperren Sie Ihren Finanz-Tresor, um die verschlüsselte Unternehmensverwaltung zu öffnen.", "Desbloquea tu bóveda financiera para abrir la administración empresarial cifrada.", "Zhbllokoni kasafortën tuaj financiare për të hapur administrimin e enkriptuar të biznesit.", "افتح خزنتك المالية لفتح إدارة الأعمال المشفرة.", "Desbloqueie o seu Cofre Financeiro para abrir a Administração Empresarial encriptada.", "Sblocca il tuo Caveau Finanziario per aprire l'Amministrazione aziendale crittografata.", "Разблокируйте финансовое хранилище, чтобы открыть зашифрованное управление бизнесом."),
  "This Business Vault has not been shared with your account yet.": row("Dieser Business-Tresor wurde noch nicht mit Ihrem Konto geteilt.", "Esta bóveda empresarial aún no se ha compartido con tu cuenta.", "Kjo kasafortë biznesi nuk është ndarë ende me llogarinë tuaj.", "لم تتم مشاركة خزنة الأعمال هذه مع حسابك بعد.", "Este cofre empresarial ainda não foi partilhado com a sua conta.", "Questo caveau aziendale non è ancora stato condiviso con il tuo account.", "Это бизнес-хранилище ещё не предоставлено вашему аккаунту.")
};

export function translateGovernancePhraseBatch2(language: FiconterLanguage, source: string): string | null {
  if (language === "en") return source;
  return GOVERNANCE_UI_TRANSLATIONS_BATCH_2[source]?.[language] ?? null;
}
