import type { FiconterLanguage } from "./config";

type NonEnglishLanguage = Exclude<FiconterLanguage, "en">;
type TranslationRow = Record<NonEnglishLanguage, string>;

function row(de: string, es: string, sq: string, ar: string, pt: string, it: string, ru: string): TranslationRow {
  return { de, es, sq, ar, pt, it, ru };
}

export const GOVERNANCE_UI_TRANSLATIONS_BATCH_8: Record<string, TranslationRow> = {
  "Use this once to activate the emergency recovery envelope and rotate to a new code.": row("Verwende dies einmal, um den Notfall-Wiederherstellungsumschlag zu aktivieren und zu einem neuen Code zu wechseln.", "Úsalo una vez para activar el sobre de recuperación de emergencia y cambiar a un código nuevo.", "Përdore një herë për të aktivizuar zarfin e rikuperimit emergjent dhe për të kaluar në një kod të ri.", "استخدم هذا مرة واحدة لتفعيل حزمة الاسترداد الطارئ والانتقال إلى رمز جديد.", "Use isto uma vez para ativar o envelope de recuperação de emergência e mudar para um novo código.", "Usalo una volta per attivare l'involucro di recupero di emergenza e passare a un nuovo codice.", "Используйте это один раз, чтобы активировать аварийный механизм восстановления и перейти на новый код."),
  "Current recovery code": row("Aktueller Wiederherstellungscode", "Código de recuperación actual", "Kodi aktual i rikuperimit", "رمز الاسترداد الحالي", "Código de recuperação atual", "Codice di recupero attuale", "Текущий код восстановления"),
  "Protecting Vault…": row("Tresor wird geschützt…", "Protegiendo la bóveda…", "Po mbrohet kasaforta…", "جارٍ حماية الخزنة…", "A proteger o cofre…", "Protezione del caveau…", "Защита хранилища…"),
  "Generate replacement recovery code": row("Ersatz-Wiederherstellungscode erstellen", "Generar código de recuperación de sustitución", "Gjenero kod zëvendësues rikuperimi", "إنشاء رمز استرداد بديل", "Gerar código de recuperação de substituição", "Genera codice di recupero sostitutivo", "Создать новый код восстановления"),
  "I no longer have my recovery code": row("Ich habe meinen Wiederherstellungscode nicht mehr", "Ya no tengo mi código de recuperación", "Nuk e kam më kodin tim të rikuperimit", "لم يعد لدي رمز الاسترداد", "Já não tenho o meu código de recuperação", "Non ho più il mio codice di recupero", "У меня больше нет кода восстановления"),
  "Use FICONTER Assisted Recovery. A temporary key is created in this browser, the managed recovery boundary re-wraps the same Vault key specifically to this session, and your browser creates a new recovery code.": row("Verwende die unterstützte Wiederherstellung von FICONTER. In diesem Browser wird ein temporärer Schlüssel erstellt, die verwaltete Wiederherstellungsgrenze verpackt denselben Tresorschlüssel speziell für diese Sitzung neu, und dein Browser erstellt einen neuen Wiederherstellungscode.", "Usa la Recuperación Asistida de FICONTER. Se crea una clave temporal en este navegador, el límite de recuperación gestionado vuelve a envolver la misma clave de la bóveda específicamente para esta sesión y tu navegador crea un nuevo código de recuperación.", "Përdor Rikuperimin e Asistuar të FICONTER. Në këtë shfletues krijohet një çelës i përkohshëm, kufiri i menaxhuar i rikuperimit e rimbështjell të njëjtin çelës të kasafortës posaçërisht për këtë sesion dhe shfletuesi yt krijon një kod të ri rikuperimi.", "استخدم الاسترداد بمساعدة FICONTER. يتم إنشاء مفتاح مؤقت في هذا المتصفح، ويعيد نطاق الاسترداد المُدار تغليف مفتاح الخزنة نفسه خصيصًا لهذه الجلسة، ثم ينشئ متصفحك رمز استرداد جديدًا.", "Use a Recuperação Assistida FICONTER. É criada uma chave temporária neste navegador, o limite de recuperação gerido volta a envolver a mesma chave do cofre especificamente para esta sessão e o navegador cria um novo código de recuperação.", "Usa il Recupero Assistito FICONTER. In questo browser viene creata una chiave temporanea, il confine di recupero gestito riavvolge la stessa chiave del caveau specificamente per questa sessione e il browser crea un nuovo codice di recupero.", "Используйте восстановление с помощью FICONTER. В этом браузере создаётся временный ключ, управляемая граница восстановления повторно оборачивает тот же ключ хранилища специально для этой сессии, а браузер создаёт новый код восстановления."),
  "Recovering Vault…": row("Tresor wird wiederhergestellt…", "Recuperando la bóveda…", "Po rikuperohet kasaforta…", "جارٍ استرداد الخزنة…", "A recuperar o cofre…", "Recupero del caveau…", "Восстановление хранилища…"),
  "Recover without old code": row("Ohne alten Code wiederherstellen", "Recuperar sin código anterior", "Rikupero pa kodin e vjetër", "الاسترداد بدون الرمز القديم", "Recuperar sem o código antigo", "Recupera senza il vecchio codice", "Восстановить без старого кода"),
  "Vault recovery completed": row("Tresor-Wiederherstellung abgeschlossen", "Recuperación de la bóveda completada", "Rikuperimi i kasafortës përfundoi", "اكتمل استرداد الخزنة", "Recuperação do cofre concluída", "Recupero del caveau completato", "Восстановление хранилища завершено"),
  "Save this new recovery code now. The previous recovery credential is no longer active. The same underlying Vault key was preserved, so your existing encrypted financial records remain tied to the same Vault.": row("Speichere diesen neuen Wiederherstellungscode jetzt. Die vorherige Wiederherstellungsberechtigung ist nicht mehr aktiv. Derselbe zugrunde liegende Tresorschlüssel wurde beibehalten, daher bleiben deine bestehenden verschlüsselten Finanzdaten mit demselben Tresor verbunden.", "Guarda ahora este nuevo código de recuperación. La credencial de recuperación anterior ya no está activa. Se conservó la misma clave subyacente de la bóveda, por lo que tus registros financieros cifrados existentes siguen vinculados a la misma bóveda.", "Ruaje tani këtë kod të ri rikuperimi. Kredenciali i mëparshëm i rikuperimit nuk është më aktiv. U ruajt i njëjti çelës bazë i kasafortës, prandaj të dhënat e tua financiare të enkriptuara mbeten të lidhura me të njëjtën kasafortë.", "احفظ رمز الاسترداد الجديد الآن. بيانات اعتماد الاسترداد السابقة لم تعد نشطة. تم الحفاظ على مفتاح الخزنة الأساسي نفسه، لذلك تظل سجلاتك المالية المشفرة الحالية مرتبطة بالخزنة نفسها.", "Guarde agora este novo código de recuperação. A credencial de recuperação anterior já não está ativa. A mesma chave subjacente do cofre foi preservada, por isso os registos financeiros encriptados existentes continuam ligados ao mesmo cofre.", "Salva ora questo nuovo codice di recupero. La precedente credenziale di recupero non è più attiva. È stata preservata la stessa chiave sottostante del caveau, quindi i dati finanziari crittografati esistenti restano legati allo stesso caveau.", "Сохраните новый код восстановления сейчас. Предыдущие учётные данные восстановления больше не активны. Тот же базовый ключ хранилища сохранён, поэтому существующие зашифрованные финансовые записи остаются привязаны к тому же хранилищу."),
  "FICONTER staff do not receive the readable Vault key or this replacement recovery code.": row("FICONTER-Mitarbeiter erhalten weder den lesbaren Tresorschlüssel noch diesen neuen Wiederherstellungscode.", "El personal de FICONTER no recibe la clave legible de la bóveda ni este código de recuperación de sustitución.", "Stafi i FICONTER nuk merr çelësin e lexueshëm të kasafortës ose këtë kod zëvendësues rikuperimi.", "لا يتلقى موظفو FICONTER مفتاح الخزنة القابل للقراءة ولا رمز الاسترداد البديل هذا.", "A equipa FICONTER não recebe a chave legível do cofre nem este código de recuperação de substituição.", "Il personale FICONTER non riceve la chiave leggibile del caveau né questo codice di recupero sostitutivo.", "Сотрудники FICONTER не получают читаемый ключ хранилища или новый код восстановления."),
  "For security, this authorization can no longer be used. FICONTER Support must issue a new temporary Recovery Access.": row("Aus Sicherheitsgründen kann diese Autorisierung nicht mehr verwendet werden. Der FICONTER-Support muss einen neuen temporären Wiederherstellungszugang ausstellen.", "Por seguridad, esta autorización ya no puede utilizarse. El Soporte de FICONTER debe emitir un nuevo Acceso de Recuperación temporal.", "Për arsye sigurie, ky autorizim nuk mund të përdoret më. Mbështetja e FICONTER duhet të lëshojë një Qasje të re të përkohshme Rikuperimi.", "لأسباب أمنية، لم يعد من الممكن استخدام هذا التفويض. يجب أن يصدر دعم FICONTER وصول استرداد مؤقتًا جديدًا.", "Por motivos de segurança, esta autorização já não pode ser utilizada. O Suporte FICONTER tem de emitir um novo Acesso de Recuperação temporário.", "Per motivi di sicurezza, questa autorizzazione non può più essere utilizzata. L'Assistenza FICONTER deve emettere un nuovo Accesso di Recupero temporaneo.", "По соображениям безопасности эту авторизацию больше нельзя использовать. Поддержка FICONTER должна выдать новый временный доступ для восстановления."),
  "This authorization cannot be used. Contact FICONTER Support if recovery still needs to continue.": row("Diese Autorisierung kann nicht verwendet werden. Kontaktiere den FICONTER-Support, wenn die Wiederherstellung fortgesetzt werden muss.", "Esta autorización no puede utilizarse. Contacta con el Soporte de FICONTER si la recuperación debe continuar.", "Ky autorizim nuk mund të përdoret. Kontakto Mbështetjen e FICONTER nëse rikuperimi duhet të vazhdojë.", "لا يمكن استخدام هذا التفويض. تواصل مع دعم FICONTER إذا كان يجب متابعة الاسترداد.", "Esta autorização não pode ser utilizada. Contacte o Suporte FICONTER se a recuperação ainda tiver de continuar.", "Questa autorizzazione non può essere utilizzata. Contatta l'Assistenza FICONTER se il recupero deve continuare.", "Эту авторизацию нельзя использовать. Обратитесь в поддержку FICONTER, если восстановление необходимо продолжить."),
  "Recovery Access completed": row("Wiederherstellungszugang abgeschlossen", "Acceso de Recuperación completado", "Qasja e Rikuperimit përfundoi", "اكتمل وصول الاسترداد", "Acesso de Recuperação concluído", "Accesso di Recupero completato", "Доступ для восстановления завершён"),
  "This one-time authorization has already been consumed and cannot be reused.": row("Diese einmalige Autorisierung wurde bereits verwendet und kann nicht erneut genutzt werden.", "Esta autorización de un solo uso ya se ha consumido y no puede reutilizarse.", "Ky autorizim njëpërdorimësh është përdorur tashmë dhe nuk mund të ripërdoret.", "تم استخدام هذا التفويض لمرة واحدة بالفعل ولا يمكن إعادة استخدامه.", "Esta autorização de utilização única já foi consumida e não pode ser reutilizada.", "Questa autorizzazione monouso è già stata utilizzata e non può essere riutilizzata.", "Эта одноразовая авторизация уже использована и не может быть применена повторно."),
  "Recovery authorization and Vault decryption remain separate security steps. Assisted Recovery preserves the existing Vault encryption key instead of creating an empty Vault.": row("Wiederherstellungsautorisierung und Tresorentschlüsselung bleiben getrennte Sicherheitsschritte. Die unterstützte Wiederherstellung bewahrt den bestehenden Verschlüsselungsschlüssel des Tresors, statt einen leeren Tresor zu erstellen.", "La autorización de recuperación y el descifrado de la bóveda siguen siendo pasos de seguridad separados. La Recuperación Asistida conserva la clave de cifrado existente de la bóveda en lugar de crear una bóveda vacía.", "Autorizimi i rikuperimit dhe dekriptimi i kasafortës mbeten hapa të ndarë sigurie. Rikuperimi i Asistuar ruan çelësin ekzistues të enkriptimit të kasafortës në vend që të krijojë një kasafortë bosh.", "تظل موافقة الاسترداد وفك تشفير الخزنة خطوتين أمنيتين منفصلتين. يحافظ الاسترداد بمساعدة على مفتاح تشفير الخزنة الحالي بدلًا من إنشاء خزنة فارغة.", "A autorização de recuperação e a desencriptação do cofre continuam a ser etapas de segurança separadas. A Recuperação Assistida preserva a chave de encriptação existente do cofre em vez de criar um cofre vazio.", "L'autorizzazione al recupero e la decrittografia del caveau restano passaggi di sicurezza separati. Il Recupero Assistito preserva la chiave di crittografia esistente del caveau invece di crearne uno vuoto.", "Авторизация восстановления и расшифровка хранилища остаются отдельными этапами безопасности. Восстановление с помощью поддержки сохраняет существующий ключ шифрования хранилища вместо создания пустого хранилища."),
  "Delete this recovery case?": row("Diesen Wiederherstellungsfall löschen?", "¿Eliminar este caso de recuperación?", "Ta fshish këtë rast rikuperimi?", "حذف حالة الاسترداد هذه؟", "Eliminar este caso de recuperação?", "Eliminare questo caso di recupero?", "Удалить этот случай восстановления?"),
  "This permanently removes the archived recovery case and its associated recovery records that are eligible for deletion. This action cannot be undone.": row("Dadurch werden der archivierte Wiederherstellungsfall und die zugehörigen löschbaren Wiederherstellungsdatensätze dauerhaft entfernt. Diese Aktion kann nicht rückgängig gemacht werden.", "Esto elimina permanentemente el caso de recuperación archivado y los registros de recuperación asociados que pueden borrarse. Esta acción no se puede deshacer.", "Kjo heq përgjithmonë rastin e arkivuar të rikuperimit dhe të dhënat përkatëse të rikuperimit që lejohen të fshihen. Ky veprim nuk mund të zhbëhet.", "يؤدي هذا إلى حذف حالة الاسترداد المؤرشفة وسجلات الاسترداد المرتبطة المؤهلة للحذف نهائيًا. لا يمكن التراجع عن هذا الإجراء.", "Isto remove permanentemente o caso de recuperação arquivado e os registos de recuperação associados elegíveis para eliminação. Esta ação não pode ser anulada.", "Questo rimuove definitivamente il caso di recupero archiviato e i relativi record di recupero eliminabili. L'azione non può essere annullata.", "Это навсегда удалит архивный случай восстановления и связанные записи восстановления, доступные для удаления. Действие нельзя отменить."),
  "Recovery records (": row("Wiederherstellungsdatensätze (", "Registros de recuperación (", "Regjistrat e rikuperimit (", "سجلات الاسترداد (", "Registos de recuperação (", "Record di recupero (", "Записи восстановления ("),
  "Signed customer authorizations are recorded here automatically.": row("Unterzeichnete Kundenautorisierungen werden hier automatisch erfasst.", "Las autorizaciones firmadas de los clientes se registran aquí automáticamente.", "Autorizimet e nënshkruara të klientëve regjistrohen këtu automatikisht.", "يتم تسجيل تفويضات العملاء الموقّعة هنا تلقائيًا.", "As autorizações assinadas pelos clientes são registadas aqui automaticamente.", "Le autorizzazioni firmate dai clienti vengono registrate qui automaticamente.", "Подписанные клиентские разрешения автоматически регистрируются здесь."),
  "Document Signed": row("Dokument unterzeichnet", "Documento firmado", "Dokumenti i nënshkruar", "تم توقيع المستند", "Documento assinado", "Documento firmato", "Документ подписан"),
  "FICONTER User ID": row("FICONTER-Benutzer-ID", "ID de usuario de FICONTER", "ID e përdoruesit FICONTER", "معرّف مستخدم FICONTER", "ID de utilizador FICONTER", "ID utente FICONTER", "ID пользователя FICONTER"),
  "Document ID": row("Dokument-ID", "ID de documento", "ID e dokumentit", "معرّف المستند", "ID do documento", "ID documento", "ID документа"),
  "View signed document": row("Unterzeichnetes Dokument anzeigen", "Ver documento firmado", "Shiko dokumentin e nënshkruar", "عرض المستند الموقّع", "Ver documento assinado", "Visualizza documento firmato", "Просмотреть подписанный документ"),
  "Print / save PDF": row("Drucken / PDF speichern", "Imprimir / guardar PDF", "Printo / ruaj PDF", "طباعة / حفظ PDF", "Imprimir / guardar PDF", "Stampa / salva PDF", "Печать / сохранить PDF"),
  "No signed recovery records yet.": row("Noch keine unterzeichneten Wiederherstellungsdatensätze.", "Todavía no hay registros de recuperación firmados.", "Ende nuk ka regjistra rikuperimi të nënshkruar.", "لا توجد سجلات استرداد موقّعة حتى الآن.", "Ainda não existem registos de recuperação assinados.", "Nessun record di recupero firmato finora.", "Подписанных записей восстановления пока нет."),
  "Vault recovery consent requires your signature": row("Die Einwilligung zur Tresor-Wiederherstellung erfordert deine Unterschrift", "El consentimiento para recuperar la bóveda requiere tu firma", "Pëlqimi për rikuperimin e kasafortës kërkon nënshkrimin tënd", "تتطلب موافقة استرداد الخزنة توقيعك", "O consentimento para recuperação do cofre requer a sua assinatura", "Il consenso al recupero del caveau richiede la tua firma", "Согласие на восстановление хранилища требует вашей подписи"),
  "Vault recovery consent submitted": row("Einwilligung zur Tresor-Wiederherstellung übermittelt", "Consentimiento para recuperar la bóveda enviado", "Pëlqimi për rikuperimin e kasafortës u dërgua", "تم إرسال موافقة استرداد الخزنة", "Consentimento para recuperação do cofre enviado", "Consenso al recupero del caveau inviato", "Согласие на восстановление хранилища отправлено"),
  "AES-GCM": row("AES-GCM", "AES-GCM", "AES-GCM", "AES-GCM", "AES-GCM", "AES-GCM", "AES-GCM"),
  "RSA-OAEP": row("RSA-OAEP", "RSA-OAEP", "RSA-OAEP", "RSA-OAEP", "RSA-OAEP", "RSA-OAEP", "RSA-OAEP"),
  "HKDF": row("HKDF", "HKDF", "HKDF", "HKDF", "HKDF", "HKDF", "HKDF"),
  "Credit card payment": row("Kreditkartenzahlung", "Pago de tarjeta de crédito", "Pagesë e kartës së kreditit", "دفعة بطاقة ائتمان", "Pagamento de cartão de crédito", "Pagamento carta di credito", "Платёж по кредитной карте"),
  "Debt payment": row("Schuldenzahlung", "Pago de deuda", "Pagesë borxhi", "دفعة دين", "Pagamento de dívida", "Pagamento debito", "Платёж по долгу"),
  "PBKDF2": row("PBKDF2", "PBKDF2", "PBKDF2", "PBKDF2", "PBKDF2", "PBKDF2", "PBKDF2"),
};

export function translateGovernancePhraseBatch8(language: FiconterLanguage, source: string): string | null {
  if (language === "en") return source;
  return GOVERNANCE_UI_TRANSLATIONS_BATCH_8[source]?.[language] ?? null;
}
