import type { FiconterLanguage } from "./config";

type NonEnglishLanguage = Exclude<FiconterLanguage, "en">;
type TranslationRow = Record<NonEnglishLanguage, string>;

function row(de: string, es: string, sq: string, ar: string, pt: string, it: string, ru: string): TranslationRow {
  return { de, es, sq, ar, pt, it, ru };
}

export const GOVERNANCE_UI_TRANSLATIONS_BATCH_4: Record<string, TranslationRow> = {
  "Opening encrypted transactions…": row("Verschlüsselte Transaktionen werden geöffnet…", "Abriendo transacciones cifradas…", "Po hapen transaksionet e enkriptuara…", "جارٍ فتح المعاملات المشفرة…", "A abrir transações encriptadas…", "Apertura delle transazioni crittografate…", "Открываются зашифрованные транзакции…"),
  "Personal details saved.": row("Persönliche Daten gespeichert.", "Datos personales guardados.", "Të dhënat personale u ruajtën.", "تم حفظ البيانات الشخصية.", "Dados pessoais guardados.", "Dati personali salvati.", "Личные данные сохранены."),
  "Personal details could not be saved.": row("Persönliche Daten konnten nicht gespeichert werden.", "No se pudieron guardar los datos personales.", "Të dhënat personale nuk mund të ruheshin.", "تعذر حفظ البيانات الشخصية.", "Não foi possível guardar os dados pessoais.", "Non è stato possibile salvare i dati personali.", "Не удалось сохранить личные данные."),
  "Personal identity & address": row("Persönliche Identität & Adresse", "Identidad personal y dirección", "Identiteti personal dhe adresa", "الهوية الشخصية والعنوان", "Identidade pessoal e morada", "Identità personale e indirizzo", "Личные данные и адрес"),
  "These details are used for customer identification and authorized Vault recovery records.": row("Diese Angaben werden zur Kundenidentifikation und für autorisierte Vault-Wiederherstellungsunterlagen verwendet.", "Estos datos se utilizan para la identificación del cliente y los registros autorizados de recuperación de la bóveda.", "Këto të dhëna përdoren për identifikimin e klientit dhe regjistrat e autorizuar të rikuperimit të kasafortës.", "تُستخدم هذه البيانات لتحديد هوية العميل ولسجلات استرداد الخزنة المصرح بها.", "Estes dados são utilizados para identificação do cliente e registos autorizados de recuperação do Cofre.", "Questi dati sono utilizzati per l'identificazione del cliente e per i registri autorizzati di recupero del Caveau.", "Эти данные используются для идентификации клиента и авторизованных записей восстановления хранилища."),
  "Edit details": row("Daten bearbeiten", "Editar datos", "Ndrysho të dhënat", "تعديل البيانات", "Editar dados", "Modifica dati", "Изменить данные"),
  "Add details": row("Daten hinzufügen", "Añadir datos", "Shto të dhëna", "إضافة بيانات", "Adicionar dados", "Aggiungi dati", "Добавить данные"),
  "No personal identity or address details have been added yet.": row("Es wurden noch keine persönlichen Identitäts- oder Adressdaten hinzugefügt.", "Aún no se han añadido datos de identidad personal ni dirección.", "Nuk janë shtuar ende të dhëna të identitetit personal ose adresës.", "لم تتم إضافة بيانات الهوية الشخصية أو العنوان بعد.", "Ainda não foram adicionados dados de identidade pessoal ou morada.", "Non sono ancora stati aggiunti dati di identità personale o indirizzo.", "Личные данные или адрес пока не добавлены."),
  "Edit personal identity and address": row("Persönliche Identität und Adresse bearbeiten", "Editar identidad personal y dirección", "Ndrysho identitetin personal dhe adresën", "تعديل الهوية الشخصية والعنوان", "Editar identidade pessoal e morada", "Modifica identità personale e indirizzo", "Изменить личные данные и адрес"),
  "Update the details used for account identification and authorized recovery records.": row("Aktualisieren Sie die Angaben für die Kontenidentifikation und autorisierte Wiederherstellungsunterlagen.", "Actualiza los datos utilizados para identificar la cuenta y los registros autorizados de recuperación.", "Përditësoni të dhënat që përdoren për identifikimin e llogarisë dhe regjistrat e autorizuar të rikuperimit.", "حدّث البيانات المستخدمة لتحديد الحساب وسجلات الاسترداد المصرح بها.", "Atualize os dados usados para identificação da conta e registos autorizados de recuperação.", "Aggiorna i dati utilizzati per l'identificazione dell'account e i registri autorizzati di recupero.", "Обновите данные, используемые для идентификации аккаунта и авторизованных записей восстановления."),
  "Birthdate": row("Geburtsdatum", "Fecha de nacimiento", "Datëlindja", "تاريخ الميلاد", "Data de nascimento", "Data di nascita", "Дата рождения"),
  "Select country / region": row("Land / Region auswählen", "Seleccionar país / región", "Zgjidh shtetin / rajonin", "اختر البلد / المنطقة", "Selecionar país / região", "Seleziona paese / regione", "Выберите страну / регион"),
  "Street address": row("Straßenadresse", "Dirección", "Adresa e rrugës", "عنوان الشارع", "Morada", "Indirizzo", "Улица и номер дома"),
  "Apartment, unit, floor (optional)": row("Wohnung, Einheit, Etage (optional)", "Apartamento, unidad, planta (opcional)", "Apartament, njësi, kat (opsionale)", "الشقة، الوحدة، الطابق (اختياري)", "Apartamento, unidade, piso (opcional)", "Appartamento, unità, piano (opzionale)", "Квартира, помещение, этаж (необязательно)"),
  "Save details": row("Daten speichern", "Guardar datos", "Ruaj të dhënat", "حفظ البيانات", "Guardar dados", "Salva dati", "Сохранить данные"),
  "Could not load the test customer.": row("Der Testkunde konnte nicht geladen werden.", "No se pudo cargar el cliente de prueba.", "Klienti i testimit nuk mund të ngarkohej.", "تعذر تحميل عميل الاختبار.", "Não foi possível carregar o cliente de teste.", "Non è stato possibile caricare il cliente di test.", "Не удалось загрузить тестового клиента."),
  "Test customer created. Save the password now; it is shown only in this browser response.": row("Testkunde erstellt. Speichern Sie das Passwort jetzt; es wird nur in dieser Browser-Antwort angezeigt.", "Cliente de prueba creado. Guarda ahora la contraseña; solo se muestra en esta respuesta del navegador.", "Klienti i testimit u krijua. Ruajeni fjalëkalimin tani; shfaqet vetëm në këtë përgjigje të shfletuesit.", "تم إنشاء عميل الاختبار. احفظ كلمة المرور الآن؛ فهي تظهر فقط في استجابة المتصفح هذه.", "Cliente de teste criado. Guarde agora a palavra-passe; ela é mostrada apenas nesta resposta do navegador.", "Cliente di test creato. Salva ora la password; viene mostrata solo in questa risposta del browser.", "Тестовый клиент создан. Сохраните пароль сейчас; он показывается только в этом ответе браузера."),
  "Could not create the test customer.": row("Der Testkunde konnte nicht erstellt werden.", "No se pudo crear el cliente de prueba.", "Klienti i testimit nuk mund të krijohej.", "تعذر إنشاء عميل الاختبار.", "Não foi possível criar o cliente de teste.", "Non è stato possibile creare il cliente di test.", "Не удалось создать тестового клиента."),
  "Test password reset. Use the new one-time password shown above.": row("Testpasswort zurückgesetzt. Verwenden Sie das oben angezeigte neue Einmalpasswort.", "Contraseña de prueba restablecida. Usa la nueva contraseña de un solo uso mostrada arriba.", "Fjalëkalimi i testimit u rivendos. Përdorni fjalëkalimin e ri njëpërdorimësh të shfaqur më sipër.", "تمت إعادة تعيين كلمة مرور الاختبار. استخدم كلمة المرور الجديدة لمرة واحدة الموضحة أعلاه.", "Palavra-passe de teste reposta. Use a nova palavra-passe de utilização única mostrada acima.", "Password di test reimpostata. Usa la nuova password monouso mostrata sopra.", "Тестовый пароль сброшен. Используйте новый одноразовый пароль, показанный выше."),
  "Could not reset the test password.": row("Das Testpasswort konnte nicht zurückgesetzt werden.", "No se pudo restablecer la contraseña de prueba.", "Fjalëkalimi i testimit nuk mund të rivendosej.", "تعذر إعادة تعيين كلمة مرور الاختبار.", "Não foi possível repor a palavra-passe de teste.", "Non è stato possibile reimpostare la password di test.", "Не удалось сбросить тестовый пароль."),
  "Disposable staging customer deleted.": row("Temporärer Staging-Kunde gelöscht.", "Cliente temporal de staging eliminado.", "Klienti i përkohshëm i staging u fshi.", "تم حذف عميل الاختبار المرحلي المؤقت.", "Cliente temporário de staging eliminado.", "Cliente temporaneo di staging eliminato.", "Временный staging-клиент удалён."),
  "Could not delete the test customer.": row("Der Testkunde konnte nicht gelöscht werden.", "No se pudo eliminar el cliente de prueba.", "Klienti i testimit nuk mund të fshihej.", "تعذر حذف عميل الاختبار.", "Não foi possível eliminar o cliente de teste.", "Non è stato possibile eliminare il cliente di test.", "Не удалось удалить тестового клиента."),
  "STAGING ONLY": row("NUR STAGING", "SOLO STAGING", "VETËM STAGING", "لبيئة STAGING فقط", "APENAS STAGING", "SOLO STAGING", "ТОЛЬКО STAGING"),
  "Recovery test customer": row("Testkunde für Wiederherstellung", "Cliente de prueba de recuperación", "Klient testimi për rikuperim", "عميل اختبار الاسترداد", "Cliente de teste de recuperação", "Cliente di test per il recupero", "Тестовый клиент восстановления"),
  "Creates one disposable, email-confirmed customer account for the E2E assisted-recovery test. This utility is blocked outside the staging Supabase project and requires Owner or Super Admin access.": row("Erstellt ein temporäres, per E-Mail bestätigtes Kundenkonto für den E2E-Test der unterstützten Wiederherstellung. Dieses Werkzeug ist außerhalb des Staging-Supabase-Projekts gesperrt und erfordert Owner- oder Super-Admin-Zugriff.", "Crea una cuenta de cliente desechable y confirmada por correo para la prueba E2E de recuperación asistida. Esta utilidad está bloqueada fuera del proyecto Supabase de staging y requiere acceso de Owner o Super Admin.", "Krijon një llogari klienti të përkohshme, të konfirmuar me email, për testin E2E të rikuperimit të asistuar. Ky mjet bllokohet jashtë projektit Supabase të staging dhe kërkon akses Owner ose Super Admin.", "ينشئ حساب عميل مؤقتًا ومؤكدًا بالبريد الإلكتروني لاختبار الاسترداد المساعد E2E. هذه الأداة محظورة خارج مشروع Supabase المرحلي وتتطلب صلاحية Owner أو Super Admin.", "Cria uma conta de cliente descartável e confirmada por email para o teste E2E de recuperação assistida. Esta ferramenta é bloqueada fora do projeto Supabase de staging e requer acesso Owner ou Super Admin.", "Crea un account cliente temporaneo e confermato via email per il test E2E di recupero assistito. Questa utilità è bloccata fuori dal progetto Supabase di staging e richiede accesso Owner o Super Admin.", "Создаёт одноразовый подтверждённый по email аккаунт клиента для E2E-теста Assisted Recovery. Инструмент заблокирован вне staging-проекта Supabase и требует доступа Owner или Super Admin."),
  "Status:": row("Status:", "Estado:", "Statusi:", "الحالة:", "Estado:", "Stato:", "Статус:"),
  "Customer exists": row("Kunde vorhanden", "El cliente existe", "Klienti ekziston", "العميل موجود", "Cliente existente", "Cliente esistente", "Клиент существует"),
  "Not created": row("Nicht erstellt", "No creado", "Nuk është krijuar", "غير مُنشأ", "Não criado", "Non creato", "Не создан"),
  "Name:": row("Name:", "Nombre:", "Emri:", "الاسم:", "Nome:", "Nome:", "Имя:"),
  "Email:": row("E-Mail:", "Correo electrónico:", "Email:", "البريد الإلكتروني:", "Email:", "Email:", "Эл. почта:"),
  "User ID:": row("Benutzer-ID:", "ID de usuario:", "ID e përdoruesit:", "معرّف المستخدم:", "ID do utilizador:", "ID utente:", "ID пользователя:"),
  "ONE-TIME TEST PASSWORD": row("EINMALIGES TESTPASSWORT", "CONTRASEÑA DE PRUEBA DE UN SOLO USO", "FJALËKALIM TESTIMI NJËPËRDORIMËSH", "كلمة مرور اختبار لمرة واحدة", "PALAVRA-PASSE DE TESTE DE UTILIZAÇÃO ÚNICA", "PASSWORD DI TEST MONOUSO", "ОДНОРАЗОВЫЙ ТЕСТОВЫЙ ПАРОЛЬ"),
  "Creating…": row("Wird erstellt…", "Creando…", "Po krijohet…", "جارٍ الإنشاء…", "A criar…", "Creazione…", "Создание…"),
  "Create test customer": row("Testkunden erstellen", "Crear cliente de prueba", "Krijo klient testimi", "إنشاء عميل اختبار", "Criar cliente de teste", "Crea cliente di test", "Создать тестового клиента"),
  "Resetting…": row("Wird zurückgesetzt…", "Restableciendo…", "Po rivendoset…", "جارٍ إعادة التعيين…", "A repor…", "Reimpostazione…", "Сброс…"),
  "Reset test password": row("Testpasswort zurücksetzen", "Restablecer contraseña de prueba", "Rivendos fjalëkalimin e testimit", "إعادة تعيين كلمة مرور الاختبار", "Repor palavra-passe de teste", "Reimposta password di test", "Сбросить тестовый пароль"),
  "Delete test customer": row("Testkunden löschen", "Eliminar cliente de prueba", "Fshi klientin e testimit", "حذف عميل الاختبار", "Eliminar cliente de teste", "Elimina cliente di test", "Удалить тестового клиента"),
  "Unlock your Financial Vault before editing a transaction.": row("Entsperren Sie Ihren Finanz-Tresor, bevor Sie eine Transaktion bearbeiten.", "Desbloquea tu bóveda financiera antes de editar una transacción.", "Zhbllokoni kasafortën tuaj financiare para se të ndryshoni një transaksion.", "افتح خزنتك المالية قبل تعديل معاملة.", "Desbloqueie o seu Cofre Financeiro antes de editar uma transação.", "Sblocca il tuo Caveau Finanziario prima di modificare una transazione.", "Разблокируйте финансовое хранилище перед редактированием транзакции."),
  "Financial Vault": row("Finanz-Tresor", "Bóveda financiera", "Kasaforta financiare", "الخزنة المالية", "Cofre Financeiro", "Caveau Finanziario", "Финансовое хранилище"),
  "Checking your encrypted vault…": row("Ihr verschlüsselter Tresor wird geprüft…", "Comprobando tu bóveda cifrada…", "Po kontrollohet kasaforta juaj e enkriptuar…", "جارٍ التحقق من خزنتك المشفرة…", "A verificar o seu Cofre encriptado…", "Verifica del Caveau crittografato…", "Проверяется ваше зашифрованное хранилище…"),
  "Create your Financial Vault": row("Erstellen Sie Ihren Finanz-Tresor", "Crea tu bóveda financiera", "Krijoni kasafortën tuaj financiare", "أنشئ خزنتك المالية", "Crie o seu Cofre Financeiro", "Crea il tuo Caveau Finanziario", "Создайте финансовое хранилище"),
  "FICONTER will create a private encryption key inside this browser. The readable key is not stored in the database.": row("FICONTER erstellt in diesem Browser einen privaten Verschlüsselungsschlüssel. Der lesbare Schlüssel wird nicht in der Datenbank gespeichert.", "FICONTER creará una clave privada de cifrado dentro de este navegador. La clave legible no se almacena en la base de datos.", "FICONTER do të krijojë një çelës privat enkriptimi brenda këtij shfletuesi. Çelësi i lexueshëm nuk ruhet në bazën e të dhënave.", "سينشئ FICONTER مفتاح تشفير خاصًا داخل هذا المتصفح. لا يتم تخزين المفتاح القابل للقراءة في قاعدة البيانات.", "O FICONTER criará uma chave privada de encriptação neste navegador. A chave legível não é armazenada na base de dados.", "FICONTER creerà una chiave di crittografia privata all'interno di questo browser. La chiave leggibile non viene memorizzata nel database.", "FICONTER создаст закрытый ключ шифрования в этом браузере. Ключ в читаемом виде не хранится в базе данных."),
  "Creating vault…": row("Tresor wird erstellt…", "Creando bóveda…", "Po krijohet kasaforta…", "جارٍ إنشاء الخزنة…", "A criar o Cofre…", "Creazione del Caveau…", "Создание хранилища…"),
  "Create secure vault": row("Sicheren Tresor erstellen", "Crear bóveda segura", "Krijo kasafortë të sigurt", "إنشاء خزنة آمنة", "Criar Cofre seguro", "Crea Caveau sicuro", "Создать защищённое хранилище"),
  "Financial Vault Locked": row("Finanz-Tresor gesperrt", "Bóveda financiera bloqueada", "Kasaforta financiare e kyçur", "الخزنة المالية مقفلة", "Cofre Financeiro bloqueado", "Caveau Finanziario bloccato", "Финансовое хранилище заблокировано"),
  "Enter your recovery code to unlock your encrypted financial data on this device.": row("Geben Sie Ihren Wiederherstellungscode ein, um Ihre verschlüsselten Finanzdaten auf diesem Gerät zu entsperren.", "Introduce tu código de recuperación para desbloquear tus datos financieros cifrados en este dispositivo.", "Vendosni kodin tuaj të rikuperimit për të zhbllokuar të dhënat financiare të enkriptuara në këtë pajisje.", "أدخل رمز الاسترداد لفتح بياناتك المالية المشفرة على هذا الجهاز.", "Introduza o seu código de recuperação para desbloquear os seus dados financeiros encriptados neste dispositivo.", "Inserisci il codice di recupero per sbloccare i tuoi dati finanziari crittografati su questo dispositivo.", "Введите код восстановления, чтобы разблокировать зашифрованные финансовые данные на этом устройстве."),
  "Unlocking…": row("Wird entsperrt…", "Desbloqueando…", "Po zhbllokohet…", "جارٍ الفتح…", "A desbloquear…", "Sblocco…", "Разблокировка…"),
  "Unlock vault": row("Tresor entsperren", "Desbloquear bóveda", "Zhblloko kasafortën", "فتح الخزنة", "Desbloquear Cofre", "Sblocca Caveau", "Разблокировать хранилище"),
  "Financial Vault Unlocked": row("Finanz-Tresor entsperrt", "Bóveda financiera desbloqueada", "Kasaforta financiare e zhbllokuar", "الخزنة المالية مفتوحة", "Cofre Financeiro desbloqueado", "Caveau Finanziario sbloccato", "Финансовое хранилище разблокировано"),
};

export function translateGovernancePhraseBatch4(language: FiconterLanguage, source: string): string | null {
  if (language === "en") return source;
  return GOVERNANCE_UI_TRANSLATIONS_BATCH_4[source]?.[language] ?? null;
}
