import type { FiconterLanguage } from "./config";

type NonEnglishLanguage = Exclude<FiconterLanguage, "en">;
type TranslationRow = Record<NonEnglishLanguage, string>;

function row(de: string, es: string, sq: string, ar: string, pt: string, it: string, ru: string): TranslationRow {
  return { de, es, sq, ar, pt, it, ru };
}

export const GOVERNANCE_UI_TRANSLATIONS_BATCH_7: Record<string, TranslationRow> = {
  "No matching customer found.": row("Kein passender Kunde gefunden.", "No se encontró ningún cliente coincidente.", "Nuk u gjet asnjë klient që përputhet.", "لم يتم العثور على عميل مطابق.", "Não foi encontrado nenhum cliente correspondente.", "Nessun cliente corrispondente trovato.", "Подходящий клиент не найден."),
  "Generate document": row("Dokument erstellen", "Generar documento", "Gjenero dokumentin", "إنشاء المستند", "Gerar documento", "Genera documento", "Создать документ"),
  "Active cases (": row("Aktive Fälle (", "Casos activos (", "Raste aktive (", "الحالات النشطة (", "Casos ativos (", "Casi attivi (", "Активные случаи ("),
  "No active recovery cases.": row("Keine aktiven Wiederherstellungsfälle.", "No hay casos de recuperación activos.", "Nuk ka raste aktive rikuperimi.", "لا توجد حالات استرداد نشطة.", "Não existem casos de recuperação ativos.", "Nessun caso di recupero attivo.", "Нет активных случаев восстановления."),
  "Archived cases (": row("Archivierte Fälle (", "Casos archivados (", "Raste të arkivuara (", "الحالات المؤرشفة (", "Casos arquivados (", "Casi archiviati (", "Архивные случаи ("),
  "Recovery code could not be rotated.": row("Wiederherstellungscode konnte nicht ersetzt werden.", "No se pudo rotar el código de recuperación.", "Kodi i rikuperimit nuk mund të ndërrohej.", "تعذر تدوير رمز الاسترداد.", "Não foi possível rodar o código de recuperação.", "Impossibile ruotare il codice di recupero.", "Не удалось заменить код восстановления."),
  "Automatic copy was blocked. Select the new recovery code and copy it manually.": row("Das automatische Kopieren wurde blockiert. Wähle den neuen Wiederherstellungscode aus und kopiere ihn manuell.", "La copia automática fue bloqueada. Selecciona el nuevo código de recuperación y cópialo manualmente.", "Kopjimi automatik u bllokua. Zgjidh kodin e ri të rikuperimit dhe kopjoje manualisht.", "تم حظر النسخ التلقائي. حدّد رمز الاسترداد الجديد وانسخه يدويًا.", "A cópia automática foi bloqueada. Selecione o novo código de recuperação e copie-o manualmente.", "La copia automatica è stata bloccata. Seleziona il nuovo codice di recupero e copialo manualmente.", "Автоматическое копирование заблокировано. Выберите новый код восстановления и скопируйте его вручную."),
  "Recovery code replaced": row("Wiederherstellungscode ersetzt", "Código de recuperación sustituido", "Kodi i rikuperimit u zëvendësua", "تم استبدال رمز الاسترداد", "Código de recuperação substituído", "Codice di recupero sostituito", "Код восстановления заменён"),
  "The old recovery code is now invalid. Save this new code somewhere private before leaving this page.": row("Der alte Wiederherstellungscode ist jetzt ungültig. Speichere diesen neuen Code an einem privaten Ort, bevor du diese Seite verlässt.", "El código de recuperación anterior ya no es válido. Guarda este nuevo código en un lugar privado antes de salir de esta página.", "Kodi i vjetër i rikuperimit tani është i pavlefshëm. Ruaje këtë kod të ri në një vend privat para se të largohesh nga kjo faqe.", "رمز الاسترداد القديم لم يعد صالحًا. احفظ هذا الرمز الجديد في مكان خاص قبل مغادرة هذه الصفحة.", "O código de recuperação antigo deixou de ser válido. Guarde este novo código num local privado antes de sair desta página.", "Il vecchio codice di recupero non è più valido. Salva questo nuovo codice in un luogo privato prima di lasciare la pagina.", "Старый код восстановления больше недействителен. Сохраните новый код в безопасном месте перед уходом с этой страницы."),
  "Copy new code": row("Neuen Code kopieren", "Copiar código nuevo", "Kopjo kodin e ri", "نسخ الرمز الجديد", "Copiar novo código", "Copia nuovo codice", "Копировать новый код"),
  "I saved the new code": row("Ich habe den neuen Code gespeichert", "He guardado el código nuevo", "E kam ruajtur kodin e ri", "لقد حفظت الرمز الجديد", "Guardei o novo código", "Ho salvato il nuovo codice", "Я сохранил новый код"),
  "Do not send this code in chat, email, screenshots, or support requests.": row("Sende diesen Code nicht per Chat, E-Mail, Screenshot oder Supportanfrage.", "No envíes este código por chat, correo electrónico, capturas de pantalla ni solicitudes de soporte.", "Mos e dërgo këtë kod në chat, email, pamje ekrani ose kërkesa për mbështetje.", "لا ترسل هذا الرمز عبر الدردشة أو البريد الإلكتروني أو لقطات الشاشة أو طلبات الدعم.", "Não envie este código por chat, email, capturas de ecrã ou pedidos de suporte.", "Non inviare questo codice tramite chat, email, screenshot o richieste di assistenza.", "Не отправляйте этот код в чате, по электронной почте, на скриншотах или в обращениях в поддержку."),
  "Replace recovery code": row("Wiederherstellungscode ersetzen", "Sustituir código de recuperación", "Zëvendëso kodin e rikuperimit", "استبدال رمز الاسترداد", "Substituir código de recuperação", "Sostituisci codice di recupero", "Заменить код восстановления"),
  "Enter your current recovery code. A new code will be generated only in this browser while the same encrypted Vault key and financial data are preserved.": row("Gib deinen aktuellen Wiederherstellungscode ein. Ein neuer Code wird nur in diesem Browser erzeugt, während derselbe verschlüsselte Tresorschlüssel und deine Finanzdaten erhalten bleiben.", "Introduce tu código de recuperación actual. El nuevo código se generará solo en este navegador mientras se conserva la misma clave cifrada de la bóveda y tus datos financieros.", "Vendos kodin aktual të rikuperimit. Një kod i ri do të gjenerohet vetëm në këtë shfletues, ndërsa ruhet i njëjti çelës i enkriptuar i kasafortës dhe të dhënat financiare.", "أدخل رمز الاسترداد الحالي. سيتم إنشاء رمز جديد فقط داخل هذا المتصفح مع الحفاظ على مفتاح الخزنة المشفر نفسه وبياناتك المالية.", "Introduza o código de recuperação atual. Um novo código será gerado apenas neste navegador, mantendo a mesma chave encriptada do cofre e os seus dados financeiros.", "Inserisci il codice di recupero attuale. Un nuovo codice verrà generato solo in questo browser, mantenendo la stessa chiave cifrata del caveau e i dati finanziari.", "Введите текущий код восстановления. Новый код будет создан только в этом браузере, при этом тот же зашифрованный ключ хранилища и финансовые данные сохранятся."),
  "Replacing code…": row("Code wird ersetzt…", "Sustituyendo código…", "Po zëvendësohet kodi…", "جارٍ استبدال الرمز…", "A substituir código…", "Sostituzione del codice…", "Код заменяется…"),
  "Rotate recovery code": row("Wiederherstellungscode rotieren", "Rotar código de recuperación", "Ndrysho kodin e rikuperimit", "تدوير رمز الاسترداد", "Rodar código de recuperação", "Ruota codice di recupero", "Сменить код восстановления"),
  "The signed consent could not be submitted.": row("Die unterzeichnete Einwilligung konnte nicht übermittelt werden.", "No se pudo enviar el consentimiento firmado.", "Pëlqimi i nënshkruar nuk mund të dërgohej.", "تعذر إرسال الموافقة الموقّعة.", "Não foi possível enviar o consentimento assinado.", "Impossibile inviare il consenso firmato.", "Не удалось отправить подписанное согласие."),
  "Signed document submitted": row("Unterzeichnetes Dokument übermittelt", "Documento firmado enviado", "Dokumenti i nënshkruar u dërgua", "تم إرسال المستند الموقّع", "Documento assinado enviado", "Documento firmato inviato", "Подписанный документ отправлен"),
  "FICONTER recorded your electronic consent.": row("FICONTER hat deine elektronische Einwilligung erfasst.", "FICONTER registró tu consentimiento electrónico.", "FICONTER regjistroi pëlqimin tënd elektronik.", "سجّل FICONTER موافقتك الإلكترونية.", "A FICONTER registou o seu consentimento eletrónico.", "FICONTER ha registrato il tuo consenso elettronico.", "FICONTER зарегистрировал ваше электронное согласие."),
  "Type your full legal name in the signature box. Submitting from your authenticated FICONTER account records this as your electronic signature for this recovery request.": row("Gib deinen vollständigen rechtlichen Namen in das Unterschriftsfeld ein. Durch das Absenden aus deinem authentifizierten FICONTER-Konto wird dies als deine elektronische Unterschrift für diese Wiederherstellungsanfrage erfasst.", "Escribe tu nombre legal completo en el campo de firma. Al enviarlo desde tu cuenta de FICONTER autenticada, quedará registrado como tu firma electrónica para esta solicitud de recuperación.", "Shkruaj emrin tënd të plotë ligjor në kutinë e nënshkrimit. Dërgimi nga llogaria jote e autentikuar FICONTER regjistrohet si nënshkrimi yt elektronik për këtë kërkesë rikuperimi.", "اكتب اسمك القانوني الكامل في خانة التوقيع. سيُسجَّل الإرسال من حساب FICONTER الموثّق كتوقيعك الإلكتروني لطلب الاسترداد هذا.", "Introduza o seu nome legal completo no campo de assinatura. O envio a partir da sua conta FICONTER autenticada será registado como assinatura eletrónica para este pedido de recuperação.", "Inserisci il tuo nome legale completo nel campo firma. L'invio dal tuo account FICONTER autenticato verrà registrato come firma elettronica per questa richiesta di recupero.", "Введите полное юридическое имя в поле подписи. Отправка из вашей авторизованной учётной записи FICONTER будет зарегистрирована как электронная подпись для этого запроса на восстановление."),
  "Signature": row("Unterschrift", "Firma", "Nënshkrimi", "التوقيع", "Assinatura", "Firma", "Подпись"),
  "Send signed document": row("Unterzeichnetes Dokument senden", "Enviar documento firmado", "Dërgo dokumentin e nënshkruar", "إرسال المستند الموقّع", "Enviar documento assinado", "Invia documento firmato", "Отправить подписанный документ"),
  "Recovery Access could not be claimed.": row("Wiederherstellungszugang konnte nicht beansprucht werden.", "No se pudo reclamar el Acceso de Recuperación.", "Qasja e Rikuperimit nuk mund të merrej.", "تعذر المطالبة بوصول الاسترداد.", "Não foi possível reivindicar o Acesso de Recuperação.", "Impossibile richiedere l'Accesso di Recupero.", "Не удалось получить доступ для восстановления."),
  "Recovery credential could not be rotated.": row("Wiederherstellungsberechtigung konnte nicht rotiert werden.", "No se pudo rotar la credencial de recuperación.", "Kredenciali i rikuperimit nuk mund të ndërrohej.", "تعذر تدوير بيانات اعتماد الاسترداد.", "Não foi possível rodar a credencial de recuperação.", "Impossibile ruotare la credenziale di recupero.", "Не удалось сменить учётные данные восстановления."),
  "Assisted Recovery could not be completed.": row("Die unterstützte Wiederherstellung konnte nicht abgeschlossen werden.", "No se pudo completar la Recuperación Asistida.", "Rikuperimi i Asistuar nuk mund të përfundonte.", "تعذر إكمال الاسترداد بمساعدة.", "Não foi possível concluir a Recuperação Assistida.", "Impossibile completare il Recupero Assistito.", "Не удалось завершить восстановление с помощью поддержки."),
  "No Recovery Access is currently available.": row("Derzeit ist kein Wiederherstellungszugang verfügbar.", "Actualmente no hay Acceso de Recuperación disponible.", "Aktualisht nuk ka Qasje Rikuperimi të disponueshme.", "لا يتوفر حاليًا وصول للاسترداد.", "Atualmente não existe Acesso de Recuperação disponível.", "Al momento non è disponibile alcun Accesso di Recupero.", "Сейчас доступ для восстановления недоступен."),
  "FICONTER Support must finish verification and authorize this recovery request before secure recovery can begin.": row("Der FICONTER-Support muss die Verifizierung abschließen und diese Wiederherstellungsanfrage autorisieren, bevor die sichere Wiederherstellung beginnen kann.", "El Soporte de FICONTER debe finalizar la verificación y autorizar esta solicitud antes de que pueda comenzar la recuperación segura.", "Mbështetja e FICONTER duhet të përfundojë verifikimin dhe të autorizojë këtë kërkesë para se të fillojë rikuperimi i sigurt.", "يجب أن يكمل دعم FICONTER التحقق ويصرّح بطلب الاسترداد هذا قبل بدء الاسترداد الآمن.", "O Suporte FICONTER tem de concluir a verificação e autorizar este pedido antes de a recuperação segura começar.", "L'Assistenza FICONTER deve completare la verifica e autorizzare questa richiesta prima che possa iniziare il recupero sicuro.", "Служба поддержки FICONTER должна завершить проверку и авторизовать запрос, прежде чем начнётся безопасное восстановление."),
  "Recovery Access ID": row("ID des Wiederherstellungszugangs", "ID del Acceso de Recuperación", "ID e Qasjes së Rikuperimit", "معرّف وصول الاسترداد", "ID do Acesso de Recuperação", "ID Accesso di Recupero", "ID доступа для восстановления"),
  "Temporary Recovery Access is ready": row("Temporärer Wiederherstellungszugang ist bereit", "El Acceso de Recuperación temporal está listo", "Qasja e përkohshme e Rikuperimit është gati", "وصول الاسترداد المؤقت جاهز", "O Acesso de Recuperação temporário está pronto", "L'Accesso di Recupero temporaneo è pronto", "Временный доступ для восстановления готов"),
  "This authorization is bound to your signed-in FICONTER account and expires automatically. It does not expose your Vault key to FICONTER staff.": row("Diese Autorisierung ist an dein angemeldetes FICONTER-Konto gebunden und läuft automatisch ab. Sie legt deinen Tresorschlüssel gegenüber FICONTER-Mitarbeitern nicht offen.", "Esta autorización está vinculada a tu cuenta de FICONTER iniciada y caduca automáticamente. No expone la clave de tu bóveda al personal de FICONTER.", "Ky autorizim lidhet me llogarinë tënde FICONTER ku je i kyçur dhe skadon automatikisht. Ai nuk ua zbulon çelësin e kasafortës stafit të FICONTER.", "هذا التفويض مرتبط بحساب FICONTER الذي سجلت الدخول إليه وتنتهي صلاحيته تلقائيًا. ولا يكشف مفتاح خزنتك لموظفي FICONTER.", "Esta autorização está associada à sua conta FICONTER autenticada e expira automaticamente. Não expõe a chave do cofre à equipa FICONTER.", "Questa autorizzazione è associata al tuo account FICONTER autenticato e scade automaticamente. Non espone la chiave del caveau al personale FICONTER.", "Эта авторизация привязана к вашей учётной записи FICONTER и автоматически истекает. Она не раскрывает ключ хранилища сотрудникам FICONTER."),
  "Claiming…": row("Wird beansprucht…", "Reclamando…", "Po merret…", "جارٍ المطالبة…", "A reivindicar…", "Richiesta in corso…", "Получение доступа…"),
  "Choose the recovery path that matches your situation. Both paths preserve the same encrypted Vault and existing financial records.": row("Wähle den Wiederherstellungsweg, der zu deiner Situation passt. Beide Wege bewahren denselben verschlüsselten Tresor und die bestehenden Finanzdaten.", "Elige la ruta de recuperación que corresponda a tu situación. Ambas rutas conservan la misma bóveda cifrada y los registros financieros existentes.", "Zgjidh rrugën e rikuperimit që i përshtatet situatës tënde. Të dyja rrugët ruajnë të njëjtën kasafortë të enkriptuar dhe të dhënat financiare ekzistuese.", "اختر مسار الاسترداد المناسب لحالتك. كلا المسارين يحافظان على الخزنة المشفرة نفسها والسجلات المالية الحالية.", "Escolha o caminho de recuperação adequado à sua situação. Ambos preservam o mesmo cofre encriptado e os registos financeiros existentes.", "Scegli il percorso di recupero adatto alla tua situazione. Entrambi preservano lo stesso caveau crittografato e i dati finanziari esistenti.", "Выберите подходящий для вашей ситуации путь восстановления. Оба варианта сохраняют то же зашифрованное хранилище и существующие финансовые записи."),
  "Claimed": row("Beansprucht", "Reclamado", "U mor", "تمت المطالبة", "Reivindicado", "Richiesto", "Получено"),
  "I still have my current recovery code": row("Ich habe meinen aktuellen Wiederherstellungscode noch", "Todavía tengo mi código de recuperación actual", "E kam ende kodin tim aktual të rikuperimit", "ما زال لدي رمز الاسترداد الحالي", "Ainda tenho o meu código de recuperação atual", "Ho ancora il mio codice di recupero attuale", "У меня всё ещё есть текущий код восстановления"),
};

export function translateGovernancePhraseBatch7(language: FiconterLanguage, source: string): string | null {
  if (language === "en") return source;
  return GOVERNANCE_UI_TRANSLATIONS_BATCH_7[source]?.[language] ?? null;
}
