import type { FiconterLanguage } from "./config";
import { LANDING_UI_TRANSLATIONS } from "./landingUiCatalog";

type NonEnglishLanguage = Exclude<FiconterLanguage, "en">;
type LandingTranslationRow = Record<NonEnglishLanguage, string>;

function landing(
  de: string,
  es: string,
  sq: string,
  ar: string,
  pt: string,
  it: string,
  ru: string,
): LandingTranslationRow {
  return { de, es, sq, ar, pt, it, ru };
}

export const LANDING_WHY_TRANSLATIONS: Record<string, LandingTranslationRow> = {
  "Back to FICONTER": landing("Zurück zu FICONTER", "Volver a FICONTER", "Kthehu te FICONTER", "العودة إلى FICONTER", "Voltar à FICONTER", "Torna a FICONTER", "Вернуться в FICONTER"),
  "What this means in practice": landing("Was das in der Praxis bedeutet", "Qué significa esto en la práctica", "Çfarë do të thotë kjo në praktikë", "ماذا يعني هذا عمليًا", "O que isto significa na prática", "Cosa significa in pratica", "Что это означает на практике"),
  "How it works": landing("So funktioniert es", "Cómo funciona", "Si funksionon", "كيف يعمل", "Como funciona", "Come funziona", "Как это работает"),
  "A structure that stays understandable.": landing("Eine Struktur, die verständlich bleibt.", "Una estructura que sigue siendo comprensible.", "Një strukturë që mbetet e kuptueshme.", "هيكل يبقى واضحًا ومفهومًا.", "Uma estrutura que continua fácil de compreender.", "Una struttura che resta comprensibile.", "Структура, которая остаётся понятной."),
  "FICONTER keeps the path from information to action deliberate, so the user can see what context they are working in and why a number matters.": landing(
    "FICONTER gestaltet den Weg von Informationen zu Handlungen bewusst, damit Nutzer erkennen, in welchem Kontext sie arbeiten und warum eine Zahl relevant ist.",
    "FICONTER mantiene deliberado el camino de la información a la acción, para que el usuario vea en qué contexto trabaja y por qué importa una cifra.",
    "FICONTER e mban të qartë rrugën nga informacioni te veprimi, që përdoruesi të shohë në çfarë konteksti po punon dhe pse një shifër ka rëndësi.",
    "يحافظ FICONTER على مسار واضح ومدروس من المعلومات إلى الإجراء، حتى يعرف المستخدم السياق الذي يعمل فيه ولماذا يهم كل رقم.",
    "A FICONTER mantém deliberado o caminho da informação à ação, para que o utilizador veja em que contexto está a trabalhar e por que motivo um número é importante.",
    "FICONTER mantiene intenzionale il percorso dall'informazione all'azione, così l'utente vede in quale contesto sta lavorando e perché un numero conta.",
    "FICONTER выстраивает осознанный путь от информации к действию, чтобы пользователь видел, в каком контексте он работает и почему конкретная цифра важна."
  ),
  "Why it matters": landing("Warum das wichtig ist", "Por qué importa", "Pse ka rëndësi", "لماذا يهم", "Porque é importante", "Perché è importante", "Почему это важно"),
  "Related": landing("Verwandte Themen", "Relacionado", "Të ngjashme", "مرتبط", "Relacionado", "Correlato", "Связанные темы"),
  "Explore another part of FICONTER": landing("Einen weiteren Bereich von FICONTER entdecken", "Explora otra parte de FICONTER", "Eksploro një pjesë tjetër të FICONTER", "استكشف جانبًا آخر من FICONTER", "Explore outra parte da FICONTER", "Esplora un'altra parte di FICONTER", "Изучите другой раздел FICONTER"),
  "Bring your financial world into one considered system.": landing("Bringe deine Finanzwelt in ein durchdachtes System.", "Lleva tu mundo financiero a un sistema bien pensado.", "Sill botën tënde financiare në një sistem të menduar mirë.", "اجمع عالمك المالي في نظام واحد مدروس.", "Reúna o seu mundo financeiro num sistema bem pensado.", "Porta il tuo mondo finanziario in un unico sistema ben progettato.", "Соберите свой финансовый мир в одной продуманной системе."),
  "Start with a private workspace and build a clearer picture from there.": landing("Beginne mit einem privaten Arbeitsbereich und entwickle daraus ein klareres Gesamtbild.", "Empieza con un espacio privado y construye desde ahí una visión más clara.", "Fillo me një hapësirë private dhe ndërto prej saj një pamje më të qartë.", "ابدأ بمساحة عمل خاصة وابنِ منها صورة مالية أوضح.", "Comece com um espaço privado e construa a partir daí uma visão mais clara.", "Inizia con uno spazio privato e costruisci da lì un quadro più chiaro.", "Начните с приватного пространства и на его основе сформируйте более ясную картину."),

  "Privacy & account control": landing("Datenschutz & Kontokontrolle", "Privacidad y control de cuenta", "Privatësia dhe kontrolli i llogarisë", "الخصوصية والتحكم بالحساب", "Privacidade e controlo da conta", "Privacy e controllo dell'account", "Конфиденциальность и контроль аккаунта"),
  "Your financial workspace stays yours.": landing("Dein Finanzarbeitsbereich bleibt deiner.", "Tu espacio financiero sigue siendo tuyo.", "Hapësira jote financiare mbetet e jotja.", "تبقى مساحة عملك المالية ملكًا لك.", "O seu espaço financeiro continua a ser seu.", "Il tuo spazio finanziario resta tuo.", "Ваше финансовое пространство остаётся вашим."),
  "FICONTER is structured around authenticated, isolated workspaces so your financial records stay attached to the account and context they belong to.": landing(
    "FICONTER ist um authentifizierte, voneinander getrennte Arbeitsbereiche aufgebaut, damit deine Finanzdaten dem Konto und Kontext zugeordnet bleiben, zu dem sie gehören.",
    "FICONTER se estructura en torno a espacios autenticados y aislados para que tus registros financieros permanezcan vinculados a la cuenta y al contexto que les corresponde.",
    "FICONTER është strukturuar rreth hapësirave të autentikuara dhe të izoluara, që të dhënat e tua financiare të mbeten të lidhura me llogarinë dhe kontekstin përkatës.",
    "تم تصميم FICONTER حول مساحات عمل موثقة ومعزولة حتى تبقى سجلاتك المالية مرتبطة بالحساب والسياق الصحيحين.",
    "A FICONTER está estruturada em torno de espaços autenticados e isolados, para que os seus registos financeiros permaneçam associados à conta e ao contexto a que pertencem.",
    "FICONTER è strutturata attorno a spazi autenticati e isolati, così i tuoi dati finanziari restano associati all'account e al contesto corretti.",
    "FICONTER построен вокруг аутентифицированных изолированных рабочих пространств, чтобы финансовые записи оставались привязаны к нужному аккаунту и контексту."
  ),
  "Privacy is not a single switch. It is part of how FICONTER organises access, records and financial contexts.": landing(
    "Datenschutz ist kein einzelner Schalter. Er ist Teil davon, wie FICONTER Zugriffe, Datensätze und finanzielle Kontexte organisiert.",
    "La privacidad no es un único interruptor. Forma parte de cómo FICONTER organiza el acceso, los registros y los contextos financieros.",
    "Privatësia nuk është një çelës i vetëm. Ajo është pjesë e mënyrës se si FICONTER organizon qasjen, të dhënat dhe kontekstet financiare.",
    "الخصوصية ليست مفتاحًا واحدًا، بل هي جزء من طريقة FICONTER في تنظيم الوصول والسجلات والسياقات المالية.",
    "A privacidade não é um único interruptor. Faz parte da forma como a FICONTER organiza o acesso, os registos e os contextos financeiros.",
    "La privacy non è un singolo interruttore. Fa parte del modo in cui FICONTER organizza accessi, dati e contesti finanziari.",
    "Конфиденциальность — не один переключатель. Она заложена в то, как FICONTER организует доступ, записи и финансовые контексты."
  ),
  "Authenticated access": landing("Authentifizierter Zugriff", "Acceso autenticado", "Qasje e autentikuar", "وصول موثّق", "Acesso autenticado", "Accesso autenticato", "Аутентифицированный доступ"),
  "Private areas are tied to signed-in sessions, so workspace access begins with your FICONTER account.": landing(
    "Private Bereiche sind an angemeldete Sitzungen gebunden, daher beginnt der Zugriff auf den Arbeitsbereich mit deinem FICONTER-Konto.",
    "Las áreas privadas están vinculadas a sesiones iniciadas, por lo que el acceso al espacio comienza con tu cuenta FICONTER.",
    "Zonat private lidhen me sesione të identifikuara, ndaj qasja në hapësirë fillon me llogarinë tënde FICONTER.",
    "ترتبط المناطق الخاصة بجلسات مسجّل الدخول إليها، لذلك يبدأ الوصول إلى مساحة العمل من حسابك في FICONTER.",
    "As áreas privadas estão associadas a sessões autenticadas, pelo que o acesso ao espaço começa com a sua conta FICONTER.",
    "Le aree private sono legate a sessioni con accesso effettuato, quindi l'accesso allo spazio parte dal tuo account FICONTER.",
    "Приватные разделы связаны с авторизованными сессиями, поэтому доступ к рабочему пространству начинается с вашего аккаунта FICONTER."
  ),
  "Account-level isolation": landing("Trennung auf Kontoebene", "Aislamiento a nivel de cuenta", "Izolim në nivel llogarie", "عزل على مستوى الحساب", "Isolamento ao nível da conta", "Isolamento a livello di account", "Изоляция на уровне аккаунта"),
  "Database access policies are designed to keep each customer's records separated from other customer accounts.": landing(
    "Datenbank-Zugriffsrichtlinien sind darauf ausgelegt, die Datensätze jedes Kunden von anderen Kundenkonten getrennt zu halten.",
    "Las políticas de acceso a la base de datos están diseñadas para mantener los registros de cada cliente separados de otras cuentas.",
    "Politikat e qasjes në bazën e të dhënave janë projektuar që të mbajnë të dhënat e çdo klienti të ndara nga llogaritë e klientëve të tjerë.",
    "صُممت سياسات الوصول إلى قاعدة البيانات لإبقاء سجلات كل عميل منفصلة عن حسابات العملاء الآخرين.",
    "As políticas de acesso à base de dados são concebidas para manter os registos de cada cliente separados das contas de outros clientes.",
    "Le policy di accesso al database sono progettate per mantenere i dati di ogni cliente separati dagli account degli altri clienti.",
    "Политики доступа к базе данных предназначены для отделения записей каждого клиента от аккаунтов других клиентов."
  ),
  "Personal and business separation": landing("Trennung von Privat und Geschäft", "Separación personal y empresarial", "Ndarja personale dhe e biznesit", "فصل الشخصي عن التجاري", "Separação pessoal e empresarial", "Separazione tra personale e business", "Разделение личного и делового"),
  "Personal and business records can remain in distinct workspaces, reducing the risk of mixing financial contexts.": landing(
    "Private und geschäftliche Datensätze können in getrennten Arbeitsbereichen bleiben, wodurch das Vermischen finanzieller Kontexte reduziert wird.",
    "Los registros personales y empresariales pueden permanecer en espacios distintos, reduciendo el riesgo de mezclar contextos financieros.",
    "Të dhënat personale dhe të biznesit mund të mbeten në hapësira të ndara, duke ulur rrezikun e përzierjes së konteksteve financiare.",
    "يمكن أن تبقى السجلات الشخصية والتجارية في مساحات منفصلة، مما يقلل خطر خلط السياقات المالية.",
    "Os registos pessoais e empresariais podem permanecer em espaços distintos, reduzindo o risco de misturar contextos financeiros.",
    "I dati personali e aziendali possono restare in spazi distinti, riducendo il rischio di mescolare contesti finanziari.",
    "Личные и деловые записи могут оставаться в отдельных пространствах, снижая риск смешения финансовых контекстов."
  ),
  "No advertising model": landing("Modell ohne Werbung", "Modelo sin publicidad", "Model pa reklama", "نموذج بلا إعلانات", "Modelo sem publicidade", "Modello senza pubblicità", "Модель без рекламы"),
  "FICONTER is built without advertising and without selling financial data as part of the product model.": landing(
    "FICONTER ist als Produktmodell ohne Werbung und ohne Verkauf finanzieller Daten aufgebaut.",
    "FICONTER está construido sin publicidad y sin vender datos financieros como parte del modelo de producto.",
    "FICONTER është ndërtuar pa reklama dhe pa shitjen e të dhënave financiare si pjesë e modelit të produktit.",
    "تم بناء FICONTER من دون إعلانات ومن دون بيع البيانات المالية كجزء من نموذج المنتج.",
    "A FICONTER é construída sem publicidade e sem vender dados financeiros como parte do modelo do produto.",
    "FICONTER è costruita senza pubblicità e senza vendita di dati finanziari come parte del modello di prodotto.",
    "FICONTER построен без рекламы и без продажи финансовых данных как части продуктовой модели."
  ),
  "Deliberate workspace switching": landing("Bewusster Arbeitsbereichswechsel", "Cambio deliberado de espacio", "Ndërrim i qëllimshëm i hapësirës", "تبديل مقصود لمساحة العمل", "Mudança deliberada de espaço", "Cambio intenzionale dello spazio", "Осознанное переключение пространства"),
  "Moving between personal and business is an explicit action, so the user always knows which financial context is active.": landing(
    "Der Wechsel zwischen Privat und Geschäft ist eine bewusste Aktion, sodass der Nutzer immer weiß, welcher finanzielle Kontext aktiv ist.",
    "Cambiar entre personal y empresa es una acción explícita, por lo que el usuario siempre sabe qué contexto financiero está activo.",
    "Kalimi mes personales dhe biznesit është një veprim i qartë, ndaj përdoruesi e di gjithmonë cili kontekst financiar është aktiv.",
    "الانتقال بين الشخصي والتجاري إجراء واضح، لذلك يعرف المستخدم دائمًا أي سياق مالي نشط.",
    "Mudar entre pessoal e empresa é uma ação explícita, para que o utilizador saiba sempre qual o contexto financeiro ativo.",
    "Passare tra personale e business è un'azione esplicita, così l'utente sa sempre quale contesto finanziario è attivo.",
    "Переход между личным и деловым пространством — явное действие, поэтому пользователь всегда знает, какой финансовый контекст активен."
  ),
  "Data and privacy controls": landing("Daten- und Datenschutzkontrollen", "Controles de datos y privacidad", "Kontrolle të të dhënave dhe privatësisë", "ضوابط البيانات والخصوصية", "Controlos de dados e privacidade", "Controlli di dati e privacy", "Управление данными и конфиденциальностью"),
  "Account settings provide a dedicated place for privacy, account and data-management preferences.": landing(
    "Die Kontoeinstellungen bieten einen eigenen Bereich für Datenschutz-, Konto- und Datenverwaltungspräferenzen.",
    "La configuración de la cuenta ofrece un lugar específico para preferencias de privacidad, cuenta y gestión de datos.",
    "Cilësimet e llogarisë ofrojnë një vend të dedikuar për privatësinë, llogarinë dhe preferencat e menaxhimit të të dhënave.",
    "توفر إعدادات الحساب مكانًا مخصصًا لتفضيلات الخصوصية والحساب وإدارة البيانات.",
    "As definições da conta oferecem um local dedicado para preferências de privacidade, conta e gestão de dados.",
    "Le impostazioni dell'account offrono uno spazio dedicato a privacy, account e preferenze di gestione dei dati.",
    "Настройки аккаунта содержат отдельный раздел для параметров конфиденциальности, аккаунта и управления данными."
  ),
  "Sign in": landing("Anmelden", "Iniciar sesión", "Hyr", "تسجيل الدخول", "Iniciar sessão", "Accedi", "Войти"),
  "Access begins through your authenticated FICONTER account.": landing("Der Zugriff beginnt über dein authentifiziertes FICONTER-Konto.", "El acceso comienza a través de tu cuenta FICONTER autenticada.", "Qasja fillon përmes llogarisë tënde të autentikuar FICONTER.", "يبدأ الوصول عبر حسابك الموثق في FICONTER.", "O acesso começa através da sua conta FICONTER autenticada.", "L'accesso inizia tramite il tuo account FICONTER autenticato.", "Доступ начинается через ваш аутентифицированный аккаунт FICONTER."),
  "Work in context": landing("Im Kontext arbeiten", "Trabajar en contexto", "Puno në kontekst", "العمل ضمن السياق", "Trabalhar no contexto", "Lavorare nel contesto", "Работать в контексте"),
  "Your records are shown inside the workspace they belong to.": landing("Deine Datensätze werden in dem Arbeitsbereich angezeigt, zu dem sie gehören.", "Tus registros se muestran dentro del espacio al que pertenecen.", "Të dhënat shfaqen brenda hapësirës së cilës i përkasin.", "تظهر سجلاتك داخل مساحة العمل التي تنتمي إليها.", "Os seus registos são apresentados no espaço a que pertencem.", "I tuoi dati vengono mostrati nello spazio a cui appartengono.", "Ваши записи отображаются в том рабочем пространстве, к которому относятся."),
  "Switch intentionally": landing("Bewusst wechseln", "Cambiar intencionadamente", "Ndërro me qëllim", "التبديل بشكل مقصود", "Mudar de forma intencional", "Cambiare intenzionalmente", "Переключаться осознанно"),
  "Move to another workspace only when you choose to change financial context.": landing("Wechsle nur dann in einen anderen Arbeitsbereich, wenn du bewusst den finanziellen Kontext ändern möchtest.", "Pasa a otro espacio solo cuando decidas cambiar el contexto financiero.", "Kalo në një hapësirë tjetër vetëm kur zgjedh të ndryshosh kontekstin financiar.", "انتقل إلى مساحة عمل أخرى فقط عندما تختار تغيير السياق المالي.", "Mude para outro espaço apenas quando decidir alterar o contexto financeiro.", "Passa a un altro spazio solo quando scegli di cambiare contesto finanziario.", "Переходите в другое пространство только тогда, когда сами решаете изменить финансовый контекст."),
  "Privacy that supports clarity.": landing("Datenschutz, der Klarheit unterstützt.", "Privacidad que favorece la claridad.", "Privatësi që mbështet qartësinë.", "خصوصية تدعم الوضوح.", "Privacidade que apoia a clareza.", "Privacy che sostiene la chiarezza.", "Конфиденциальность, которая поддерживает ясность."),
  "A private workspace is useful because it keeps financial information both protected and understandable. Separation is not only a security concern; it also prevents unrelated records from distorting the picture you are trying to manage.": landing(
    "Ein privater Arbeitsbereich ist nützlich, weil er Finanzinformationen zugleich geschützt und verständlich hält. Trennung ist nicht nur eine Sicherheitsfrage; sie verhindert auch, dass unzusammenhängende Datensätze das Bild verzerren, das du verwalten möchtest.",
    "Un espacio privado es útil porque mantiene la información financiera protegida y comprensible. La separación no es solo una cuestión de seguridad; también evita que registros no relacionados distorsionen la imagen que intentas gestionar.",
    "Një hapësirë private është e dobishme sepse i mban informacionet financiare si të mbrojtura, ashtu edhe të kuptueshme. Ndarja nuk është vetëm çështje sigurie; ajo parandalon edhe që të dhëna të palidhura të shtrembërojnë pamjen që po menaxhon.",
    "تكون مساحة العمل الخاصة مفيدة لأنها تحافظ على المعلومات المالية محمية وواضحة في الوقت نفسه. والفصل ليس مسألة أمن فقط؛ بل يمنع أيضًا السجلات غير المرتبطة من تشويه الصورة التي تحاول إدارتها.",
    "Um espaço privado é útil porque mantém a informação financeira protegida e compreensível. A separação não é apenas uma questão de segurança; também evita que registos sem relação distorçam a visão que está a gerir.",
    "Uno spazio privato è utile perché mantiene le informazioni finanziarie protette e comprensibili. La separazione non è solo una questione di sicurezza; evita anche che dati non correlati distorcano il quadro che stai gestendo.",
    "Приватное рабочее пространство полезно тем, что сохраняет финансовую информацию одновременно защищённой и понятной. Разделение важно не только для безопасности: оно также не позволяет несвязанным записям искажать картину, которой вы управляете."
  ),

  "Financial clarity": landing("Finanzielle Klarheit", "Claridad financiera", "Qartësi financiare", "وضوح مالي", "Clareza financeira", "Chiarezza finanziaria", "Финансовая ясность"),
  "See the whole financial picture, not just a balance.": landing("Sieh das gesamte Finanzbild, nicht nur einen Kontostand.", "Ve toda la imagen financiera, no solo un saldo.", "Shiko të gjithë pamjen financiare, jo vetëm një bilanc.", "شاهد الصورة المالية كاملة، لا مجرد رصيد.", "Veja toda a sua situação financeira, não apenas um saldo.", "Guarda l'intero quadro finanziario, non solo un saldo.", "Смотрите на всю финансовую картину, а не только на баланс."),
  "FICONTER brings daily movement, obligations, reserves, debt, goals and financial indicators into one structured view so you can understand what is happening and what deserves attention.": landing(
    "FICONTER bringt tägliche Bewegungen, Verpflichtungen, Rücklagen, Schulden, Ziele und Finanzindikatoren in eine strukturierte Ansicht, damit du verstehst, was geschieht und was Aufmerksamkeit verdient.",
    "FICONTER reúne movimientos diarios, obligaciones, reservas, deuda, objetivos e indicadores financieros en una vista estructurada para que entiendas qué ocurre y qué merece atención.",
    "FICONTER bashkon lëvizjet ditore, detyrimet, rezervat, borxhin, objektivat dhe treguesit financiarë në një pamje të strukturuar, që të kuptosh çfarë po ndodh dhe çfarë kërkon vëmendje.",
    "يجمع FICONTER الحركة اليومية والالتزامات والاحتياطيات والديون والأهداف والمؤشرات المالية في رؤية منظمة حتى تفهم ما يحدث وما يستحق الاهتمام.",
    "A FICONTER reúne movimentos diários, obrigações, reservas, dívida, objetivos e indicadores financeiros numa visão estruturada, para compreender o que está a acontecer e o que merece atenção.",
    "FICONTER riunisce movimenti quotidiani, impegni, riserve, debiti, obiettivi e indicatori finanziari in una vista strutturata, così puoi capire cosa sta succedendo e cosa richiede attenzione.",
    "FICONTER объединяет ежедневные движения, обязательства, резервы, долги, цели и финансовые показатели в одной структурированной картине, чтобы вы понимали, что происходит и что требует внимания."
  ),
  "A balance tells you what exists at one moment. A financial picture explains how the pieces relate.": landing("Ein Kontostand zeigt, was in einem Moment vorhanden ist. Ein Finanzbild erklärt, wie die Teile zusammenhängen.", "Un saldo te dice qué existe en un momento. Una imagen financiera explica cómo se relacionan las piezas.", "Një bilanc të tregon çfarë ekziston në një moment. Një pamje financiare shpjegon si lidhen pjesët.", "يخبرك الرصيد بما هو موجود في لحظة معينة، بينما تشرح الصورة المالية كيف ترتبط الأجزاء ببعضها.", "Um saldo mostra o que existe num determinado momento. Uma visão financeira explica como as peças se relacionam.", "Un saldo dice cosa esiste in un momento. Un quadro finanziario spiega come si collegano i vari elementi.", "Баланс показывает, что есть в конкретный момент. Финансовая картина объясняет, как элементы связаны между собой."),
  "Income and spending": landing("Einnahmen und Ausgaben", "Ingresos y gastos", "Të ardhura dhe shpenzime", "الدخل والإنفاق", "Rendimentos e despesas", "Entrate e spese", "Доходы и расходы"),
  "Track the movement of money across the month so inflows and outflows have context.": landing("Verfolge die Geldbewegungen über den Monat, damit Ein- und Ausgaben einen Zusammenhang haben.", "Sigue el movimiento del dinero durante el mes para que entradas y salidas tengan contexto.", "Ndiq lëvizjen e parave gjatë muajit që hyrjet dhe daljet të kenë kontekst.", "تتبّع حركة الأموال خلال الشهر حتى تكون التدفقات الداخلة والخارجة ضمن سياق واضح.", "Acompanhe o movimento do dinheiro ao longo do mês para dar contexto às entradas e saídas.", "Segui il movimento del denaro durante il mese, così entrate e uscite hanno un contesto.", "Отслеживайте движение денег в течение месяца, чтобы поступления и расходы имели контекст."),
  "Bills and commitments": landing("Rechnungen und Verpflichtungen", "Facturas y compromisos", "Fatura dhe detyrime", "الفواتير والالتزامات", "Contas e compromissos", "Fatture e impegni", "Счета и обязательства"),
  "See what is already spoken for before treating the remaining amount as truly available.": landing("Sieh, welcher Betrag bereits gebunden ist, bevor du den Rest als wirklich verfügbar behandelst.", "Ve qué cantidad ya está comprometida antes de considerar el resto como realmente disponible.", "Shiko çfarë është tashmë e angazhuar para se pjesën e mbetur ta konsiderosh realisht të disponueshme.", "اعرف ما تم تخصيصه بالفعل قبل اعتبار المبلغ المتبقي متاحًا فعلًا.", "Veja o que já está comprometido antes de considerar o montante restante como realmente disponível.", "Vedi cosa è già impegnato prima di considerare davvero disponibile l'importo restante.", "Сначала учитывайте уже зарезервированные суммы, прежде чем считать остаток действительно доступным."),
  "Savings and reserves": landing("Ersparnisse und Rücklagen", "Ahorros y reservas", "Kursime dhe rezerva", "المدخرات والاحتياطيات", "Poupanças e reservas", "Risparmi e riserve", "Сбережения и резервы"),
  "Follow money set aside for resilience, planned goals and future priorities.": landing("Verfolge Geld, das für Sicherheit, geplante Ziele und zukünftige Prioritäten zurückgelegt wurde.", "Sigue el dinero apartado para resiliencia, objetivos planificados y prioridades futuras.", "Ndiq paratë e ndara për siguri, objektiva të planifikuara dhe prioritete të ardhshme.", "تابع الأموال المخصصة للمرونة والأهداف المخطط لها والأولويات المستقبلية.", "Acompanhe o dinheiro reservado para segurança, objetivos planeados e prioridades futuras.", "Segui il denaro accantonato per solidità, obiettivi pianificati e priorità future.", "Следите за средствами, отложенными для устойчивости, запланированных целей и будущих приоритетов."),
  "Debt and credit obligations": landing("Schulden- und Kreditverpflichtungen", "Deudas y obligaciones de crédito", "Detyrime borxhi dhe kredie", "التزامات الديون والائتمان", "Obrigações de dívida e crédito", "Obblighi di debito e credito", "Долговые и кредитные обязательства"),
  "Keep repayment responsibilities visible alongside the rest of the monthly plan.": landing("Halte Rückzahlungsverpflichtungen neben dem restlichen Monatsplan sichtbar.", "Mantén visibles las obligaciones de pago junto al resto del plan mensual.", "Mbaji detyrimet e shlyerjes të dukshme krahas pjesës tjetër të planit mujor.", "أبقِ التزامات السداد ظاهرة إلى جانب بقية الخطة الشهرية.", "Mantenha as responsabilidades de reembolso visíveis juntamente com o restante plano mensal.", "Mantieni visibili gli obblighi di rimborso insieme al resto del piano mensile.", "Держите обязательства по погашению видимыми рядом с остальной частью месячного плана."),
  "Goals and wealth direction": landing("Ziele und Vermögensrichtung", "Objetivos y dirección patrimonial", "Objektiva dhe drejtim pasurie", "الأهداف واتجاه الثروة", "Objetivos e direção patrimonial", "Obiettivi e direzione patrimoniale", "Цели и направление благосостояния"),
  "Connect short-term decisions with longer-term objectives instead of viewing them as separate problems.": landing("Verbinde kurzfristige Entscheidungen mit langfristigen Zielen, statt sie als getrennte Probleme zu betrachten.", "Conecta decisiones a corto plazo con objetivos a largo plazo en lugar de verlos como problemas separados.", "Lidh vendimet afatshkurtra me objektivat afatgjata, në vend që t'i shohësh si probleme të ndara.", "اربط القرارات قصيرة الأجل بالأهداف طويلة الأجل بدل النظر إليها كمشكلات منفصلة.", "Ligue decisões de curto prazo a objetivos de longo prazo, em vez de os tratar como problemas separados.", "Collega le decisioni di breve termine agli obiettivi di lungo termine invece di considerarli problemi separati.", "Связывайте краткосрочные решения с долгосрочными целями, а не рассматривайте их как отдельные проблемы."),
  "Financial intelligence": landing("Finanzielle Intelligenz", "Inteligencia financiera", "Inteligjencë financiare", "الذكاء المالي", "Inteligência financeira", "Intelligenza finanziaria", "Финансовая аналитика"),
  "Structured indicators can surface financial health, cash-flow position, reserve progress and areas that may need attention.": landing("Strukturierte Indikatoren können finanzielle Gesundheit, Cashflow-Position, Rücklagenfortschritt und Bereiche sichtbar machen, die Aufmerksamkeit benötigen könnten.", "Los indicadores estructurados pueden mostrar salud financiera, posición de flujo de caja, progreso de reservas y áreas que pueden requerir atención.", "Treguesit e strukturuar mund të nxjerrin në pah shëndetin financiar, pozicionin e rrjedhës së parasë, progresin e rezervave dhe fushat që mund të kërkojnë vëmendje.", "يمكن للمؤشرات المنظمة إظهار الصحة المالية ووضع التدفق النقدي وتقدم الاحتياطيات والمجالات التي قد تحتاج إلى اهتمام.", "Indicadores estruturados podem revelar saúde financeira, posição de fluxo de caixa, progresso das reservas e áreas que podem precisar de atenção.", "Indicatori strutturati possono evidenziare salute finanziaria, posizione del flusso di cassa, progresso delle riserve e aree che possono richiedere attenzione.", "Структурированные показатели могут показывать финансовое состояние, позицию денежного потока, прогресс резервов и области, требующие внимания."),
  "Record": landing("Erfassen", "Registrar", "Regjistro", "سجّل", "Registar", "Registra", "Записать"),
  "Add the financial activity and obligations that matter to your plan.": landing("Erfasse die finanziellen Aktivitäten und Verpflichtungen, die für deinen Plan relevant sind.", "Añade la actividad financiera y las obligaciones que importan para tu plan.", "Shto aktivitetin financiar dhe detyrimet që kanë rëndësi për planin tënd.", "أضف النشاط المالي والالتزامات المهمة لخطتك.", "Adicione a atividade financeira e as obrigações que importam para o seu plano.", "Aggiungi l'attività finanziaria e gli obblighi rilevanti per il tuo piano.", "Добавьте финансовую активность и обязательства, важные для вашего плана."),
  "Structure": landing("Strukturieren", "Estructurar", "Strukturo", "نظّم", "Estruturar", "Struttura", "Структурировать"),
  "FICONTER groups the information into meaningful financial contexts.": landing("FICONTER gruppiert die Informationen in sinnvolle finanzielle Kontexte.", "FICONTER agrupa la información en contextos financieros significativos.", "FICONTER e grupon informacionin në kontekste financiare me kuptim.", "يجمع FICONTER المعلومات في سياقات مالية ذات معنى.", "A FICONTER agrupa a informação em contextos financeiros relevantes.", "FICONTER raggruppa le informazioni in contesti finanziari significativi.", "FICONTER группирует информацию по значимым финансовым контекстам."),
  "Understand": landing("Verstehen", "Entender", "Kupto", "افهم", "Compreender", "Comprendi", "Понять"),
  "Indicators and summaries turn individual numbers into a usable picture.": landing("Indikatoren und Zusammenfassungen machen aus einzelnen Zahlen ein nutzbares Gesamtbild.", "Los indicadores y resúmenes convierten cifras individuales en una imagen útil.", "Treguesit dhe përmbledhjet i kthejnë shifrat individuale në një pamje të përdorshme.", "تحوّل المؤشرات والملخصات الأرقام الفردية إلى صورة قابلة للاستخدام.", "Indicadores e resumos transformam números isolados numa visão útil.", "Indicatori e riepiloghi trasformano singoli numeri in un quadro utilizzabile.", "Показатели и сводки превращают отдельные цифры в понятную и полезную картину."),
  "Decide": landing("Entscheiden", "Decidir", "Vendos", "قرّر", "Decidir", "Decidi", "Решить"),
  "Use that picture to prioritise the next action with better context.": landing("Nutze dieses Bild, um die nächste Handlung mit besserem Kontext zu priorisieren.", "Usa esa imagen para priorizar la siguiente acción con mejor contexto.", "Përdore atë pamje për të prioritizuar veprimin e ardhshëm me kontekst më të mirë.", "استخدم هذه الصورة لتحديد أولوية الخطوة التالية ضمن سياق أفضل.", "Use essa visão para priorizar a próxima ação com melhor contexto.", "Usa quel quadro per dare priorità alla prossima azione con un contesto migliore.", "Используйте эту картину, чтобы лучше расставить приоритеты для следующего действия."),
  "Control, not noise.": landing("Kontrolle statt Rauschen.", "Control, no ruido.", "Kontroll, jo zhurmë.", "تحكم بلا ضوضاء.", "Controlo, não ruído.", "Controllo, non rumore.", "Контроль, а не шум."),
  "FICONTER is designed to organise financial information and surface signals. It does not replace professional financial, investment, tax or legal advice.": landing("FICONTER dient dazu, Finanzinformationen zu organisieren und Signale sichtbar zu machen. Es ersetzt keine professionelle Finanz-, Anlage-, Steuer- oder Rechtsberatung.", "FICONTER está diseñado para organizar información financiera y mostrar señales. No sustituye el asesoramiento profesional financiero, de inversión, fiscal o legal.", "FICONTER është projektuar për të organizuar informacionin financiar dhe për të nxjerrë sinjale në pah. Nuk zëvendëson këshillimin profesional financiar, të investimeve, tatimor apo ligjor.", "تم تصميم FICONTER لتنظيم المعلومات المالية وإظهار الإشارات المهمة. وهو لا يحل محل المشورة المهنية المالية أو الاستثمارية أو الضريبية أو القانونية.", "A FICONTER foi concebida para organizar informação financeira e evidenciar sinais. Não substitui aconselhamento profissional financeiro, de investimento, fiscal ou jurídico.", "FICONTER è progettata per organizzare le informazioni finanziarie e mettere in evidenza segnali. Non sostituisce consulenza professionale finanziaria, d'investimento, fiscale o legale.", "FICONTER предназначен для организации финансовой информации и выявления сигналов. Он не заменяет профессиональные финансовые, инвестиционные, налоговые или юридические консультации."),

  "Personal & business architecture": landing("Architektur für Privat & Geschäft", "Arquitectura personal y empresarial", "Arkitekturë personale dhe biznesi", "بنية الشخصي والأعمال", "Arquitetura pessoal e empresarial", "Architettura personale e business", "Архитектура личного и делового"),
  "Two financial worlds. One control center. No unnecessary mixing.": landing("Zwei Finanzwelten. Ein Kontrollzentrum. Keine unnötige Vermischung.", "Dos mundos financieros. Un centro de control. Sin mezclas innecesarias.", "Dy botë financiare. Një qendër kontrolli. Pa përzierje të panevojshme.", "عالمان ماليان. مركز تحكم واحد. بلا خلط غير ضروري.", "Dois mundos financeiros. Um centro de controlo. Sem misturas desnecessárias.", "Due mondi finanziari. Un centro di controllo. Senza mescolanze inutili.", "Два финансовых мира. Один центр управления. Без лишнего смешения."),
  "FICONTER lets you manage personal and business finances through one account while keeping the records, metrics and day-to-day decisions of each workspace distinct.": landing("Mit FICONTER kannst du private und geschäftliche Finanzen über ein Konto verwalten und gleichzeitig Datensätze, Kennzahlen und tägliche Entscheidungen jedes Arbeitsbereichs getrennt halten.", "FICONTER te permite gestionar finanzas personales y empresariales desde una cuenta manteniendo separados los registros, métricas y decisiones diarias de cada espacio.", "FICONTER të lejon të menaxhosh financat personale dhe të biznesit përmes një llogarie, ndërsa të dhënat, metrikat dhe vendimet ditore të secilës hapësirë mbeten të ndara.", "يتيح لك FICONTER إدارة الشؤون المالية الشخصية والتجارية من خلال حساب واحد مع إبقاء السجلات والمقاييس والقرارات اليومية لكل مساحة منفصلة.", "A FICONTER permite gerir finanças pessoais e empresariais através de uma conta, mantendo distintos os registos, métricas e decisões diárias de cada espaço.", "FICONTER ti consente di gestire finanze personali e aziendali con un solo account mantenendo distinti dati, metriche e decisioni quotidiane di ogni spazio.", "FICONTER позволяет управлять личными и деловыми финансами через один аккаунт, сохраняя отдельными записи, показатели и повседневные решения каждого пространства."),
  "The advantage is not combining everything into one ledger. It is making both contexts accessible without confusing one for the other.": landing("Der Vorteil besteht nicht darin, alles in einem Hauptbuch zu vermischen. Er besteht darin, beide Kontexte zugänglich zu machen, ohne sie miteinander zu verwechseln.", "La ventaja no es combinarlo todo en un único libro. Es hacer accesibles ambos contextos sin confundir uno con el otro.", "Avantazhi nuk është bashkimi i gjithçkaje në një regjistër. Është qasja në të dy kontekstet pa i ngatërruar me njëri-tjetrin.", "الميزة ليست جمع كل شيء في سجل واحد، بل إتاحة السياقين من دون الخلط بينهما.", "A vantagem não é juntar tudo num único registo. É tornar ambos os contextos acessíveis sem confundir um com o outro.", "Il vantaggio non è unire tutto in un unico registro. È rendere accessibili entrambi i contesti senza confonderli.", "Преимущество не в объединении всего в один реестр, а в доступности обоих контекстов без их смешения."),
  "One account, distinct workspaces": landing("Ein Konto, getrennte Arbeitsbereiche", "Una cuenta, espacios distintos", "Një llogari, hapësira të ndara", "حساب واحد، مساحات منفصلة", "Uma conta, espaços distintos", "Un account, spazi distinti", "Один аккаунт, отдельные пространства"),
  "Access personal and business environments through one FICONTER identity while preserving separate financial contexts.": landing("Greife über eine FICONTER-Identität auf private und geschäftliche Umgebungen zu und bewahre dabei getrennte finanzielle Kontexte.", "Accede a entornos personales y empresariales con una identidad FICONTER manteniendo contextos financieros separados.", "Qasu në mjediset personale dhe të biznesit përmes një identiteti FICONTER, duke ruajtur kontekste financiare të ndara.", "ادخل إلى البيئتين الشخصية والتجارية بهوية FICONTER واحدة مع الحفاظ على سياقات مالية منفصلة.", "Aceda a ambientes pessoais e empresariais através de uma identidade FICONTER, preservando contextos financeiros separados.", "Accedi agli ambienti personali e business con un'identità FICONTER mantenendo contesti finanziari separati.", "Получайте доступ к личной и деловой среде через одну учётную запись FICONTER, сохраняя финансовые контексты раздельными."),
  "Personal planning": landing("Private Planung", "Planificación personal", "Planifikim personal", "التخطيط الشخصي", "Planeamento pessoal", "Pianificazione personale", "Личное планирование"),
  "Use the personal workspace for household cash flow, obligations, savings, debt and goals.": landing("Nutze den privaten Arbeitsbereich für Haushalts-Cashflow, Verpflichtungen, Ersparnisse, Schulden und Ziele.", "Usa el espacio personal para flujo de caja del hogar, obligaciones, ahorros, deuda y objetivos.", "Përdor hapësirën personale për rrjedhën e parasë së familjes, detyrimet, kursimet, borxhin dhe objektivat.", "استخدم المساحة الشخصية للتدفق النقدي للأسرة والالتزامات والمدخرات والديون والأهداف.", "Use o espaço pessoal para fluxo de caixa doméstico, obrigações, poupanças, dívida e objetivos.", "Usa lo spazio personale per flusso di cassa familiare, obblighi, risparmi, debiti e obiettivi.", "Используйте личное пространство для домашнего денежного потока, обязательств, сбережений, долгов и целей."),
  "Business operations": landing("Geschäftsbetrieb", "Operaciones empresariales", "Operacione biznesi", "عمليات الأعمال", "Operações empresariais", "Operazioni aziendali", "Бизнес-операции"),
  "Use the business workspace for revenue, operating costs, inventory, suppliers and reporting.": landing("Nutze den Geschäftsarbeitsbereich für Umsatz, Betriebskosten, Inventar, Lieferanten und Berichte.", "Usa el espacio empresarial para ingresos, costes operativos, inventario, proveedores e informes.", "Përdor hapësirën e biznesit për të ardhurat, kostot operative, inventarin, furnitorët dhe raportimin.", "استخدم مساحة الأعمال للإيرادات والتكاليف التشغيلية والمخزون والموردين والتقارير.", "Use o espaço empresarial para receitas, custos operacionais, inventário, fornecedores e relatórios.", "Usa lo spazio business per ricavi, costi operativi, inventario, fornitori e reportistica.", "Используйте бизнес-пространство для выручки, операционных расходов, запасов, поставщиков и отчётности."),
  "Instant context switching": landing("Sofortiger Kontextwechsel", "Cambio instantáneo de contexto", "Ndërrim i menjëhershëm i kontekstit", "تبديل فوري للسياق", "Mudança instantânea de contexto", "Cambio istantaneo di contesto", "Мгновенное переключение контекста"),
  "Move between workspaces without signing into a separate product or rebuilding your working context.": landing("Wechsle zwischen Arbeitsbereichen, ohne dich bei einem separaten Produkt anzumelden oder deinen Arbeitskontext neu aufzubauen.", "Muévete entre espacios sin iniciar sesión en otro producto ni reconstruir tu contexto de trabajo.", "Lëviz mes hapësirave pa hyrë në një produkt tjetër ose pa rindërtuar kontekstin e punës.", "انتقل بين مساحات العمل من دون تسجيل الدخول إلى منتج منفصل أو إعادة بناء سياق عملك.", "Mude entre espaços sem iniciar sessão noutro produto nem reconstruir o seu contexto de trabalho.", "Passa tra gli spazi senza accedere a un prodotto separato o ricostruire il tuo contesto di lavoro.", "Переходите между рабочими пространствами без входа в отдельный продукт и без восстановления рабочего контекста заново."),
  "Cleaner interpretation": landing("Klarere Interpretation", "Interpretación más clara", "Interpretim më i qartë", "قراءة أوضح", "Interpretação mais clara", "Interpretazione più chiara", "Более чистая интерпретация"),
  "Personal spending does not need to distort business metrics, and business activity does not need to distort household planning.": landing("Private Ausgaben müssen Geschäftskennzahlen nicht verzerren, und geschäftliche Aktivitäten müssen die Haushaltsplanung nicht verfälschen.", "El gasto personal no tiene por qué distorsionar las métricas empresariales, ni la actividad empresarial la planificación del hogar.", "Shpenzimet personale nuk kanë pse të shtrembërojnë metrikat e biznesit dhe aktiviteti i biznesit nuk ka pse të shtrembërojë planifikimin familjar.", "لا يجب أن يشوّه الإنفاق الشخصي مؤشرات الأعمال، ولا أن يشوّه نشاط الأعمال تخطيط الأسرة.", "As despesas pessoais não têm de distorcer métricas empresariais, nem a atividade empresarial o planeamento doméstico.", "Le spese personali non devono distorcere le metriche aziendali, né l'attività business deve distorcere la pianificazione familiare.", "Личные расходы не должны искажать бизнес-показатели, а деловая активность — домашнее планирование."),
  "Room to grow": landing("Raum zum Wachsen", "Espacio para crecer", "Hapësirë për t'u rritur", "مساحة للنمو", "Espaço para crescer", "Spazio per crescere", "Пространство для роста"),
  "The structure can support someone managing only personal finances today and adding business needs when their financial life expands.": landing("Die Struktur kann jemanden unterstützen, der heute nur private Finanzen verwaltet und später geschäftliche Anforderungen ergänzt, wenn das finanzielle Leben wächst.", "La estructura puede servir a alguien que hoy solo gestiona finanzas personales y añadir necesidades empresariales cuando su vida financiera crece.", "Struktura mund të mbështesë dikë që sot menaxhon vetëm financat personale dhe më vonë shton nevojat e biznesit kur jeta financiare zgjerohet.", "يمكن للهيكل أن يدعم من يدير اليوم شؤونه المالية الشخصية فقط، ثم يضيف احتياجات الأعمال عندما تتوسع حياته المالية.", "A estrutura pode apoiar quem gere apenas finanças pessoais hoje e adicionar necessidades empresariais quando a sua vida financeira crescer.", "La struttura può supportare chi oggi gestisce solo finanze personali e aggiungere esigenze business quando la propria vita finanziaria cresce.", "Структура подходит тем, кто сегодня управляет только личными финансами, а затем добавляет бизнес-потребности по мере расширения финансовой жизни."),
  "Choose the workspace": landing("Arbeitsbereich auswählen", "Elige el espacio", "Zgjidh hapësirën", "اختر مساحة العمل", "Escolha o espaço", "Scegli lo spazio", "Выберите пространство"),
  "Start in the financial context you intend to manage.": landing("Beginne in dem finanziellen Kontext, den du verwalten möchtest.", "Empieza en el contexto financiero que quieras gestionar.", "Fillo në kontekstin financiar që synon të menaxhosh.", "ابدأ في السياق المالي الذي تنوي إدارته.", "Comece no contexto financeiro que pretende gerir.", "Inizia nel contesto finanziario che intendi gestire.", "Начните в том финансовом контексте, которым хотите управлять."),
  "Manage the right records": landing("Die richtigen Datensätze verwalten", "Gestiona los registros correctos", "Menaxho të dhënat e duhura", "أدر السجلات الصحيحة", "Gerir os registos certos", "Gestisci i dati corretti", "Управляйте нужными записями"),
  "Use the tools and metrics that belong to that personal or business context.": landing("Nutze die Werkzeuge und Kennzahlen, die zu diesem privaten oder geschäftlichen Kontext gehören.", "Usa las herramientas y métricas que correspondan a ese contexto personal o empresarial.", "Përdor mjetet dhe metrikat që i përkasin atij konteksti personal ose biznesi.", "استخدم الأدوات والمقاييس التي تنتمي إلى ذلك السياق الشخصي أو التجاري.", "Use as ferramentas e métricas que pertencem a esse contexto pessoal ou empresarial.", "Usa gli strumenti e le metriche che appartengono a quel contesto personale o business.", "Используйте инструменты и показатели, относящиеся к соответствующему личному или деловому контексту."),
  "Switch when needed": landing("Bei Bedarf wechseln", "Cambia cuando sea necesario", "Ndërro kur duhet", "بدّل عند الحاجة", "Mude quando necessário", "Cambia quando serve", "Переключайтесь при необходимости"),
  "Change workspaces deliberately while keeping each set of records organised.": landing("Wechsle Arbeitsbereiche bewusst und halte dabei jeden Datensatz organisiert.", "Cambia de espacio de forma deliberada manteniendo organizado cada conjunto de registros.", "Ndërro hapësirat me vetëdije, duke mbajtur të organizuar secilin grup të dhënash.", "غيّر مساحات العمل بشكل مقصود مع الحفاظ على تنظيم كل مجموعة من السجلات.", "Mude de espaço de forma deliberada, mantendo cada conjunto de registos organizado.", "Cambia spazio intenzionalmente mantenendo organizzato ogni insieme di dati.", "Переключайте пространства осознанно, сохраняя каждый набор записей организованным."),
  "Together where useful. Separate where necessary.": landing("Gemeinsam, wo es sinnvoll ist. Getrennt, wo es nötig ist.", "Juntos donde sea útil. Separados donde sea necesario.", "Bashkë ku është e dobishme. Të ndara ku është e nevojshme.", "معًا حيث يفيد. منفصلان حيث يلزم.", "Juntos onde é útil. Separados onde é necessário.", "Insieme dove è utile. Separati dove è necessario.", "Вместе там, где полезно. Раздельно там, где необходимо."),
  "FICONTER treats personal and business finance as connected parts of the same life, but not as interchangeable records. That distinction is what makes one-system access practical.": landing("FICONTER behandelt private und geschäftliche Finanzen als verbundene Teile desselben Lebens, aber nicht als austauschbare Datensätze. Genau diese Unterscheidung macht den Zugang über ein System praktikabel.", "FICONTER trata las finanzas personales y empresariales como partes conectadas de la misma vida, pero no como registros intercambiables. Esa distinción hace práctico el acceso desde un solo sistema.", "FICONTER i trajton financat personale dhe të biznesit si pjesë të lidhura të së njëjtës jetë, por jo si të dhëna të këmbyeshme. Kjo dallim e bën praktik aksesin në një sistem të vetëm.", "يتعامل FICONTER مع الشؤون المالية الشخصية والتجارية كأجزاء مترابطة من الحياة نفسها، ولكن ليس كسجلات قابلة للتبادل. وهذا التمييز هو ما يجعل الوصول عبر نظام واحد عمليًا.", "A FICONTER trata as finanças pessoais e empresariais como partes ligadas da mesma vida, mas não como registos intercambiáveis. Essa distinção torna prático o acesso através de um único sistema.", "FICONTER tratta finanze personali e aziendali come parti connesse della stessa vita, ma non come dati intercambiabili. Questa distinzione rende pratico l'accesso da un unico sistema.", "FICONTER рассматривает личные и деловые финансы как связанные части одной жизни, но не как взаимозаменяемые записи. Именно это различие делает единый доступ практичным."),

  "Understand how FICONTER keeps account data and financial contexts separated.": landing("Verstehe, wie FICONTER Kontodaten und finanzielle Kontexte getrennt hält.", "Descubre cómo FICONTER mantiene separados los datos de cuenta y los contextos financieros.", "Kupto si FICONTER i mban të ndara të dhënat e llogarisë dhe kontekstet financiare.", "تعرّف على كيفية إبقاء FICONTER بيانات الحساب والسياقات المالية منفصلة.", "Perceba como a FICONTER mantém separados os dados da conta e os contextos financeiros.", "Scopri come FICONTER mantiene separati i dati dell'account e i contesti finanziari.", "Узнайте, как FICONTER разделяет данные аккаунта и финансовые контексты."),
  "See how FICONTER turns multiple financial signals into one usable picture.": landing("Sieh, wie FICONTER mehrere Finanzsignale in ein nutzbares Gesamtbild verwandelt.", "Descubre cómo FICONTER convierte múltiples señales financieras en una imagen útil.", "Shiko si FICONTER i kthen disa sinjale financiare në një pamje të përdorshme.", "شاهد كيف يحول FICONTER إشارات مالية متعددة إلى صورة واحدة قابلة للاستخدام.", "Veja como a FICONTER transforma vários sinais financeiros numa visão útil.", "Scopri come FICONTER trasforma più segnali finanziari in un quadro utilizzabile.", "Посмотрите, как FICONTER превращает множество финансовых сигналов в одну полезную картину."),
  "See how one account can support personal and business workspaces without mixing the records.": landing("Sieh, wie ein Konto private und geschäftliche Arbeitsbereiche unterstützen kann, ohne Datensätze zu vermischen.", "Descubre cómo una cuenta puede admitir espacios personales y empresariales sin mezclar registros.", "Shiko si një llogari mund të mbështesë hapësira personale dhe biznesi pa përzier të dhënat.", "شاهد كيف يمكن لحساب واحد دعم مساحات شخصية وتجارية من دون خلط السجلات.", "Veja como uma conta pode suportar espaços pessoais e empresariais sem misturar os registos.", "Scopri come un account può supportare spazi personali e business senza mescolare i dati.", "Посмотрите, как один аккаунт может поддерживать личное и деловое пространства без смешения записей.")
};

Object.assign(LANDING_UI_TRANSLATIONS, LANDING_WHY_TRANSLATIONS);
