import type { FiconterLanguage } from "./config";
import { LANDING_UI_TRANSLATIONS } from "./landingUiCatalog";

type NonEnglishLanguage = Exclude<FiconterLanguage, "en">;
type TranslationRow = Record<NonEnglishLanguage, string>;

function landing(de: string, es: string, sq: string, ar: string, pt: string, it: string, ru: string): TranslationRow {
  return { de, es, sq, ar, pt, it, ru };
}

/** Exact sentence-level translations for /platform. */
export const PUBLIC_PLATFORM_TRANSLATIONS: Record<string, TranslationRow> = {
  "The FICONTER platform": landing("Die FICONTER Plattform", "La plataforma FICONTER", "Platforma FICONTER", "منصة FICONTER", "A plataforma FICONTER", "La piattaforma FICONTER", "Платформа FICONTER"),
  "One financial system. Every important decision in context.": landing("Ein Finanzsystem. Jede wichtige Entscheidung im richtigen Kontext.", "Un sistema financiero. Cada decisión importante en contexto.", "Një sistem financiar. Çdo vendim i rëndësishëm në kontekst.", "نظام مالي واحد. كل قرار مهم ضمن سياقه.", "Um sistema financeiro. Cada decisão importante no seu contexto.", "Un sistema finanziario. Ogni decisione importante nel giusto contesto.", "Одна финансовая система. Каждое важное решение — в контексте."),
  "FICONTER brings daily money movement, monthly planning, obligations, savings, debt, goals, wealth and financial intelligence into one considered control center. The aim is not to create more data—it is to make financial information easier to understand and act on.": landing(
    "FICONTER vereint tägliche Geldbewegungen, Monatsplanung, Verpflichtungen, Sparen, Schulden, Ziele, Vermögen und finanzielle Intelligenz in einem durchdachten Kontrollzentrum. Das Ziel ist nicht, mehr Daten zu erzeugen, sondern Finanzinformationen leichter verständlich und handlungsrelevant zu machen.",
    "FICONTER reúne el movimiento diario del dinero, la planificación mensual, las obligaciones, el ahorro, la deuda, los objetivos, el patrimonio y la inteligencia financiera en un centro de control pensado. El objetivo no es crear más datos, sino hacer que la información financiera sea más fácil de entender y utilizar.",
    "FICONTER bashkon lëvizjen ditore të parave, planifikimin mujor, detyrimet, kursimet, borxhet, objektivat, pasurinë dhe inteligjencën financiare në një qendër kontrolli të menduar mirë. Qëllimi nuk është të krijohen më shumë të dhëna, por që informacioni financiar të kuptohet dhe të përdoret më lehtë.",
    "تجمع FICONTER حركة المال اليومية والتخطيط الشهري والالتزامات والادخار والديون والأهداف والثروة والذكاء المالي في مركز تحكم واحد مدروس. الهدف ليس إنشاء مزيد من البيانات، بل جعل المعلومات المالية أسهل فهمًا واتخاذًا للقرار.",
    "A FICONTER reúne movimentos diários de dinheiro, planeamento mensal, obrigações, poupanças, dívida, objetivos, património e inteligência financeira num centro de controlo pensado. O objetivo não é criar mais dados, mas tornar a informação financeira mais fácil de compreender e utilizar.",
    "FICONTER riunisce movimenti quotidiani di denaro, pianificazione mensile, obblighi, risparmi, debiti, obiettivi, patrimonio e intelligenza finanziaria in un unico centro di controllo ragionato. L’obiettivo non è creare più dati, ma rendere le informazioni finanziarie più facili da capire e usare.",
    "FICONTER объединяет ежедневное движение денег, ежемесячное планирование, обязательства, сбережения, долги, цели, капитал и финансовую аналитику в одном продуманном центре управления. Цель не в том, чтобы создавать больше данных, а в том, чтобы финансовую информацию было проще понимать и применять."
  ),
  "FINANCIAL CONTROL CENTER": landing("FINANZKONTROLLZENTRUM", "CENTRO DE CONTROL FINANCIERO", "QENDRA E KONTROLLIT FINANCIAR", "مركز التحكم المالي", "CENTRO DE CONTROLO FINANCEIRO", "CENTRO DI CONTROLLO FINANZIARIO", "ЦЕНТР ФИНАНСОВОГО КОНТРОЛЯ"),
  "See what happened, what is already committed, what remains available and what deserves attention next.": landing("Sieh, was passiert ist, was bereits gebunden ist, was verfügbar bleibt und was als Nächstes Aufmerksamkeit verdient.", "Ve qué ocurrió, qué está ya comprometido, qué sigue disponible y qué merece atención a continuación.", "Shih çfarë ndodhi, çfarë është tashmë e angazhuar, çfarë mbetet e disponueshme dhe çfarë kërkon vëmendje më pas.", "اعرف ما حدث، وما تم الالتزام به بالفعل، وما المتاح المتبقي، وما الذي يستحق الانتباه بعد ذلك.", "Veja o que aconteceu, o que já está comprometido, o que permanece disponível e o que merece atenção a seguir.", "Vedi cosa è successo, cosa è già impegnato, cosa resta disponibile e cosa merita attenzione dopo.", "Смотрите, что произошло, что уже зарезервировано, что осталось доступным и что требует внимания дальше."),
  "Daily money control": landing("Tägliche Geldkontrolle", "Control diario del dinero", "Kontrolli ditor i parave", "التحكم اليومي بالمال", "Controlo diário do dinheiro", "Controllo quotidiano del denaro", "Ежедневный контроль денег"),
  "Keep transactions, balances and monthly movement visible without losing the context around each number.": landing("Behalte Transaktionen, Salden und monatliche Bewegungen im Blick, ohne den Kontext hinter jeder Zahl zu verlieren.", "Mantén visibles las transacciones, los saldos y el movimiento mensual sin perder el contexto de cada cifra.", "Mbaji transaksionet, bilancet dhe lëvizjet mujore të dukshme pa humbur kontekstin e çdo shifre.", "أبقِ المعاملات والأرصدة والحركة الشهرية واضحة دون فقدان سياق كل رقم.", "Mantenha transações, saldos e movimentos mensais visíveis sem perder o contexto de cada número.", "Mantieni visibili transazioni, saldi e movimenti mensili senza perdere il contesto di ogni numero.", "Держите транзакции, балансы и ежемесячное движение на виду, не теряя контекст каждой цифры."),
  "Plan before you spend": landing("Planen, bevor du ausgibst", "Planifica antes de gastar", "Planifiko para se të shpenzosh", "خطط قبل أن تنفق", "Planeie antes de gastar", "Pianifica prima di spendere", "Планируйте до расходов"),
  "Structure bills, commitments, reserves and goals before treating the remaining amount as truly available.": landing("Strukturiere Rechnungen, Verpflichtungen, Rücklagen und Ziele, bevor du den Restbetrag als wirklich verfügbar betrachtest.", "Estructura facturas, compromisos, reservas y objetivos antes de considerar realmente disponible el importe restante.", "Strukturo faturat, angazhimet, rezervat dhe objektivat para se ta konsiderosh shumën e mbetur si vërtet të disponueshme.", "نظّم الفواتير والالتزامات والاحتياطيات والأهداف قبل اعتبار المبلغ المتبقي متاحًا فعليًا.", "Estruture contas, compromissos, reservas e objetivos antes de considerar o valor restante verdadeiramente disponível.", "Struttura fatture, impegni, riserve e obiettivi prima di considerare davvero disponibile l’importo restante.", "Структурируйте счета, обязательства, резервы и цели, прежде чем считать остаток действительно доступным."),
  "Build long-term direction": landing("Langfristige Richtung aufbauen", "Construye una dirección a largo plazo", "Ndërto drejtimin afatgjatë", "ابنِ اتجاهًا طويل الأجل", "Construa uma direção a longo prazo", "Costruisci una direzione a lungo termine", "Создавайте долгосрочное направление"),
  "Connect savings, debt, net worth and goals so short-term decisions support a broader financial direction.": landing("Verbinde Sparen, Schulden, Nettovermögen und Ziele, damit kurzfristige Entscheidungen eine breitere finanzielle Richtung unterstützen.", "Conecta ahorro, deuda, patrimonio neto y objetivos para que las decisiones a corto plazo apoyen una dirección financiera más amplia.", "Lidh kursimet, borxhet, pasurinë neto dhe objektivat që vendimet afatshkurtra të mbështesin një drejtim financiar më të gjerë.", "اربط الادخار والديون وصافي الثروة والأهداف بحيث تدعم القرارات قصيرة الأجل اتجاهًا ماليًا أوسع.", "Ligue poupanças, dívida, património líquido e objetivos para que as decisões de curto prazo apoiem uma direção financeira mais ampla.", "Collega risparmi, debiti, patrimonio netto e obiettivi affinché le decisioni a breve termine sostengano una direzione finanziaria più ampia.", "Связывайте сбережения, долги, чистый капитал и цели, чтобы краткосрочные решения поддерживали общее финансовое направление."),
  "Understand the signals": landing("Die Signale verstehen", "Comprende las señales", "Kupto sinjalet", "افهم الإشارات", "Compreenda os sinais", "Comprendi i segnali", "Понимайте сигналы"),
  "Financial intelligence turns activity into focused indicators, priorities and areas that may deserve attention.": landing("Finanzielle Intelligenz verwandelt Aktivität in fokussierte Kennzahlen, Prioritäten und Bereiche, die Aufmerksamkeit verdienen könnten.", "La inteligencia financiera convierte la actividad en indicadores enfocados, prioridades y áreas que pueden requerir atención.", "Inteligjenca financiare e kthen aktivitetin në tregues të fokusuar, prioritete dhe fusha që mund të kërkojnë vëmendje.", "يحوّل الذكاء المالي النشاط إلى مؤشرات مركزة وأولويات ومجالات قد تستحق الانتباه.", "A inteligência financeira transforma atividade em indicadores focados, prioridades e áreas que podem merecer atenção.", "L’intelligenza finanziaria trasforma l’attività in indicatori mirati, priorità e aree che possono meritare attenzione.", "Финансовая аналитика превращает активность в понятные индикаторы, приоритеты и области, которые могут требовать внимания."),
  "The everyday financial work stays connected.": landing("Die tägliche Finanzarbeit bleibt verbunden.", "El trabajo financiero cotidiano permanece conectado.", "Puna e përditshme financiare mbetet e lidhur.", "يبقى العمل المالي اليومي مترابطًا.", "O trabalho financeiro do dia a dia mantém-se ligado.", "Il lavoro finanziario quotidiano resta collegato.", "Повседневная финансовая работа остаётся связанной."),
  "FICONTER is designed so the tools people use most often are not isolated from one another. Transactions affect cash flow. Bills affect what is available. Savings and debt affect the direction of the plan. Each module contributes to the same financial picture.": landing(
    "FICONTER ist so konzipiert, dass die am häufigsten genutzten Werkzeuge nicht voneinander isoliert sind. Transaktionen beeinflussen den Cashflow. Rechnungen beeinflussen, was verfügbar ist. Sparen und Schulden beeinflussen die Richtung des Plans. Jedes Modul trägt zum selben finanziellen Gesamtbild bei.",
    "FICONTER está diseñado para que las herramientas más utilizadas no estén aisladas entre sí. Las transacciones afectan al flujo de caja. Las facturas afectan a lo disponible. El ahorro y la deuda afectan a la dirección del plan. Cada módulo contribuye a la misma visión financiera.",
    "FICONTER është projektuar që mjetet më të përdorura të mos jenë të izoluara nga njëra-tjetra. Transaksionet ndikojnë rrjedhën e parasë. Faturat ndikojnë atë që është e disponueshme. Kursimet dhe borxhet ndikojnë drejtimin e planit. Çdo modul kontribuon në të njëjtën pamje financiare.",
    "صُممت FICONTER بحيث لا تكون الأدوات الأكثر استخدامًا معزولة عن بعضها. تؤثر المعاملات في التدفق النقدي، وتؤثر الفواتير في المتاح، ويؤثر الادخار والديون في اتجاه الخطة. يساهم كل قسم في الصورة المالية نفسها.",
    "A FICONTER foi concebida para que as ferramentas mais usadas não fiquem isoladas umas das outras. As transações afetam o fluxo de caixa. As contas afetam o que está disponível. As poupanças e a dívida afetam a direção do plano. Cada módulo contribui para a mesma visão financeira.",
    "FICONTER è progettata affinché gli strumenti più usati non siano isolati tra loro. Le transazioni influenzano il flusso di cassa. Le fatture influenzano ciò che è disponibile. Risparmi e debiti influenzano la direzione del piano. Ogni modulo contribuisce alla stessa visione finanziaria.",
    "FICONTER спроектирован так, чтобы наиболее используемые инструменты не были изолированы друг от друга. Транзакции влияют на денежный поток. Счета — на доступные средства. Сбережения и долги — на направление плана. Каждый модуль дополняет единую финансовую картину."
  ),
  "Transactions": landing("Transaktionen", "Transacciones", "Transaksionet", "المعاملات", "Transações", "Transazioni", "Транзакции"),
  "Record income and spending so daily financial movement has a reliable source of context.": landing("Erfasse Einnahmen und Ausgaben, damit tägliche Finanzbewegungen einen verlässlichen Kontext haben.", "Registra ingresos y gastos para que el movimiento financiero diario tenga un contexto fiable.", "Regjistro të ardhurat dhe shpenzimet që lëvizja ditore financiare të ketë një kontekst të besueshëm.", "سجّل الدخل والإنفاق حتى تكون للحركة المالية اليومية مرجعية موثوقة.", "Registe rendimentos e despesas para que os movimentos financeiros diários tenham um contexto fiável.", "Registra entrate e spese affinché i movimenti finanziari quotidiani abbiano un contesto affidabile.", "Записывайте доходы и расходы, чтобы ежедневное движение денег имело надёжный контекст."),
  "Bills & commitments": landing("Rechnungen & Verpflichtungen", "Facturas y compromisos", "Faturat & angazhimet", "الفواتير والالتزامات", "Contas e compromissos", "Fatture e impegni", "Счета и обязательства"),
  "Keep recurring and upcoming obligations visible before making decisions with the rest of the month.": landing("Behalte wiederkehrende und anstehende Verpflichtungen im Blick, bevor du über den Rest des Monats entscheidest.", "Mantén visibles las obligaciones recurrentes y próximas antes de tomar decisiones con el resto del mes.", "Mbaji të dukshme detyrimet periodike dhe të ardhshme para se të marrësh vendime për pjesën tjetër të muajit.", "أبقِ الالتزامات المتكررة والقادمة واضحة قبل اتخاذ قرارات بشأن بقية الشهر.", "Mantenha as obrigações recorrentes e futuras visíveis antes de tomar decisões para o resto do mês.", "Mantieni visibili gli obblighi ricorrenti e imminenti prima di prendere decisioni sul resto del mese.", "Держите регулярные и предстоящие обязательства на виду до решений по оставшейся части месяца."),
  "Savings & reserves": landing("Sparen & Rücklagen", "Ahorro y reservas", "Kursimet & rezervat", "الادخار والاحتياطيات", "Poupanças e reservas", "Risparmi e riserve", "Сбережения и резервы"),
  "Track money set aside for resilience, planned purchases and longer-term priorities.": landing("Verfolge Geld, das für Sicherheit, geplante Anschaffungen und langfristige Prioritäten zurückgelegt wurde.", "Sigue el dinero reservado para resiliencia, compras previstas y prioridades a largo plazo.", "Ndiq paratë e lëna mënjanë për siguri, blerje të planifikuara dhe prioritete afatgjata.", "تابع الأموال المخصصة للمرونة والمشتريات المخطط لها والأولويات طويلة الأجل.", "Acompanhe o dinheiro reservado para segurança, compras planeadas e prioridades de longo prazo.", "Tieni traccia del denaro accantonato per sicurezza, acquisti pianificati e priorità a lungo termine.", "Отслеживайте деньги, отложенные на финансовую устойчивость, запланированные покупки и долгосрочные приоритеты."),
  "Debt & credit": landing("Schulden & Kredit", "Deuda y crédito", "Borxhet & kredia", "الديون والائتمان", "Dívida e crédito", "Debiti e credito", "Долги и кредит"),
  "Keep repayment obligations alongside the rest of the plan instead of treating them as a separate financial world.": landing("Halte Rückzahlungsverpflichtungen zusammen mit dem restlichen Plan, statt sie als eigene Finanzwelt zu behandeln.", "Mantén las obligaciones de pago junto al resto del plan en vez de tratarlas como un mundo financiero separado.", "Mbaji detyrimet e shlyerjes pranë pjesës tjetër të planit, në vend që t'i trajtosh si një botë financiare më vete.", "أبقِ التزامات السداد ضمن بقية الخطة بدل التعامل معها كعالم مالي منفصل.", "Mantenha as obrigações de reembolso junto do resto do plano, em vez de as tratar como um mundo financeiro separado.", "Mantieni gli obblighi di rimborso insieme al resto del piano invece di trattarli come un mondo finanziario separato.", "Учитывайте обязательства по погашению вместе с остальным планом, а не как отдельный финансовый мир."),
  "Goals": landing("Ziele", "Objetivos", "Objektivat", "الأهداف", "Objetivos", "Obiettivi", "Цели"),
  "Give savings and financial decisions a defined destination with visible progress over time.": landing("Gib Sparen und Finanzentscheidungen ein klares Ziel mit sichtbarem Fortschritt im Zeitverlauf.", "Da al ahorro y a las decisiones financieras un destino definido con progreso visible en el tiempo.", "Jepu kursimeve dhe vendimeve financiare një destinacion të qartë me progres të dukshëm me kalimin e kohës.", "امنح الادخار والقرارات المالية وجهة محددة مع تقدم واضح بمرور الوقت.", "Dê às poupanças e às decisões financeiras um destino definido com progresso visível ao longo do tempo.", "Dai a risparmi e decisioni finanziarie una destinazione definita con progressi visibili nel tempo.", "Задавайте сбережениям и финансовым решениям конкретную цель с видимым прогрессом во времени."),
  "Available after planning": landing("Nach der Planung verfügbar", "Disponible después de planificar", "Në dispozicion pas planifikimit", "متاح بعد التخطيط", "Disponível após o planeamento", "Disponibile dopo la pianificazione", "Доступно после планирования"),
  "Understand what remains after obligations and planned allocations are accounted for, not merely what sits in an account.": landing("Verstehe, was nach Verpflichtungen und geplanten Zuweisungen übrig bleibt – nicht nur, was auf einem Konto liegt.", "Comprende lo que queda después de contabilizar obligaciones y asignaciones planificadas, no solo lo que hay en una cuenta.", "Kupto çfarë mbetet pasi llogariten detyrimet dhe ndarjet e planifikuara, jo thjesht çfarë ndodhet në një llogari.", "اعرف ما يتبقى بعد احتساب الالتزامات والتخصيصات المخطط لها، لا مجرد ما يظهر في الحساب.", "Compreenda o que resta depois de contabilizar obrigações e alocações planeadas, e não apenas o que está numa conta.", "Comprendi cosa resta dopo aver considerato obblighi e allocazioni pianificate, non soltanto ciò che è presente su un conto.", "Понимайте, что остаётся после учёта обязательств и запланированных распределений, а не только сумму на счёте."),
  "Numbers become useful when they explain what is happening.": landing("Zahlen werden nützlich, wenn sie erklären, was passiert.", "Los números son útiles cuando explican lo que está ocurriendo.", "Shifrat bëhen të dobishme kur shpjegojnë çfarë po ndodh.", "تصبح الأرقام مفيدة عندما تشرح ما يحدث.", "Os números tornam-se úteis quando explicam o que está a acontecer.", "I numeri diventano utili quando spiegano ciò che sta accadendo.", "Цифры становятся полезными, когда объясняют происходящее."),
  "FICONTER's intelligence layer is designed to summarise the condition of the financial plan without creating unnecessary noise. It combines structured financial signals so a user can understand where things are stable, where progress is happening and what may require attention.": landing(
    "FICONTERs Intelligenzebene fasst den Zustand des Finanzplans zusammen, ohne unnötiges Rauschen zu erzeugen. Sie verbindet strukturierte finanzielle Signale, damit Nutzer erkennen können, was stabil ist, wo Fortschritt entsteht und was Aufmerksamkeit erfordern könnte.",
    "La capa de inteligencia de FICONTER está diseñada para resumir el estado del plan financiero sin generar ruido innecesario. Combina señales financieras estructuradas para que el usuario entienda qué está estable, dónde hay progreso y qué puede requerir atención.",
    "Shtresa e inteligjencës së FICONTER është projektuar për të përmbledhur gjendjen e planit financiar pa krijuar zhurmë të panevojshme. Ajo kombinon sinjale financiare të strukturuara që përdoruesi të kuptojë ku ka stabilitet, ku po ndodh progres dhe çfarë mund të kërkojë vëmendje.",
    "صُممت طبقة الذكاء في FICONTER لتلخيص حالة الخطة المالية دون خلق ضوضاء غير ضرورية. فهي تجمع إشارات مالية منظمة ليعرف المستخدم أين يوجد الاستقرار، وأين يحدث التقدم، وما الذي قد يحتاج إلى الانتباه.",
    "A camada de inteligência da FICONTER foi concebida para resumir o estado do plano financeiro sem criar ruído desnecessário. Combina sinais financeiros estruturados para que o utilizador perceba onde existe estabilidade, onde há progresso e o que pode exigir atenção.",
    "Il livello di intelligenza di FICONTER è progettato per riassumere lo stato del piano finanziario senza creare rumore inutile. Combina segnali finanziari strutturati affinché l’utente capisca cosa è stabile, dove c’è progresso e cosa può richiedere attenzione.",
    "Интеллектуальный слой FICONTER предназначен для краткого понимания состояния финансового плана без лишнего шума. Он объединяет структурированные финансовые сигналы, чтобы пользователь видел, где всё стабильно, где есть прогресс и что может требовать внимания."
  ),
  "Financial Health": landing("Finanzielle Gesundheit", "Salud financiera", "Shëndeti financiar", "الصحة المالية", "Saúde Financeira", "Salute finanziaria", "Финансовое здоровье"),
  "A structured indicator that reflects multiple parts of the user's financial position rather than a single balance.": landing("Ein strukturierter Indikator, der mehrere Teile der finanziellen Lage des Nutzers abbildet statt nur einen einzelnen Saldo.", "Un indicador estructurado que refleja varias partes de la posición financiera del usuario en lugar de un único saldo.", "Një tregues i strukturuar që pasqyron disa pjesë të pozicionit financiar të përdoruesit, jo vetëm një bilanc të vetëm.", "مؤشر منظم يعكس عدة جوانب من الوضع المالي للمستخدم بدلًا من رصيد واحد فقط.", "Um indicador estruturado que reflete várias partes da posição financeira do utilizador, em vez de um único saldo.", "Un indicatore strutturato che riflette più aspetti della posizione finanziaria dell’utente invece di un singolo saldo.", "Структурированный показатель, отражающий несколько аспектов финансового положения пользователя, а не один баланс."),
  "Cash Flow Intelligence": landing("Cashflow-Intelligenz", "Inteligencia de flujo de caja", "Inteligjenca e rrjedhës së parasë", "ذكاء التدفق النقدي", "Inteligência de Fluxo de Caixa", "Intelligenza del flusso di cassa", "Аналитика денежного потока"),
  "Shows how incoming and outgoing money interact across the month and whether the current pattern is sustainable.": landing("Zeigt, wie eingehendes und ausgehendes Geld über den Monat zusammenspielen und ob das aktuelle Muster tragfähig ist.", "Muestra cómo interactúan el dinero entrante y saliente durante el mes y si el patrón actual es sostenible.", "Tregon si ndërveprojnë paratë hyrëse dhe dalëse gjatë muajit dhe nëse modeli aktual është i qëndrueshëm.", "يوضح كيف تتفاعل الأموال الداخلة والخارجة خلال الشهر وما إذا كان النمط الحالي مستدامًا.", "Mostra como o dinheiro que entra e sai interage ao longo do mês e se o padrão atual é sustentável.", "Mostra come denaro in entrata e in uscita interagiscono durante il mese e se il modello attuale è sostenibile.", "Показывает, как входящие и исходящие деньги взаимодействуют в течение месяца и устойчив ли текущий сценарий."),
  "Emergency Fund": landing("Notfallreserve", "Fondo de emergencia", "Fondi i emergjencës", "صندوق الطوارئ", "Fundo de Emergência", "Fondo di emergenza", "Резервный фонд"),
  "Measures reserve progress against the user's financial commitments and selected planning assumptions.": landing("Misst den Fortschritt der Rücklagen im Verhältnis zu den finanziellen Verpflichtungen des Nutzers und den gewählten Planungsannahmen.", "Mide el progreso de las reservas frente a los compromisos financieros del usuario y las hipótesis de planificación seleccionadas.", "Mat progresin e rezervave kundrejt angazhimeve financiare të përdoruesit dhe supozimeve të zgjedhura të planifikimit.", "يقيس تقدم الاحتياطي مقارنة بالتزامات المستخدم المالية وافتراضات التخطيط المختارة.", "Mede o progresso das reservas face aos compromissos financeiros do utilizador e aos pressupostos de planeamento selecionados.", "Misura il progresso delle riserve rispetto agli impegni finanziari dell’utente e alle ipotesi di pianificazione selezionate.", "Измеряет прогресс резервов относительно финансовых обязательств пользователя и выбранных предположений планирования."),
  "Wealth direction": landing("Vermögensrichtung", "Dirección patrimonial", "Drejtimi i pasurisë", "اتجاه الثروة", "Direção patrimonial", "Direzione patrimoniale", "Направление капитала"),
  "Connects net worth, savings and long-term progress so users can see movement beyond the current month.": landing("Verbindet Nettovermögen, Sparen und langfristigen Fortschritt, damit Nutzer Entwicklungen über den aktuellen Monat hinaus sehen können.", "Conecta patrimonio neto, ahorro y progreso a largo plazo para que los usuarios vean movimiento más allá del mes actual.", "Lidh pasurinë neto, kursimet dhe progresin afatgjatë që përdoruesit të shohin lëvizjen përtej muajit aktual.", "يربط صافي الثروة والادخار والتقدم طويل الأجل ليتمكن المستخدم من رؤية الحركة بعد الشهر الحالي.", "Liga património líquido, poupanças e progresso de longo prazo para que os utilizadores vejam evolução para além do mês atual.", "Collega patrimonio netto, risparmi e progresso a lungo termine affinché gli utenti vedano l’evoluzione oltre il mese corrente.", "Связывает чистый капитал, сбережения и долгосрочный прогресс, чтобы видеть движение дальше текущего месяца."),
  "How the platform works": landing("So funktioniert die Plattform", "Cómo funciona la plataforma", "Si funksionon platforma", "كيف تعمل المنصة", "Como funciona a plataforma", "Come funziona la piattaforma", "Как работает платформа"),
  "From financial activity to a clearer next decision.": landing("Von finanzieller Aktivität zur klareren nächsten Entscheidung.", "De la actividad financiera a una próxima decisión más clara.", "Nga aktiviteti financiar te vendimi i ardhshëm më i qartë.", "من النشاط المالي إلى قرار تالٍ أكثر وضوحًا.", "Da atividade financeira a uma próxima decisão mais clara.", "Dall’attività finanziaria a una prossima decisione più chiara.", "От финансовой активности к более ясному следующему решению."),
  "FICONTER keeps the path understandable so users know where information comes from and why a number matters.": landing("FICONTER hält den Weg nachvollziehbar, damit Nutzer wissen, woher Informationen kommen und warum eine Zahl wichtig ist.", "FICONTER mantiene el proceso comprensible para que los usuarios sepan de dónde viene la información y por qué importa una cifra.", "FICONTER e mban rrugën të kuptueshme që përdoruesit të dinë nga vjen informacioni dhe pse ka rëndësi një shifër.", "تحافظ FICONTER على وضوح المسار ليعرف المستخدم من أين تأتي المعلومات ولماذا يهم الرقم.", "A FICONTER mantém o percurso compreensível para que os utilizadores saibam de onde vem a informação e porque importa um número.", "FICONTER mantiene il percorso comprensibile affinché gli utenti sappiano da dove arrivano le informazioni e perché un numero conta.", "FICONTER делает путь понятным, чтобы пользователь знал, откуда берётся информация и почему важна конкретная цифра."),
  "Record": landing("Erfassen", "Registrar", "Regjistro", "سجّل", "Registar", "Registra", "Записать"),
  "Add the financial activity, balances and obligations that matter to the plan.": landing("Füge die finanziellen Aktivitäten, Salden und Verpflichtungen hinzu, die für den Plan wichtig sind.", "Añade la actividad financiera, los saldos y las obligaciones relevantes para el plan.", "Shto aktivitetin financiar, bilancet dhe detyrimet që kanë rëndësi për planin.", "أضف النشاط المالي والأرصدة والالتزامات المهمة للخطة.", "Adicione a atividade financeira, os saldos e as obrigações relevantes para o plano.", "Aggiungi attività finanziarie, saldi e obblighi rilevanti per il piano.", "Добавьте финансовую активность, балансы и обязательства, важные для плана."),
  "Structure": landing("Strukturieren", "Estructurar", "Strukturo", "نظّم", "Estruturar", "Struttura", "Структурировать"),
  "FICONTER organises that information into the right financial modules and workspaces.": landing("FICONTER ordnet diese Informationen den passenden Finanzmodulen und Arbeitsbereichen zu.", "FICONTER organiza esa información en los módulos financieros y espacios adecuados.", "FICONTER e organizon atë informacion në modulet dhe hapësirat e duhura financiare.", "تنظّم FICONTER هذه المعلومات ضمن الوحدات ومساحات العمل المالية المناسبة.", "A FICONTER organiza essa informação nos módulos financeiros e espaços adequados.", "FICONTER organizza queste informazioni nei moduli finanziari e negli spazi corretti.", "FICONTER распределяет эту информацию по нужным финансовым модулям и рабочим пространствам."),
  "Understand": landing("Verstehen", "Comprender", "Kupto", "افهم", "Compreender", "Comprendi", "Понять"),
  "Dashboards and indicators turn separate figures into a usable financial picture.": landing("Dashboards und Indikatoren verwandeln einzelne Zahlen in ein nutzbares Finanzbild.", "Los paneles e indicadores convierten cifras separadas en una visión financiera útil.", "Panelet dhe treguesit i kthejnë shifrat e veçanta në një pamje financiare të përdorshme.", "تحوّل لوحات المعلومات والمؤشرات الأرقام المنفصلة إلى صورة مالية قابلة للاستخدام.", "Painéis e indicadores transformam números separados numa visão financeira útil.", "Dashboard e indicatori trasformano cifre separate in un quadro finanziario utilizzabile.", "Панели и индикаторы превращают отдельные цифры в полезную финансовую картину."),
  "Decide": landing("Entscheiden", "Decidir", "Vendos", "قرّر", "Decidir", "Decidi", "Решить"),
  "Use that picture to plan spending, build reserves, reduce obligations or pursue goals with better context.": landing("Nutze dieses Bild, um Ausgaben zu planen, Rücklagen aufzubauen, Verpflichtungen zu reduzieren oder Ziele mit besserem Kontext zu verfolgen.", "Usa esa visión para planificar gastos, crear reservas, reducir obligaciones o perseguir objetivos con mejor contexto.", "Përdor atë pamje për të planifikuar shpenzimet, ndërtuar rezerva, ulur detyrimet ose ndjekur objektivat me kontekst më të mirë.", "استخدم هذه الصورة لتخطيط الإنفاق وبناء الاحتياطيات وتقليل الالتزامات أو متابعة الأهداف ضمن سياق أفضل.", "Use essa visão para planear despesas, criar reservas, reduzir obrigações ou perseguir objetivos com melhor contexto.", "Usa questo quadro per pianificare le spese, costruire riserve, ridurre gli obblighi o perseguire obiettivi con un contesto migliore.", "Используйте эту картину, чтобы планировать расходы, создавать резервы, сокращать обязательства или двигаться к целям с лучшим пониманием контекста."),
  "The design principle": landing("Das Designprinzip", "El principio de diseño", "Parimi i dizajnit", "مبدأ التصميم", "O princípio de design", "Il principio di design", "Принцип дизайна"),
  "Control should feel calmer than the financial life it is organising.": landing("Kontrolle sollte sich ruhiger anfühlen als das Finanzleben, das sie organisiert.", "El control debe sentirse más tranquilo que la vida financiera que organiza.", "Kontrolli duhet të ndihet më i qetë se jeta financiare që organizon.", "يجب أن يكون التحكم أكثر هدوءًا من الحياة المالية التي ينظمها.", "O controlo deve parecer mais calmo do que a vida financeira que organiza.", "Il controllo dovrebbe sembrare più calmo della vita finanziaria che organizza.", "Контроль должен ощущаться спокойнее, чем финансовая жизнь, которую он организует."),
  "FICONTER is built around a clear hierarchy of information: the current position first, the commitments around it, the direction ahead and the signals that deserve attention. The platform is not intended to overwhelm users with dashboards for the sake of dashboards.": landing(
    "FICONTER basiert auf einer klaren Informationshierarchie: zuerst die aktuelle Lage, dann die Verpflichtungen darum herum, die weitere Richtung und die Signale, die Aufmerksamkeit verdienen. Die Plattform soll Nutzer nicht mit Dashboards um der Dashboards willen überfordern.",
    "FICONTER se construye sobre una jerarquía clara de información: primero la posición actual, después los compromisos que la rodean, la dirección futura y las señales que merecen atención. La plataforma no pretende abrumar a los usuarios con paneles por el simple hecho de tener paneles.",
    "FICONTER ndërtohet mbi një hierarki të qartë informacioni: fillimisht pozicioni aktual, pastaj angazhimet rreth tij, drejtimi përpara dhe sinjalet që kërkojnë vëmendje. Platforma nuk synon t'i mbingarkojë përdoruesit me panele vetëm për hir të paneleve.",
    "بُنيت FICONTER حول تسلسل واضح للمعلومات: الوضع الحالي أولًا، ثم الالتزامات المحيطة به، والاتجاه القادم، والإشارات التي تستحق الانتباه. لا تهدف المنصة إلى إغراق المستخدم بلوحات معلومات لمجرد وجود لوحات معلومات.",
    "A FICONTER é construída em torno de uma hierarquia clara de informação: primeiro a posição atual, depois os compromissos à sua volta, a direção futura e os sinais que merecem atenção. A plataforma não pretende sobrecarregar os utilizadores com painéis apenas por ter painéis.",
    "FICONTER è costruita attorno a una chiara gerarchia delle informazioni: prima la posizione attuale, poi gli impegni che la circondano, la direzione futura e i segnali che meritano attenzione. La piattaforma non vuole sommergere gli utenti di dashboard fini a sé stesse.",
    "FICONTER построен вокруг ясной иерархии информации: сначала текущее положение, затем обязательства вокруг него, направление вперёд и сигналы, требующие внимания. Платформа не должна перегружать пользователя панелями ради самих панелей."
  ),
};

Object.assign(LANDING_UI_TRANSLATIONS, PUBLIC_PLATFORM_TRANSLATIONS);
