import type { FiconterLanguage } from "./config";
import { LANDING_UI_TRANSLATIONS } from "./landingUiCatalog";

type NonEnglishLanguage = Exclude<FiconterLanguage, "en">;
type TranslationRow = Record<NonEnglishLanguage, string>;

function landing(de: string, es: string, sq: string, ar: string, pt: string, it: string, ru: string): TranslationRow {
  return { de, es, sq, ar, pt, it, ru };
}

/** Exact sentence-level translations for /personal-business. */
export const PUBLIC_PERSONAL_BUSINESS_TRANSLATIONS: Record<string, TranslationRow> = {
  "Personal & business architecture": landing("Architektur für Privat & Geschäft", "Arquitectura personal y empresarial", "Arkitekturë personale dhe biznesi", "بنية الشخصي والأعمال", "Arquitetura pessoal e empresarial", "Architettura personale e business", "Архитектура личного и делового"),
  "Two financial worlds. One control center.": landing("Zwei Finanzwelten. Ein Kontrollzentrum.", "Dos mundos financieros. Un centro de control.", "Dy botë financiare. Një qendër kontrolli.", "عالمان ماليان. مركز تحكم واحد.", "Dois mundos financeiros. Um centro de controlo.", "Due mondi finanziari. Un centro di controllo.", "Два финансовых мира. Один центр управления."),
  "Personal finances and business finances influence the same life, but they should not be mixed into the same operating context. FICONTER gives each one its own workspace while keeping both accessible through a single account.": landing(
    "Private und geschäftliche Finanzen beeinflussen dasselbe Leben, sollten aber nicht im selben operativen Kontext vermischt werden. FICONTER gibt beiden einen eigenen Arbeitsbereich und hält sie dennoch über ein einziges Konto erreichbar.",
    "Las finanzas personales y empresariales influyen en la misma vida, pero no deberían mezclarse en el mismo contexto operativo. FICONTER ofrece a cada una su propio espacio manteniendo ambas accesibles desde una sola cuenta.",
    "Financat personale dhe të biznesit ndikojnë të njëjtën jetë, por nuk duhet të përzihen në të njëjtin kontekst operativ. FICONTER i jep secilës hapësirën e vet, duke i mbajtur të dyja të aksesueshme nga një llogari e vetme.",
    "تؤثر الشؤون المالية الشخصية والتجارية في الحياة نفسها، لكن لا ينبغي خلطها في السياق التشغيلي نفسه. تمنح FICONTER كل واحدة مساحة عمل مستقلة مع إبقائهما متاحتين من خلال حساب واحد.",
    "As finanças pessoais e empresariais influenciam a mesma vida, mas não devem ser misturadas no mesmo contexto operacional. A FICONTER dá a cada uma o seu próprio espaço, mantendo ambas acessíveis através de uma única conta.",
    "Le finanze personali e aziendali influenzano la stessa vita, ma non dovrebbero essere mescolate nello stesso contesto operativo. FICONTER assegna a ciascuna il proprio spazio mantenendole entrambe accessibili da un unico account.",
    "Личные и деловые финансы влияют на одну и ту же жизнь, но не должны смешиваться в одном операционном контексте. FICONTER даёт каждому отдельное рабочее пространство, сохраняя доступ к обоим через один аккаунт."
  ),
  "ONE ACCOUNT · DISTINCT WORKSPACES": landing("EIN KONTO · GETRENNTE ARBEITSBEREICHE", "UNA CUENTA · ESPACIOS SEPARADOS", "NJË LLOGARI · HAPËSIRA TË NDARA", "حساب واحد · مساحات عمل منفصلة", "UMA CONTA · ESPAÇOS DISTINTOS", "UN ACCOUNT · SPAZI DISTINTI", "ОДИН АККАУНТ · ОТДЕЛЬНЫЕ ПРОСТРАНСТВА"),
  "Move between household planning and business operations without rebuilding context or confusing the records that matter.": landing("Wechsle zwischen Haushaltsplanung und Geschäftsbetrieb, ohne den Kontext neu aufzubauen oder wichtige Datensätze zu vermischen.", "Pasa de la planificación del hogar a las operaciones empresariales sin reconstruir el contexto ni confundir los registros importantes.", "Kalo mes planifikimit familjar dhe operacioneve të biznesit pa rindërtuar kontekstin ose ngatërruar të dhënat e rëndësishme.", "تنقّل بين تخطيط الأسرة وعمليات الأعمال دون إعادة بناء السياق أو خلط السجلات المهمة.", "Passe do planeamento familiar para as operações empresariais sem reconstruir o contexto nem confundir os registos importantes.", "Passa dalla pianificazione familiare alle operazioni aziendali senza ricostruire il contesto né confondere i dati importanti.", "Переходите между планированием домохозяйства и бизнес-операциями без повторного построения контекста и путаницы в важных записях."),
  "Use a dedicated environment for household cash flow, bills, savings, debt, goals and personal financial health.": landing("Nutze eine eigene Umgebung für Haushalts-Cashflow, Rechnungen, Sparen, Schulden, Ziele und persönliche finanzielle Gesundheit.", "Usa un entorno dedicado para el flujo de caja del hogar, facturas, ahorro, deuda, objetivos y salud financiera personal.", "Përdor një mjedis të dedikuar për rrjedhën e parasë së familjes, faturat, kursimet, borxhet, objektivat dhe shëndetin financiar personal.", "استخدم بيئة مخصصة للتدفق النقدي للأسرة والفواتير والادخار والديون والأهداف والصحة المالية الشخصية.", "Use um ambiente dedicado para fluxo de caixa familiar, contas, poupanças, dívida, objetivos e saúde financeira pessoal.", "Usa un ambiente dedicato per flusso di cassa familiare, fatture, risparmi, debiti, obiettivi e salute finanziaria personale.", "Используйте отдельную среду для денежного потока домохозяйства, счетов, сбережений, долгов, целей и личного финансового здоровья."),
  "Keep revenue, operating costs, inventory, suppliers and business reporting in their own financial context.": landing("Halte Umsatz, Betriebskosten, Bestand, Lieferanten und Geschäftsberichte in ihrem eigenen Finanzkontext.", "Mantén ingresos, costes operativos, inventario, proveedores e informes empresariales en su propio contexto financiero.", "Mbaji të ardhurat, kostot operative, inventarin, furnitorët dhe raportimin e biznesit në kontekstin e tyre financiar.", "أبقِ الإيرادات وتكاليف التشغيل والمخزون والموردين وتقارير الأعمال ضمن سياقها المالي الخاص.", "Mantenha receitas, custos operacionais, inventário, fornecedores e relatórios empresariais no seu próprio contexto financeiro.", "Mantieni ricavi, costi operativi, inventario, fornitori e report aziendali nel loro contesto finanziario.", "Держите выручку, операционные расходы, запасы, поставщиков и бизнес-отчётность в собственном финансовом контексте."),
  "Instant context switching": landing("Sofortiger Kontextwechsel", "Cambio de contexto instantáneo", "Ndërrim i menjëhershëm i kontekstit", "تبديل فوري للسياق", "Mudança instantânea de contexto", "Cambio di contesto immediato", "Мгновенное переключение контекста"),
  "Move between workspaces without logging into a separate product or rebuilding your working environment.": landing("Wechsle zwischen Arbeitsbereichen, ohne dich bei einem separaten Produkt anzumelden oder deine Arbeitsumgebung neu aufzubauen.", "Muévete entre espacios sin iniciar sesión en otro producto ni reconstruir tu entorno de trabajo.", "Kalo mes hapësirave pa hyrë në një produkt tjetër ose rindërtuar mjedisin e punës.", "تنقّل بين مساحات العمل دون تسجيل الدخول إلى منتج منفصل أو إعادة بناء بيئة العمل.", "Mude entre espaços sem iniciar sessão noutro produto nem reconstruir o ambiente de trabalho.", "Passa da uno spazio all’altro senza accedere a un prodotto separato né ricostruire l’ambiente di lavoro.", "Переключайтесь между рабочими пространствами без входа в отдельный продукт и без повторной настройки среды."),
  "No unnecessary mixing": landing("Keine unnötige Vermischung", "Sin mezclas innecesarias", "Pa përzierje të panevojshme", "دون خلط غير ضروري", "Sem misturas desnecessárias", "Nessuna mescolanza inutile", "Без лишнего смешения"),
  "Personal activity does not need to distort business metrics, and business activity does not need to distort household planning.": landing("Private Aktivität muss Geschäftskennzahlen nicht verzerren, und geschäftliche Aktivität muss die Haushaltsplanung nicht verzerren.", "La actividad personal no tiene por qué distorsionar las métricas empresariales, ni la actividad empresarial la planificación del hogar.", "Aktiviteti personal nuk duhet të shtrembërojë metrikat e biznesit dhe aktiviteti i biznesit nuk duhet të shtrembërojë planifikimin familjar.", "لا ينبغي للنشاط الشخصي أن يشوّه مؤشرات الأعمال، ولا لنشاط الأعمال أن يشوّه تخطيط الأسرة.", "A atividade pessoal não precisa de distorcer as métricas empresariais, nem a atividade empresarial o planeamento familiar.", "L’attività personale non deve distorcere le metriche aziendali, né quella aziendale la pianificazione familiare.", "Личная активность не должна искажать бизнес-метрики, а бизнес-активность — планирование домохозяйства."),
  "A financial system for the life outside the business.": landing("Ein Finanzsystem für das Leben außerhalb des Geschäfts.", "Un sistema financiero para la vida fuera del negocio.", "Një sistem financiar për jetën jashtë biznesit.", "نظام مالي للحياة خارج العمل.", "Um sistema financeiro para a vida fora do negócio.", "Un sistema finanziario per la vita fuori dal business.", "Финансовая система для жизни вне бизнеса."),
  "The personal workspace is designed around the decisions individuals and households make every month: what comes in, what is already committed, what can be saved, what must be repaid and what goals are moving forward.": landing(
    "Der private Arbeitsbereich ist auf die Entscheidungen ausgerichtet, die Einzelpersonen und Haushalte jeden Monat treffen: was hereinkommt, was bereits gebunden ist, was gespart werden kann, was zurückgezahlt werden muss und welche Ziele vorankommen.",
    "El espacio personal está diseñado alrededor de las decisiones que personas y hogares toman cada mes: qué entra, qué está ya comprometido, qué puede ahorrarse, qué debe devolverse y qué objetivos avanzan.",
    "Hapësira personale është projektuar rreth vendimeve që individët dhe familjet marrin çdo muaj: çfarë hyn, çfarë është tashmë e angazhuar, çfarë mund të kursehet, çfarë duhet të shlyhet dhe cilat objektiva po ecin përpara.",
    "صُممت مساحة العمل الشخصية حول القرارات التي يتخذها الأفراد والأسر كل شهر: ما الذي يدخل، وما تم الالتزام به، وما يمكن ادخاره، وما يجب سداده، وما الأهداف التي تتقدم.",
    "O espaço pessoal foi concebido em torno das decisões que pessoas e famílias tomam todos os meses: o que entra, o que já está comprometido, o que pode ser poupado, o que deve ser reembolsado e que objetivos estão a avançar.",
    "Lo spazio personale è progettato attorno alle decisioni che individui e famiglie prendono ogni mese: cosa entra, cosa è già impegnato, cosa può essere risparmiato, cosa va rimborsato e quali obiettivi stanno avanzando.",
    "Личное пространство построено вокруг решений, которые люди и семьи принимают каждый месяц: что поступает, что уже зарезервировано, что можно сберечь, что нужно погасить и какие цели продвигаются."
  ),
  "Household cash flow": landing("Haushalts-Cashflow", "Flujo de caja del hogar", "Rrjedha e parasë së familjes", "التدفق النقدي للأسرة", "Fluxo de caixa familiar", "Flusso di cassa familiare", "Денежный поток домохозяйства"),
  "Keep income and spending visible across the month so everyday decisions have context.": landing("Behalte Einnahmen und Ausgaben über den Monat hinweg sichtbar, damit Alltagsentscheidungen Kontext haben.", "Mantén ingresos y gastos visibles durante el mes para que las decisiones cotidianas tengan contexto.", "Mbaji të ardhurat dhe shpenzimet të dukshme gjatë muajit që vendimet e përditshme të kenë kontekst.", "أبقِ الدخل والإنفاق واضحين طوال الشهر حتى تكون للقرارات اليومية خلفية مفهومة.", "Mantenha rendimentos e despesas visíveis ao longo do mês para que as decisões diárias tenham contexto.", "Mantieni entrate e spese visibili durante il mese affinché le decisioni quotidiane abbiano contesto.", "Держите доходы и расходы видимыми в течение месяца, чтобы повседневные решения имели контекст."),
  "Goals & reserves": landing("Ziele & Rücklagen", "Objetivos y reservas", "Objektivat & rezervat", "الأهداف والاحتياطيات", "Objetivos e reservas", "Obiettivi e riserve", "Цели и резервы"),
  "Structure savings around clear purposes, emergency resilience and long-term priorities.": landing("Strukturiere Sparen rund um klare Zwecke, Notfallreserven und langfristige Prioritäten.", "Estructura el ahorro en torno a propósitos claros, resiliencia ante emergencias y prioridades a largo plazo.", "Strukturo kursimet rreth qëllimeve të qarta, sigurisë për emergjenca dhe prioriteteve afatgjata.", "نظّم الادخار حول أهداف واضحة ومرونة للطوارئ وأولويات طويلة الأجل.", "Estruture as poupanças em torno de objetivos claros, segurança para emergências e prioridades de longo prazo.", "Struttura i risparmi attorno a scopi chiari, resilienza per le emergenze e priorità a lungo termine.", "Структурируйте сбережения вокруг понятных целей, устойчивости к чрезвычайным ситуациям и долгосрочных приоритетов."),
  "Personal financial health": landing("Persönliche finanzielle Gesundheit", "Salud financiera personal", "Shëndeti financiar personal", "الصحة المالية الشخصية", "Saúde financeira pessoal", "Salute finanziaria personale", "Личное финансовое здоровье"),
  "View the broader condition of the personal plan rather than relying on a single account balance.": landing("Betrachte den Gesamtzustand des persönlichen Plans, statt dich auf einen einzelnen Kontostand zu verlassen.", "Observa el estado general del plan personal en lugar de depender de un único saldo de cuenta.", "Shih gjendjen më të gjerë të planit personal në vend që të mbështetesh vetëm te një bilanc llogarie.", "انظر إلى الحالة الأوسع للخطة الشخصية بدل الاعتماد على رصيد حساب واحد.", "Veja o estado geral do plano pessoal em vez de depender de um único saldo de conta.", "Osserva la condizione complessiva del piano personale invece di affidarti a un singolo saldo.", "Смотрите на общее состояние личного плана, а не полагайтесь на один баланс счёта."),
  "Private context": landing("Privater Kontext", "Contexto privado", "Kontekst privat", "سياق خاص", "Contexto privado", "Contesto privato", "Приватный контекст"),
  "Personal records remain part of the authenticated personal workspace rather than being merged into business operating data.": landing("Persönliche Datensätze bleiben Teil des authentifizierten privaten Arbeitsbereichs, statt mit operativen Geschäftsdaten zusammengeführt zu werden.", "Los registros personales permanecen en el espacio personal autenticado en lugar de fusionarse con datos operativos empresariales.", "Të dhënat personale mbeten pjesë e hapësirës personale të autentikuar, në vend që të bashkohen me të dhënat operative të biznesit.", "تبقى السجلات الشخصية ضمن مساحة العمل الشخصية الموثقة بدل دمجها مع بيانات تشغيل الأعمال.", "Os registos pessoais permanecem no espaço pessoal autenticado em vez de serem misturados com dados operacionais empresariais.", "I dati personali restano nello spazio personale autenticato invece di essere fusi con i dati operativi aziendali.", "Личные записи остаются в аутентифицированном личном пространстве и не объединяются с операционными данными бизнеса."),
  "Operational finance without losing the bigger picture.": landing("Operative Finanzen, ohne das Gesamtbild zu verlieren.", "Finanzas operativas sin perder la visión global.", "Financa operative pa humbur pamjen e përgjithshme.", "تمويل تشغيلي دون فقدان الصورة الأكبر.", "Finanças operacionais sem perder a visão global.", "Finanza operativa senza perdere il quadro generale.", "Операционные финансы без потери общей картины."),
  "The business workspace is designed for the financial activity that belongs to running an operation. Revenue, costs, inventory and supplier relationships can be understood on their own terms without being mixed into personal planning.": landing(
    "Der geschäftliche Arbeitsbereich ist für die finanziellen Aktivitäten konzipiert, die zum Betrieb eines Unternehmens gehören. Umsatz, Kosten, Bestand und Lieferantenbeziehungen können für sich verstanden werden, ohne in die private Planung gemischt zu werden.",
    "El espacio empresarial está diseñado para la actividad financiera propia de gestionar una operación. Ingresos, costes, inventario y relaciones con proveedores pueden entenderse en sus propios términos sin mezclarse con la planificación personal.",
    "Hapësira e biznesit është projektuar për aktivitetin financiar që i përket drejtimit të një operacioni. Të ardhurat, kostot, inventari dhe marrëdhëniet me furnitorët mund të kuptohen më vete pa u përzier me planifikimin personal.",
    "صُممت مساحة الأعمال للنشاط المالي المرتبط بإدارة التشغيل. يمكن فهم الإيرادات والتكاليف والمخزون وعلاقات الموردين ضمن سياقها الخاص دون خلطها بالتخطيط الشخصي.",
    "O espaço empresarial foi concebido para a atividade financeira própria da operação de um negócio. Receitas, custos, inventário e relações com fornecedores podem ser compreendidos no seu próprio contexto sem serem misturados com o planeamento pessoal.",
    "Lo spazio aziendale è progettato per l’attività finanziaria legata alla gestione di un’operazione. Ricavi, costi, inventario e rapporti con i fornitori possono essere compresi nel loro contesto senza essere mescolati con la pianificazione personale.",
    "Бизнес-пространство предназначено для финансовой активности, связанной с ведением деятельности. Выручку, расходы, запасы и отношения с поставщиками можно понимать в их собственном контексте, не смешивая с личным планированием."
  ),
  "Revenue & operating costs": landing("Umsatz & Betriebskosten", "Ingresos y costes operativos", "Të ardhurat & kostot operative", "الإيرادات وتكاليف التشغيل", "Receitas e custos operacionais", "Ricavi e costi operativi", "Выручка и операционные расходы"),
  "Follow the money entering and leaving the business so operating performance remains visible.": landing("Verfolge das Geld, das ins Unternehmen hinein- und hinausfließt, damit die operative Leistung sichtbar bleibt.", "Sigue el dinero que entra y sale del negocio para mantener visible el rendimiento operativo.", "Ndiq paratë që hyjnë dhe dalin nga biznesi që performanca operative të mbetet e dukshme.", "تابع الأموال الداخلة إلى الأعمال والخارجة منها حتى يظل الأداء التشغيلي واضحًا.", "Acompanhe o dinheiro que entra e sai do negócio para manter visível o desempenho operacional.", "Segui il denaro che entra ed esce dall’azienda affinché la performance operativa resti visibile.", "Отслеживайте деньги, входящие и выходящие из бизнеса, чтобы операционная эффективность оставалась видимой."),
  "Inventory & suppliers": landing("Bestand & Lieferanten", "Inventario y proveedores", "Inventari & furnitorët", "المخزون والموردون", "Inventário e fornecedores", "Inventario e fornitori", "Запасы и поставщики"),
  "Keep commercially relevant records close to the financial picture instead of scattering them across unrelated tools.": landing("Halte geschäftlich relevante Datensätze nahe am Finanzbild, statt sie über unverbundene Werkzeuge zu verstreuen.", "Mantén los registros comercialmente relevantes cerca de la visión financiera en vez de dispersarlos entre herramientas no relacionadas.", "Mbaji të dhënat me rëndësi tregtare pranë pamjes financiare, në vend që t'i shpërndash në mjete të palidhura.", "أبقِ السجلات التجارية المهمة قريبة من الصورة المالية بدل توزيعها على أدوات غير مترابطة.", "Mantenha os registos comercialmente relevantes próximos da visão financeira em vez de os dispersar por ferramentas sem relação.", "Mantieni i dati commercialmente rilevanti vicini al quadro finanziario invece di disperderli tra strumenti scollegati.", "Держите коммерчески значимые записи рядом с финансовой картиной, а не распределяйте их по несвязанным инструментам."),
  "Business reporting": landing("Geschäftsberichte", "Informes empresariales", "Raportimi i biznesit", "تقارير الأعمال", "Relatórios empresariais", "Report aziendali", "Бизнес-отчётность"),
  "Review business-specific indicators without personal spending or household obligations distorting the interpretation.": landing("Prüfe geschäftsspezifische Kennzahlen, ohne dass private Ausgaben oder Haushaltsverpflichtungen die Interpretation verzerren.", "Revisa indicadores empresariales sin que el gasto personal o las obligaciones del hogar distorsionen la interpretación.", "Shqyrto treguesit specifikë të biznesit pa lejuar që shpenzimet personale ose detyrimet familjare të shtrembërojnë interpretimin.", "راجع مؤشرات الأعمال دون أن تشوّه المصروفات الشخصية أو التزامات الأسرة تفسيرها.", "Analise indicadores empresariais sem que despesas pessoais ou obrigações familiares distorçam a interpretação.", "Esamina indicatori aziendali senza che spese personali o obblighi familiari ne distorcano l’interpretazione.", "Анализируйте бизнес-показатели без искажения из-за личных расходов или обязательств домохозяйства."),
  "Dedicated operating context": landing("Eigener operativer Kontext", "Contexto operativo dedicado", "Kontekst operativ i dedikuar", "سياق تشغيلي مخصص", "Contexto operacional dedicado", "Contesto operativo dedicato", "Отдельный операционный контекст"),
  "Use the tools and records that belong to the business while maintaining the convenience of one FICONTER identity.": landing("Nutze die Werkzeuge und Datensätze, die zum Geschäft gehören, und behalte gleichzeitig den Komfort einer einzigen FICONTER-Identität.", "Usa las herramientas y registros propios del negocio manteniendo la comodidad de una sola identidad FICONTER.", "Përdor mjetet dhe të dhënat që i përkasin biznesit duke ruajtur komoditetin e një identiteti të vetëm FICONTER.", "استخدم الأدوات والسجلات الخاصة بالأعمال مع الحفاظ على سهولة هوية FICONTER واحدة.", "Use as ferramentas e os registos próprios do negócio mantendo a conveniência de uma única identidade FICONTER.", "Usa strumenti e dati propri dell’azienda mantenendo la comodità di un’unica identità FICONTER.", "Используйте инструменты и записи бизнеса, сохраняя удобство одной идентичности FICONTER."),
  "How they work together": landing("Wie beide zusammenarbeiten", "Cómo funcionan juntos", "Si funksionojnë së bashku", "كيف يعملان معًا", "Como funcionam em conjunto", "Come lavorano insieme", "Как они работают вместе"),
  "Together where useful. Separate where necessary.": landing("Zusammen, wo es sinnvoll ist. Getrennt, wo es notwendig ist.", "Juntos donde es útil. Separados donde es necesario.", "Së bashku aty ku është e dobishme. Të ndara aty ku është e nevojshme.", "معًا حيث يفيد. منفصلان حيث يلزم.", "Juntos onde é útil. Separados onde é necessário.", "Insieme dove serve. Separati dove è necessario.", "Вместе там, где полезно. Раздельно там, где необходимо."),
  "The value is not in combining every number into one ledger. The value is being able to manage both sides of your financial life without losing the distinction between them.": landing("Der Wert liegt nicht darin, jede Zahl in einem einzigen Ledger zusammenzuführen. Der Wert liegt darin, beide Seiten deines Finanzlebens zu verwalten, ohne die Unterscheidung zwischen ihnen zu verlieren.", "El valor no está en combinar cada cifra en un solo libro. Está en poder gestionar ambos lados de tu vida financiera sin perder la distinción entre ellos.", "Vlera nuk është te bashkimi i çdo shifre në një regjistër të vetëm. Vlera është të menaxhosh të dyja anët e jetës financiare pa humbur dallimin mes tyre.", "القيمة ليست في جمع كل رقم في سجل واحد، بل في القدرة على إدارة جانبي حياتك المالية دون فقدان التمييز بينهما.", "O valor não está em juntar todos os números num único registo. Está em conseguir gerir os dois lados da sua vida financeira sem perder a distinção entre eles.", "Il valore non sta nel combinare ogni numero in un unico registro, ma nel poter gestire entrambi i lati della propria vita finanziaria senza perdere la distinzione tra loro.", "Ценность не в объединении всех цифр в одну книгу, а в возможности управлять обеими сторонами финансовой жизни, не теряя различия между ними."),
  "One identity": landing("Eine Identität", "Una identidad", "Një identitet", "هوية واحدة", "Uma identidade", "Una identità", "Одна идентичность"),
  "Access both financial contexts through the same FICONTER account rather than maintaining separate products and logins.": landing("Greife über dasselbe FICONTER-Konto auf beide Finanzkontexte zu, statt separate Produkte und Anmeldungen zu pflegen.", "Accede a ambos contextos financieros con la misma cuenta FICONTER en lugar de mantener productos e inicios de sesión separados.", "Aksesoi të dy kontekstet financiare përmes të njëjtës llogari FICONTER, në vend që të mbash produkte dhe hyrje të veçanta.", "ادخل إلى السياقين الماليين عبر حساب FICONTER نفسه بدل الاحتفاظ بمنتجات وبيانات دخول منفصلة.", "Aceda aos dois contextos financeiros através da mesma conta FICONTER em vez de manter produtos e acessos separados.", "Accedi a entrambi i contesti finanziari con lo stesso account FICONTER invece di mantenere prodotti e accessi separati.", "Получайте доступ к обоим финансовым контекстам через один аккаунт FICONTER вместо отдельных продуктов и входов."),
  "Distinct records": landing("Getrennte Datensätze", "Registros separados", "Të dhëna të ndara", "سجلات منفصلة", "Registos distintos", "Dati distinti", "Раздельные записи"),
  "Each workspace retains the financial records and metrics appropriate to its purpose.": landing("Jeder Arbeitsbereich behält die Finanzdaten und Kennzahlen, die zu seinem Zweck passen.", "Cada espacio conserva los registros y métricas financieras apropiados para su propósito.", "Çdo hapësirë ruan të dhënat dhe metrikat financiare të përshtatshme për qëllimin e saj.", "تحتفظ كل مساحة عمل بالسجلات والمؤشرات المالية المناسبة لغرضها.", "Cada espaço mantém os registos e métricas financeiras adequados ao seu objetivo.", "Ogni spazio conserva i dati e le metriche finanziarie adatti al proprio scopo.", "Каждое пространство сохраняет финансовые записи и показатели, соответствующие его назначению."),
  "Cleaner interpretation": landing("Klarere Interpretation", "Interpretación más clara", "Interpretim më i pastër", "تفسير أوضح", "Interpretação mais clara", "Interpretazione più chiara", "Более чистая интерпретация"),
  "Keep business performance and personal financial health understandable without cross-contamination of unrelated activity.": landing("Halte Geschäftsleistung und persönliche finanzielle Gesundheit verständlich, ohne Vermischung nicht zusammengehöriger Aktivitäten.", "Mantén comprensibles el rendimiento empresarial y la salud financiera personal sin contaminación cruzada de actividad no relacionada.", "Mbaji performancën e biznesit dhe shëndetin financiar personal të kuptueshëm pa përzierje të aktiviteteve të palidhura.", "حافظ على وضوح أداء الأعمال والصحة المالية الشخصية دون تداخل أنشطة غير مرتبطة.", "Mantenha o desempenho empresarial e a saúde financeira pessoal compreensíveis sem mistura de atividades sem relação.", "Mantieni comprensibili performance aziendale e salute finanziaria personale senza contaminazione tra attività non correlate.", "Сохраняйте понятность бизнес-результатов и личного финансового здоровья без смешения несвязанных активностей."),
  "Room to grow": landing("Raum zum Wachsen", "Espacio para crecer", "Hapësirë për t'u rritur", "مساحة للنمو", "Espaço para crescer", "Spazio per crescere", "Пространство для роста"),
  "Start with personal finance and add business needs later, or manage both from the beginning as your financial life expands.": landing("Beginne mit privaten Finanzen und ergänze später geschäftliche Anforderungen – oder verwalte beides von Anfang an, wenn dein Finanzleben wächst.", "Empieza con las finanzas personales y añade necesidades empresariales más adelante, o gestiona ambas desde el principio a medida que tu vida financiera crece.", "Fillo me financat personale dhe shto nevojat e biznesit më vonë, ose menaxho të dyja që në fillim ndërsa jeta jote financiare zgjerohet.", "ابدأ بالشؤون المالية الشخصية وأضف احتياجات الأعمال لاحقًا، أو أدر كليهما منذ البداية مع توسع حياتك المالية.", "Comece pelas finanças pessoais e adicione necessidades empresariais mais tarde, ou gira ambas desde o início à medida que a sua vida financeira cresce.", "Inizia con le finanze personali e aggiungi in seguito le esigenze aziendali, oppure gestisci entrambe fin dall’inizio mentre la tua vita finanziaria cresce.", "Начните с личных финансов и добавьте бизнес-потребности позже либо управляйте обоими с самого начала по мере роста финансовой жизни."),
  "Workspace flow": landing("Arbeitsbereichsablauf", "Flujo de espacios", "Rrjedha e hapësirës", "مسار مساحة العمل", "Fluxo de espaços", "Flusso degli spazi", "Поток рабочих пространств"),
  "The user always knows which financial context they are managing.": landing("Der Nutzer weiß immer, welchen Finanzkontext er gerade verwaltet.", "El usuario siempre sabe qué contexto financiero está gestionando.", "Përdoruesi e di gjithmonë cilin kontekst financiar po menaxhon.", "يعرف المستخدم دائمًا أي سياق مالي يديره.", "O utilizador sabe sempre qual o contexto financeiro que está a gerir.", "L’utente sa sempre quale contesto finanziario sta gestendo.", "Пользователь всегда знает, каким финансовым контекстом он управляет."),
  "Workspace separation is useful only when switching stays simple. FICONTER keeps the transition deliberate and immediate.": landing("Die Trennung von Arbeitsbereichen ist nur dann nützlich, wenn der Wechsel einfach bleibt. FICONTER hält den Übergang bewusst und unmittelbar.", "Separar espacios solo es útil si cambiar entre ellos sigue siendo sencillo. FICONTER mantiene la transición deliberada e inmediata.", "Ndarja e hapësirave është e dobishme vetëm kur ndërrimi mbetet i thjeshtë. FICONTER e mban kalimin të qëllimshëm dhe të menjëhershëm.", "يكون فصل مساحات العمل مفيدًا فقط عندما يبقى التبديل بسيطًا. تجعل FICONTER الانتقال مقصودًا وفوريًا.", "A separação de espaços só é útil quando a mudança continua simples. A FICONTER mantém a transição deliberada e imediata.", "La separazione degli spazi è utile solo se il passaggio resta semplice. FICONTER mantiene la transizione intenzionale e immediata.", "Разделение пространств полезно только при простом переключении. FICONTER делает переход осознанным и мгновенным."),
  "Choose the context": landing("Kontext wählen", "Elige el contexto", "Zgjidh kontekstin", "اختر السياق", "Escolha o contexto", "Scegli il contesto", "Выберите контекст"),
  "Enter the personal or business workspace depending on the financial decision you are making.": landing("Öffne je nach finanzieller Entscheidung den privaten oder geschäftlichen Arbeitsbereich.", "Entra en el espacio personal o empresarial según la decisión financiera que estés tomando.", "Hyr në hapësirën personale ose të biznesit sipas vendimit financiar që po merr.", "ادخل إلى مساحة العمل الشخصية أو التجارية بحسب القرار المالي الذي تتخذه.", "Entre no espaço pessoal ou empresarial consoante a decisão financeira que está a tomar.", "Entra nello spazio personale o aziendale in base alla decisione finanziaria che stai prendendo.", "Входите в личное или бизнес-пространство в зависимости от финансового решения."),
  "Work with the right records": landing("Mit den richtigen Datensätzen arbeiten", "Trabaja con los registros adecuados", "Puno me të dhënat e duhura", "اعمل بالسجلات المناسبة", "Trabalhe com os registos certos", "Lavora con i dati giusti", "Работайте с нужными записями"),
  "Use the modules and metrics that belong to that workspace instead of combining unrelated activity.": landing("Nutze die Module und Kennzahlen dieses Arbeitsbereichs, statt nicht zusammengehörige Aktivitäten zu kombinieren.", "Usa los módulos y métricas que pertenecen a ese espacio en lugar de combinar actividad no relacionada.", "Përdor modulet dhe metrikat që i përkasin asaj hapësire, në vend që të kombinosh aktivitete të palidhura.", "استخدم الوحدات والمؤشرات الخاصة بتلك المساحة بدل جمع أنشطة غير مرتبطة.", "Use os módulos e métricas que pertencem a esse espaço em vez de combinar atividade sem relação.", "Usa moduli e metriche propri di quello spazio invece di combinare attività non correlate.", "Используйте модули и показатели соответствующего пространства вместо объединения несвязанных активностей."),
  "Switch when needed": landing("Bei Bedarf wechseln", "Cambia cuando lo necesites", "Ndërro kur nevojitet", "بدّل عند الحاجة", "Mude quando necessário", "Cambia quando serve", "Переключайтесь при необходимости"),
  "Move to the other workspace through the same account without signing into another product.": landing("Wechsle über dasselbe Konto in den anderen Arbeitsbereich, ohne dich bei einem anderen Produkt anzumelden.", "Pasa al otro espacio con la misma cuenta sin iniciar sesión en otro producto.", "Kalo në hapësirën tjetër përmes së njëjtës llogari pa hyrë në një produkt tjetër.", "انتقل إلى مساحة العمل الأخرى عبر الحساب نفسه دون تسجيل الدخول إلى منتج آخر.", "Mude para o outro espaço através da mesma conta sem iniciar sessão noutro produto.", "Passa all’altro spazio tramite lo stesso account senza accedere a un altro prodotto.", "Переходите в другое пространство через тот же аккаунт без входа в другой продукт."),
  "Keep both understandable": landing("Beide verständlich halten", "Mantén ambos comprensibles", "Mbaji të dyja të kuptueshme", "حافظ على وضوح كليهما", "Mantenha ambos compreensíveis", "Mantienili entrambi comprensibili", "Сохраняйте понятность обоих"),
  "Each workspace continues to reflect its own financial position, history and direction.": landing("Jeder Arbeitsbereich bildet weiterhin seine eigene finanzielle Lage, Historie und Richtung ab.", "Cada espacio sigue reflejando su propia posición financiera, historial y dirección.", "Çdo hapësirë vazhdon të pasqyrojë pozicionin, historinë dhe drejtimin e vet financiar.", "تواصل كل مساحة عمل عكس وضعها المالي وتاريخها واتجاهها الخاص.", "Cada espaço continua a refletir a sua própria posição financeira, histórico e direção.", "Ogni spazio continua a riflettere la propria posizione finanziaria, storia e direzione.", "Каждое пространство продолжает отражать собственное финансовое положение, историю и направление."),
  "Why it matters": landing("Warum das wichtig ist", "Por qué importa", "Pse ka rëndësi", "لماذا يهم", "Porque é importante", "Perché è importante", "Почему это важно"),
  "A business can be part of your life without becoming your household ledger.": landing("Ein Unternehmen kann Teil deines Lebens sein, ohne zum Haushaltsbuch zu werden.", "Un negocio puede formar parte de tu vida sin convertirse en el libro de cuentas del hogar.", "Një biznes mund të jetë pjesë e jetës tënde pa u bërë regjistri financiar i familjes.", "يمكن أن يكون العمل جزءًا من حياتك دون أن يتحول إلى سجل حسابات الأسرة.", "Um negócio pode fazer parte da sua vida sem se tornar o livro de contas do agregado familiar.", "Un’azienda può far parte della tua vita senza diventare il registro finanziario di casa.", "Бизнес может быть частью вашей жизни, не превращаясь в домашнюю бухгалтерскую книгу."),
  "FICONTER treats personal and business finance as connected responsibilities, not interchangeable records. That distinction keeps the information cleaner and makes the combined system more useful as financial complexity grows.": landing(
    "FICONTER behandelt private und geschäftliche Finanzen als verbundene Verantwortlichkeiten, nicht als austauschbare Datensätze. Diese Unterscheidung hält die Informationen sauberer und macht das Gesamtsystem nützlicher, wenn die finanzielle Komplexität wächst.",
    "FICONTER trata las finanzas personales y empresariales como responsabilidades conectadas, no como registros intercambiables. Esa distinción mantiene la información más limpia y hace que el sistema conjunto sea más útil a medida que crece la complejidad financiera.",
    "FICONTER i trajton financat personale dhe të biznesit si përgjegjësi të lidhura, jo si të dhëna të këmbyeshme. Ky dallim e mban informacionin më të pastër dhe e bën sistemin e përbashkët më të dobishëm ndërsa kompleksiteti financiar rritet.",
    "تتعامل FICONTER مع التمويل الشخصي والتجاري كمسؤوليات مترابطة، لا كسجلات قابلة للتبادل. يحافظ هذا التمييز على نظافة المعلومات ويجعل النظام المشترك أكثر فائدة مع ازدياد التعقيد المالي.",
    "A FICONTER trata as finanças pessoais e empresariais como responsabilidades ligadas, não como registos intercambiáveis. Essa distinção mantém a informação mais limpa e torna o sistema conjunto mais útil à medida que a complexidade financeira aumenta.",
    "FICONTER tratta finanza personale e aziendale come responsabilità collegate, non come dati intercambiabili. Questa distinzione mantiene le informazioni più pulite e rende il sistema complessivo più utile con l’aumentare della complessità finanziaria.",
    "FICONTER рассматривает личные и деловые финансы как связанные обязанности, а не взаимозаменяемые записи. Это различие делает информацию чище и общую систему полезнее по мере роста финансовой сложности."
  ),
};

Object.assign(LANDING_UI_TRANSLATIONS, PUBLIC_PERSONAL_BUSINESS_TRANSLATIONS);
