import type { FiconterLanguage } from "./config";
import { LANDING_UI_TRANSLATIONS } from "./landingUiCatalog";

type NonEnglishLanguage = Exclude<FiconterLanguage, "en">;
type TranslationRow = Record<NonEnglishLanguage, string>;

function landing(de: string, es: string, sq: string, ar: string, pt: string, it: string, ru: string): TranslationRow {
  return { de, es, sq, ar, pt, it, ru };
}

/** Exact sentence-level translations for /privacy. */
export const PUBLIC_PRIVACY_TRANSLATIONS: Record<string, TranslationRow> = {
  "Privacy & trust": landing("Datenschutz & Vertrauen", "Privacidad y confianza", "Privatësi & besim", "الخصوصية والثقة", "Privacidade e confiança", "Privacy e fiducia", "Конфиденциальность и доверие"),
  "Your financial workspace should remain yours.": landing("Dein finanzieller Arbeitsbereich sollte deiner bleiben.", "Tu espacio financiero debe seguir siendo tuyo.", "Hapësira jote financiare duhet të mbetet e jotja.", "يجب أن تبقى مساحة عملك المالية ملكًا لك.", "O seu espaço financeiro deve continuar a ser seu.", "Il tuo spazio finanziario deve restare tuo.", "Ваше финансовое пространство должно оставаться вашим."),
  "Financial information is deeply personal. FICONTER is designed around authenticated access, account-level separation and a business model that does not depend on advertising against a user's financial activity. Privacy is treated as part of the product architecture, not merely as a legal page.": landing(
    "Finanzinformationen sind sehr persönlich. FICONTER ist auf authentifizierten Zugriff, Trennung auf Kontoebene und ein Geschäftsmodell ausgelegt, das nicht von Werbung auf Basis der finanziellen Aktivität eines Nutzers abhängt. Datenschutz wird als Teil der Produktarchitektur behandelt, nicht nur als rechtliche Seite.",
    "La información financiera es profundamente personal. FICONTER está diseñado en torno al acceso autenticado, la separación a nivel de cuenta y un modelo de negocio que no depende de publicidad basada en la actividad financiera del usuario. La privacidad se trata como parte de la arquitectura del producto, no solo como una página legal.",
    "Informacioni financiar është shumë personal. FICONTER është projektuar rreth qasjes së autentikuar, ndarjes në nivel llogarie dhe një modeli biznesi që nuk varet nga reklamat mbi aktivitetin financiar të përdoruesit. Privatësia trajtohet si pjesë e arkitekturës së produktit, jo thjesht si një faqe ligjore.",
    "المعلومات المالية شديدة الخصوصية. صُممت FICONTER حول الوصول الموثق، والفصل على مستوى الحساب، ونموذج أعمال لا يعتمد على الإعلانات المبنية على النشاط المالي للمستخدم. تُعامل الخصوصية كجزء من بنية المنتج، لا كمجرد صفحة قانونية.",
    "A informação financeira é profundamente pessoal. A FICONTER foi concebida em torno de acesso autenticado, separação ao nível da conta e um modelo de negócio que não depende de publicidade baseada na atividade financeira do utilizador. A privacidade é tratada como parte da arquitetura do produto, não apenas como uma página legal.",
    "Le informazioni finanziarie sono profondamente personali. FICONTER è progettata attorno ad accesso autenticato, separazione a livello di account e un modello di business che non dipende dalla pubblicità basata sull’attività finanziaria dell’utente. La privacy è trattata come parte dell’architettura del prodotto, non soltanto come una pagina legale.",
    "Финансовая информация глубоко личная. FICONTER построен вокруг аутентифицированного доступа, разделения на уровне аккаунта и бизнес-модели, не зависящей от рекламы на основе финансовой активности пользователя. Конфиденциальность рассматривается как часть архитектуры продукта, а не просто как юридическая страница."
  ),
  "PRIVATE BY DESIGN": landing("PRIVATSPHÄRE VON ANFANG AN", "PRIVADO POR DISEÑO", "PRIVATE QË NË DIZAJN", "الخصوصية منذ التصميم", "PRIVADO DESDE A CONCEÇÃO", "PRIVATO PER PROGETTAZIONE", "КОНФИДЕНЦИАЛЬНОСТЬ ПО УМОЛЧАНИЮ"),
  "Access should be deliberate, records should stay separated and the user should remain in control of the financial information they choose to place in FICONTER.": landing("Zugriff sollte bewusst erfolgen, Datensätze sollten getrennt bleiben und der Nutzer sollte die Kontrolle über die Finanzinformationen behalten, die er in FICONTER einträgt.", "El acceso debe ser deliberado, los registros deben permanecer separados y el usuario debe mantener el control de la información financiera que decide introducir en FICONTER.", "Qasja duhet të jetë e qëllimshme, të dhënat duhet të mbeten të ndara dhe përdoruesi duhet të mbajë kontrollin mbi informacionin financiar që zgjedh të vendosë në FICONTER.", "يجب أن يكون الوصول مقصودًا، وأن تبقى السجلات منفصلة، وأن يظل المستخدم مسيطرًا على المعلومات المالية التي يختار وضعها في FICONTER.", "O acesso deve ser deliberado, os registos devem manter-se separados e o utilizador deve continuar a controlar a informação financeira que escolhe colocar na FICONTER.", "L’accesso deve essere intenzionale, i dati devono restare separati e l’utente deve mantenere il controllo delle informazioni finanziarie che sceglie di inserire in FICONTER.", "Доступ должен быть осознанным, записи — оставаться разделёнными, а пользователь — сохранять контроль над финансовой информацией, которую он решает разместить в FICONTER."),
  "Authenticated access": landing("Authentifizierter Zugriff", "Acceso autenticado", "Qasje e autentikuar", "وصول موثق", "Acesso autenticado", "Accesso autenticato", "Аутентифицированный доступ"),
  "Access to a FICONTER workspace begins with an authenticated user identity rather than an open or shared financial environment.": landing("Der Zugriff auf einen FICONTER-Arbeitsbereich beginnt mit einer authentifizierten Nutzeridentität statt mit einer offenen oder gemeinsam genutzten Finanzumgebung.", "El acceso a un espacio FICONTER comienza con una identidad de usuario autenticada, no con un entorno financiero abierto o compartido.", "Qasja në një hapësirë FICONTER fillon me një identitet përdoruesi të autentikuar, jo me një mjedis financiar të hapur ose të përbashkët.", "يبدأ الوصول إلى مساحة عمل FICONTER بهوية مستخدم موثقة، لا ببيئة مالية مفتوحة أو مشتركة.", "O acesso a um espaço FICONTER começa com uma identidade de utilizador autenticada, e não com um ambiente financeiro aberto ou partilhado.", "L’accesso a uno spazio FICONTER inizia da un’identità utente autenticata, non da un ambiente finanziario aperto o condiviso.", "Доступ к пространству FICONTER начинается с аутентифицированной личности пользователя, а не с открытой или общей финансовой среды."),
  "Workspace isolation": landing("Isolation von Arbeitsbereichen", "Aislamiento de espacios", "Izolimi i hapësirave", "عزل مساحات العمل", "Isolamento de espaços", "Isolamento degli spazi", "Изоляция рабочих пространств"),
  "Database-level access policies are used so customers can access only the records associated with their own authorised context.": landing("Zugriffsrichtlinien auf Datenbankebene sorgen dafür, dass Kunden nur auf Datensätze zugreifen können, die ihrem eigenen autorisierten Kontext zugeordnet sind.", "Se utilizan políticas de acceso a nivel de base de datos para que los clientes solo puedan acceder a los registros asociados a su propio contexto autorizado.", "Përdoren politika qasjeje në nivel databaze që klientët të mund të aksesojnë vetëm të dhënat e lidhura me kontekstin e tyre të autorizuar.", "تُستخدم سياسات وصول على مستوى قاعدة البيانات حتى يتمكن العملاء من الوصول فقط إلى السجلات المرتبطة بسياقهم المصرح به.", "São utilizadas políticas de acesso ao nível da base de dados para que os clientes acedam apenas aos registos associados ao seu próprio contexto autorizado.", "Vengono usate politiche di accesso a livello database affinché i clienti possano accedere solo ai dati associati al proprio contesto autorizzato.", "Политики доступа на уровне базы данных позволяют клиентам получать доступ только к записям, связанным с их авторизованным контекстом."),
  "No advertising model": landing("Kein Werbemodell", "Sin modelo publicitario", "Pa model reklamimi", "لا نموذج إعلاني", "Sem modelo publicitário", "Nessun modello pubblicitario", "Без рекламной модели"),
  "FICONTER is not designed around selling attention or building an advertising profile from a user's financial activity.": landing("FICONTER ist nicht darauf ausgelegt, Aufmerksamkeit zu verkaufen oder aus der finanziellen Aktivität eines Nutzers ein Werbeprofil zu erstellen.", "FICONTER no está diseñado para vender atención ni crear un perfil publicitario a partir de la actividad financiera del usuario.", "FICONTER nuk është projektuar për të shitur vëmendje ose për të ndërtuar profil reklamues nga aktiviteti financiar i përdoruesit.", "لا تُصمم FICONTER لبيع انتباه المستخدم أو بناء ملف إعلاني من نشاطه المالي.", "A FICONTER não foi concebida para vender atenção nem criar um perfil publicitário a partir da atividade financeira do utilizador.", "FICONTER non è progettata per vendere attenzione o costruire un profilo pubblicitario dall’attività finanziaria dell’utente.", "FICONTER не предназначен для продажи внимания или создания рекламного профиля на основе финансовой активности пользователя."),
  "User control": landing("Nutzerkontrolle", "Control del usuario", "Kontrolli i përdoruesit", "تحكم المستخدم", "Controlo do utilizador", "Controllo dell’utente", "Контроль пользователя"),
  "The platform is built so users decide what financial information enters their workspace and how they organise it.": landing("Die Plattform ist so gebaut, dass Nutzer entscheiden, welche Finanzinformationen in ihren Arbeitsbereich gelangen und wie sie organisiert werden.", "La plataforma está construida para que los usuarios decidan qué información financiera entra en su espacio y cómo la organizan.", "Platforma është ndërtuar që përdoruesit të vendosin çfarë informacioni financiar hyn në hapësirën e tyre dhe si e organizojnë atë.", "بُنيت المنصة بحيث يقرر المستخدم ما المعلومات المالية التي تدخل مساحة عمله وكيف ينظمها.", "A plataforma foi construída para que os utilizadores decidam que informação financeira entra no seu espaço e como a organizam.", "La piattaforma è costruita affinché gli utenti decidano quali informazioni finanziarie entrano nel proprio spazio e come organizzarle.", "Платформа построена так, чтобы пользователи решали, какая финансовая информация попадает в их пространство и как она организуется."),
  "FICONTER should organise your information—not take ownership of your financial life.": landing("FICONTER sollte deine Informationen organisieren – nicht die Kontrolle über dein Finanzleben übernehmen.", "FICONTER debe organizar tu información, no apropiarse de tu vida financiera.", "FICONTER duhet të organizojë informacionin tënd, jo të marrë pronësinë e jetës tënde financiare.", "يجب أن تنظّم FICONTER معلوماتك، لا أن تسيطر على حياتك المالية.", "A FICONTER deve organizar a sua informação, não assumir o controlo da sua vida financeira.", "FICONTER deve organizzare le tue informazioni, non appropriarsi della tua vita finanziaria.", "FICONTER должен организовывать вашу информацию, а не присваивать контроль над вашей финансовой жизнью."),
  "The product philosophy is based on direct user control. Users choose what they record, how they structure it and which personal or business workspace it belongs to. FICONTER does not require a bank connection simply to make the core planning system useful.": landing(
    "Die Produktphilosophie basiert auf direkter Nutzerkontrolle. Nutzer wählen, was sie erfassen, wie sie es strukturieren und welchem privaten oder geschäftlichen Arbeitsbereich es zugeordnet wird. FICONTER verlangt keine Bankverbindung, nur damit das Kernplanungssystem nützlich ist.",
    "La filosofía del producto se basa en el control directo del usuario. Los usuarios eligen qué registran, cómo lo estructuran y a qué espacio personal o empresarial pertenece. FICONTER no exige una conexión bancaria simplemente para que el sistema principal de planificación sea útil.",
    "Filozofia e produktit bazohet në kontrollin e drejtpërdrejtë të përdoruesit. Përdoruesit zgjedhin çfarë regjistrojnë, si e strukturojnë dhe cilës hapësirë personale ose biznesi i përket. FICONTER nuk kërkon lidhje bankare vetëm që sistemi bazë i planifikimit të jetë i dobishëm.",
    "تعتمد فلسفة المنتج على التحكم المباشر للمستخدم. يختار المستخدم ما يسجله وكيف ينظمه وإلى أي مساحة شخصية أو تجارية ينتمي. لا تتطلب FICONTER اتصالًا مصرفيًا لمجرد جعل نظام التخطيط الأساسي مفيدًا.",
    "A filosofia do produto baseia-se no controlo direto do utilizador. Os utilizadores escolhem o que registam, como estruturam a informação e a que espaço pessoal ou empresarial pertence. A FICONTER não exige uma ligação bancária apenas para tornar útil o sistema principal de planeamento.",
    "La filosofia del prodotto si basa sul controllo diretto dell’utente. Gli utenti scelgono cosa registrare, come strutturarlo e a quale spazio personale o aziendale appartiene. FICONTER non richiede un collegamento bancario solo per rendere utile il sistema di pianificazione principale.",
    "Философия продукта основана на прямом контроле пользователя. Пользователи решают, что записывать, как структурировать информацию и к какому личному или деловому пространству она относится. FICONTER не требует подключения к банку только ради полезности основной системы планирования."
  ),
  "You decide what enters": landing("Du entscheidest, was hineinkommt", "Tú decides qué entra", "Ti vendos çfarë hyn", "أنت تقرر ما الذي يدخل", "Você decide o que entra", "Decidi tu cosa entra", "Вы решаете, что входит"),
  "Financial information is added because the user chooses to record or manage it inside the platform.": landing("Finanzinformationen werden hinzugefügt, weil der Nutzer entscheidet, sie innerhalb der Plattform zu erfassen oder zu verwalten.", "La información financiera se añade porque el usuario decide registrarla o gestionarla dentro de la plataforma.", "Informacioni financiar shtohet sepse përdoruesi zgjedh ta regjistrojë ose menaxhojë brenda platformës.", "تُضاف المعلومات المالية لأن المستخدم يختار تسجيلها أو إدارتها داخل المنصة.", "A informação financeira é adicionada porque o utilizador escolhe registá-la ou geri-la dentro da plataforma.", "Le informazioni finanziarie vengono aggiunte perché l’utente sceglie di registrarle o gestirle nella piattaforma.", "Финансовая информация добавляется, потому что пользователь сам решает записывать или управлять ею внутри платформы."),
  "No mandatory bank connection": landing("Keine verpflichtende Bankverbindung", "Sin conexión bancaria obligatoria", "Pa lidhje bankare të detyrueshme", "لا اتصال مصرفي إلزامي", "Sem ligação bancária obrigatória", "Nessun collegamento bancario obbligatorio", "Без обязательного подключения банка"),
  "Core FICONTER planning and control tools can be used without granting the platform direct access to a user's banking relationship.": landing("Die zentralen Planungs- und Kontrollwerkzeuge von FICONTER können genutzt werden, ohne der Plattform direkten Zugriff auf die Bankbeziehung des Nutzers zu gewähren.", "Las herramientas principales de planificación y control de FICONTER pueden utilizarse sin conceder a la plataforma acceso directo a la relación bancaria del usuario.", "Mjetet bazë të planifikimit dhe kontrollit të FICONTER mund të përdoren pa i dhënë platformës qasje të drejtpërdrejtë në marrëdhënien bankare të përdoruesit.", "يمكن استخدام أدوات التخطيط والتحكم الأساسية في FICONTER دون منح المنصة وصولًا مباشرًا إلى العلاقة المصرفية للمستخدم.", "As ferramentas principais de planeamento e controlo da FICONTER podem ser utilizadas sem dar à plataforma acesso direto à relação bancária do utilizador.", "Gli strumenti principali di pianificazione e controllo di FICONTER possono essere usati senza concedere alla piattaforma accesso diretto al rapporto bancario dell’utente.", "Основные инструменты планирования и контроля FICONTER можно использовать без предоставления платформе прямого доступа к банковским отношениям пользователя."),
  "Separate financial contexts": landing("Getrennte Finanzkontexte", "Contextos financieros separados", "Kontekste financiare të ndara", "سياقات مالية منفصلة", "Contextos financeiros separados", "Contesti finanziari separati", "Раздельные финансовые контексты"),
  "Personal and business information can remain logically separated so one context does not become an unnecessary source of exposure for the other.": landing("Private und geschäftliche Informationen können logisch getrennt bleiben, damit ein Kontext nicht zu einer unnötigen Offenlegungsquelle für den anderen wird.", "La información personal y empresarial puede permanecer lógicamente separada para que un contexto no se convierta en una fuente innecesaria de exposición para el otro.", "Informacioni personal dhe i biznesit mund të mbetet logjikisht i ndarë që një kontekst të mos bëhet burim i panevojshëm ekspozimi për tjetrin.", "يمكن أن تبقى المعلومات الشخصية والتجارية منفصلة منطقيًا حتى لا يصبح أحد السياقين مصدر كشف غير ضروري للآخر.", "A informação pessoal e empresarial pode permanecer logicamente separada para que um contexto não se torne uma fonte desnecessária de exposição para o outro.", "Le informazioni personali e aziendali possono restare logicamente separate affinché un contesto non diventi una fonte inutile di esposizione per l’altro.", "Личная и деловая информация может оставаться логически разделённой, чтобы один контекст не создавал ненужного риска раскрытия для другого."),
  "No advertising against your finances": landing("Keine Werbung auf Basis deiner Finanzen", "Sin publicidad basada en tus finanzas", "Pa reklama mbi financat e tua", "لا إعلانات مبنية على أموالك", "Sem publicidade baseada nas suas finanças", "Nessuna pubblicità basata sulle tue finanze", "Без рекламы на основе ваших финансов"),
  "The platform is not designed to monetise financial behaviour through targeted advertising.": landing("Die Plattform ist nicht darauf ausgelegt, finanzielles Verhalten durch zielgerichtete Werbung zu monetarisieren.", "La plataforma no está diseñada para monetizar el comportamiento financiero mediante publicidad dirigida.", "Platforma nuk është projektuar për të monetizuar sjelljen financiare përmes reklamave të synuara.", "لا تُصمم المنصة لتحقيق دخل من السلوك المالي عبر الإعلانات الموجهة.", "A plataforma não foi concebida para monetizar o comportamento financeiro através de publicidade direcionada.", "La piattaforma non è progettata per monetizzare il comportamento finanziario tramite pubblicità mirata.", "Платформа не предназначена для монетизации финансового поведения через таргетированную рекламу."),
  "Privacy needs technical enforcement behind the interface.": landing("Datenschutz braucht technische Durchsetzung hinter der Oberfläche.", "La privacidad necesita aplicación técnica detrás de la interfaz.", "Privatësia kërkon zbatim teknik pas ndërfaqes.", "تحتاج الخصوصية إلى تطبيق تقني خلف الواجهة.", "A privacidade precisa de aplicação técnica por detrás da interface.", "La privacy richiede applicazione tecnica dietro l’interfaccia.", "Конфиденциальность требует технического обеспечения за интерфейсом."),
  "A trustworthy financial interface cannot rely only on visual separation. FICONTER uses authenticated sessions and database-level access controls so access rules remain part of the underlying system as well as the user experience.": landing(
    "Eine vertrauenswürdige Finanzoberfläche kann sich nicht nur auf visuelle Trennung verlassen. FICONTER nutzt authentifizierte Sitzungen und Zugriffskontrollen auf Datenbankebene, damit Zugriffsregeln sowohl Teil des zugrunde liegenden Systems als auch der Nutzererfahrung bleiben.",
    "Una interfaz financiera confiable no puede depender solo de la separación visual. FICONTER utiliza sesiones autenticadas y controles de acceso a nivel de base de datos para que las reglas de acceso formen parte tanto del sistema subyacente como de la experiencia del usuario.",
    "Një ndërfaqe financiare e besueshme nuk mund të mbështetet vetëm te ndarja vizuale. FICONTER përdor sesione të autentikuara dhe kontrolle qasjeje në nivel databaze që rregullat e qasjes të mbeten pjesë e sistemit bazë dhe e përvojës së përdoruesit.",
    "لا يمكن لواجهة مالية موثوقة أن تعتمد على الفصل البصري فقط. تستخدم FICONTER جلسات موثقة وضوابط وصول على مستوى قاعدة البيانات حتى تبقى قواعد الوصول جزءًا من النظام الأساسي ومن تجربة المستخدم أيضًا.",
    "Uma interface financeira fiável não pode depender apenas da separação visual. A FICONTER utiliza sessões autenticadas e controlos de acesso ao nível da base de dados para que as regras de acesso façam parte do sistema subjacente e da experiência do utilizador.",
    "Un’interfaccia finanziaria affidabile non può basarsi solo sulla separazione visiva. FICONTER usa sessioni autenticate e controlli di accesso a livello database affinché le regole di accesso restino parte sia del sistema sottostante sia dell’esperienza utente.",
    "Надёжный финансовый интерфейс не может полагаться только на визуальное разделение. FICONTER использует аутентифицированные сессии и контроль доступа на уровне базы данных, чтобы правила доступа были частью как базовой системы, так и пользовательского опыта."
  ),
  "Secure authentication": landing("Sichere Authentifizierung", "Autenticación segura", "Autentikim i sigurt", "مصادقة آمنة", "Autenticação segura", "Autenticazione sicura", "Безопасная аутентификация"),
  "Account access is protected through the platform's authentication layer before private workspace data is made available.": landing("Der Kontozugriff wird durch die Authentifizierungsebene der Plattform geschützt, bevor private Arbeitsbereichsdaten verfügbar werden.", "El acceso a la cuenta está protegido por la capa de autenticación de la plataforma antes de que los datos privados del espacio estén disponibles.", "Qasja në llogari mbrohet përmes shtresës së autentikimit të platformës para se të dhënat private të hapësirës të bëhen të disponueshme.", "تتم حماية الوصول إلى الحساب عبر طبقة المصادقة في المنصة قبل إتاحة بيانات مساحة العمل الخاصة.", "O acesso à conta é protegido pela camada de autenticação da plataforma antes de os dados privados do espaço ficarem disponíveis.", "L’accesso all’account è protetto dal livello di autenticazione della piattaforma prima che i dati privati dello spazio siano disponibili.", "Доступ к аккаунту защищается слоем аутентификации платформы до предоставления данных приватного пространства."),
  "Database-level access policies": landing("Zugriffsrichtlinien auf Datenbankebene", "Políticas de acceso a nivel de base de datos", "Politika qasjeje në nivel databaze", "سياسات وصول على مستوى قاعدة البيانات", "Políticas de acesso ao nível da base de dados", "Politiche di accesso a livello database", "Политики доступа на уровне базы данных"),
  "Access restrictions are enforced at the data layer so records are not intended to become visible simply because a client interface requests them.": landing("Zugriffsbeschränkungen werden auf Datenebene durchgesetzt, damit Datensätze nicht allein deshalb sichtbar werden, weil eine Client-Oberfläche sie anfordert.", "Las restricciones de acceso se aplican en la capa de datos para que los registros no se vuelvan visibles simplemente porque una interfaz cliente los solicite.", "Kufizimet e qasjes zbatohen në shtresën e të dhënave që regjistrat të mos bëhen të dukshëm vetëm sepse një ndërfaqe klienti i kërkon.", "تُفرض قيود الوصول في طبقة البيانات حتى لا تصبح السجلات مرئية لمجرد أن واجهة العميل تطلبها.", "As restrições de acesso são aplicadas na camada de dados para que os registos não se tornem visíveis simplesmente porque uma interface cliente os solicita.", "Le restrizioni di accesso vengono applicate a livello dati affinché i record non diventino visibili solo perché un’interfaccia client li richiede.", "Ограничения доступа применяются на уровне данных, чтобы записи не становились видимыми лишь потому, что клиентский интерфейс их запросил."),
  "Private workspace boundaries": landing("Grenzen privater Arbeitsbereiche", "Límites del espacio privado", "Kufijtë e hapësirës private", "حدود مساحة العمل الخاصة", "Limites do espaço privado", "Confini dello spazio privato", "Границы приватного пространства"),
  "Personal customer records remain associated with the authorised workspace rather than being exposed as a shared application dataset.": landing("Persönliche Kundendaten bleiben dem autorisierten Arbeitsbereich zugeordnet, statt als gemeinsam genutzter Anwendungsdatensatz offengelegt zu werden.", "Los registros personales del cliente permanecen asociados al espacio autorizado en lugar de exponerse como un conjunto de datos compartido de la aplicación.", "Të dhënat personale të klientit mbeten të lidhura me hapësirën e autorizuar, në vend që të ekspozohen si një grup i përbashkët të dhënash i aplikacionit.", "تبقى سجلات العميل الشخصية مرتبطة بمساحة العمل المصرح بها بدل عرضها كمجموعة بيانات مشتركة للتطبيق.", "Os registos pessoais do cliente permanecem associados ao espaço autorizado em vez de serem expostos como um conjunto de dados partilhado da aplicação.", "I dati personali del cliente restano associati allo spazio autorizzato invece di essere esposti come dataset condiviso dell’applicazione.", "Личные записи клиента остаются связанными с авторизованным пространством, а не раскрываются как общий набор данных приложения."),
  "Role-aware access": landing("Rollenbasierter Zugriff", "Acceso según el rol", "Qasje sipas rolit", "وصول حسب الدور", "Acesso baseado em funções", "Accesso basato sui ruoli", "Доступ с учётом ролей"),
  "Administrative and workspace capabilities are separated by role so elevated controls are not treated as ordinary user functions.": landing("Administrative und Arbeitsbereichsfunktionen sind nach Rollen getrennt, sodass erweiterte Kontrollen nicht wie gewöhnliche Nutzerfunktionen behandelt werden.", "Las capacidades administrativas y del espacio se separan por rol para que los controles elevados no se traten como funciones de usuario ordinarias.", "Aftësitë administrative dhe të hapësirës ndahen sipas rolit që kontrollet e avancuara të mos trajtohen si funksione të zakonshme përdoruesi.", "تُفصل القدرات الإدارية وقدرات مساحة العمل حسب الدور حتى لا تُعامل الضوابط المرتفعة كوظائف مستخدم عادية.", "As capacidades administrativas e do espaço são separadas por função para que controlos elevados não sejam tratados como funções normais de utilizador.", "Le capacità amministrative e dello spazio sono separate per ruolo affinché i controlli elevati non siano trattati come normali funzioni utente.", "Административные возможности и функции рабочего пространства разделены по ролям, чтобы повышенные полномочия не считались обычными пользовательскими функциями."),
  "Trust model": landing("Vertrauensmodell", "Modelo de confianza", "Modeli i besimit", "نموذج الثقة", "Modelo de confiança", "Modello di fiducia", "Модель доверия"),
  "A simple principle: minimise unnecessary access.": landing("Ein einfaches Prinzip: unnötigen Zugriff minimieren.", "Un principio sencillo: minimizar el acceso innecesario.", "Një parim i thjeshtë: minimizo qasjen e panevojshme.", "مبدأ بسيط: قلّل الوصول غير الضروري.", "Um princípio simples: minimizar o acesso desnecessário.", "Un principio semplice: ridurre al minimo gli accessi non necessari.", "Простой принцип: минимизировать ненужный доступ."),
  "The privacy model is easier to understand when the flow is explicit: establish who is accessing the platform, determine which workspace they are authorised to use, enforce that boundary at the data layer and expose only the information needed for the requested function.": landing(
    "Das Datenschutzmodell ist leichter verständlich, wenn der Ablauf klar ist: feststellen, wer auf die Plattform zugreift, bestimmen, welchen Arbeitsbereich diese Person nutzen darf, diese Grenze auf Datenebene durchsetzen und nur die Informationen bereitstellen, die für die angeforderte Funktion benötigt werden.",
    "El modelo de privacidad es más fácil de entender cuando el flujo es explícito: establecer quién accede a la plataforma, determinar qué espacio está autorizado a usar, aplicar ese límite en la capa de datos y exponer solo la información necesaria para la función solicitada.",
    "Modeli i privatësisë kuptohet më lehtë kur rrjedha është e qartë: përcakto kush po hyn në platformë, cilën hapësirë lejohet të përdorë, zbato atë kufi në shtresën e të dhënave dhe shfaq vetëm informacionin e nevojshëm për funksionin e kërkuar.",
    "يصبح نموذج الخصوصية أسهل فهمًا عندما يكون المسار واضحًا: تحديد من يصل إلى المنصة، وتحديد مساحة العمل المصرح له باستخدامها، وفرض هذا الحد في طبقة البيانات، وعرض المعلومات اللازمة فقط للوظيفة المطلوبة.",
    "O modelo de privacidade é mais fácil de compreender quando o fluxo é explícito: estabelecer quem acede à plataforma, determinar que espaço está autorizado a usar, aplicar esse limite na camada de dados e expor apenas a informação necessária para a função pedida.",
    "Il modello di privacy è più facile da capire quando il flusso è esplicito: stabilire chi accede alla piattaforma, determinare quale spazio è autorizzato a usare, applicare quel limite a livello dati ed esporre solo le informazioni necessarie per la funzione richiesta.",
    "Модель конфиденциальности проще понять при явном процессе: определить, кто получает доступ к платформе, какое пространство ему разрешено использовать, обеспечить эту границу на уровне данных и показывать только информацию, необходимую для запрошенной функции."
  ),
  "Authenticate": landing("Authentifizieren", "Autenticar", "Autentiko", "تحقق من الهوية", "Autenticar", "Autentica", "Аутентифицировать"),
  "Confirm the user identity before private financial records become available.": landing("Bestätige die Nutzeridentität, bevor private Finanzdaten verfügbar werden.", "Confirma la identidad del usuario antes de que los registros financieros privados estén disponibles.", "Konfirmo identitetin e përdoruesit para se të dhënat private financiare të bëhen të disponueshme.", "أكد هوية المستخدم قبل إتاحة السجلات المالية الخاصة.", "Confirme a identidade do utilizador antes de os registos financeiros privados ficarem disponíveis.", "Conferma l’identità dell’utente prima che i dati finanziari privati siano disponibili.", "Подтвердите личность пользователя до предоставления приватных финансовых записей."),
  "Authorise": landing("Autorisieren", "Autorizar", "Autorizo", "صرّح", "Autorizar", "Autorizza", "Авторизовать"),
  "Determine which workspace, role and records that identity is permitted to access.": landing("Bestimme, auf welchen Arbeitsbereich, welche Rolle und welche Datensätze diese Identität zugreifen darf.", "Determina a qué espacio, rol y registros puede acceder esa identidad.", "Përcakto cilën hapësirë, rol dhe të dhëna lejohet të aksesojë ai identitet.", "حدد مساحة العمل والدور والسجلات التي يُسمح لتلك الهوية بالوصول إليها.", "Determine a que espaço, função e registos essa identidade pode aceder.", "Determina a quale spazio, ruolo e dati può accedere quell’identità.", "Определите, к какому пространству, роли и записям разрешён доступ этой идентичности."),
  "Enforce": landing("Durchsetzen", "Aplicar", "Zbato", "طبّق", "Aplicar", "Applica", "Обеспечить"),
  "Apply access policies at the database and application layers rather than relying only on hidden interface elements.": landing("Wende Zugriffsrichtlinien auf Datenbank- und Anwendungsebene an, statt dich nur auf versteckte Oberflächenelemente zu verlassen.", "Aplica políticas de acceso en las capas de base de datos y aplicación en lugar de depender solo de elementos ocultos de la interfaz.", "Zbato politikat e qasjes në shtresat e databazës dhe aplikacionit, në vend që të mbështetesh vetëm te elementet e fshehura të ndërfaqes.", "طبّق سياسات الوصول في طبقتي قاعدة البيانات والتطبيق بدل الاعتماد فقط على عناصر واجهة مخفية.", "Aplique políticas de acesso nas camadas da base de dados e da aplicação em vez de depender apenas de elementos ocultos da interface.", "Applica le politiche di accesso a livello database e applicazione invece di affidarti solo a elementi nascosti dell’interfaccia.", "Применяйте политики доступа на уровне базы данных и приложения, а не полагайтесь только на скрытые элементы интерфейса."),
  "Present": landing("Bereitstellen", "Presentar", "Paraqit", "اعرض", "Apresentar", "Presenta", "Представить"),
  "Return the financial information needed for the user's current context without unnecessarily widening access.": landing("Stelle die Finanzinformationen bereit, die für den aktuellen Kontext des Nutzers benötigt werden, ohne den Zugriff unnötig auszuweiten.", "Devuelve la información financiera necesaria para el contexto actual del usuario sin ampliar innecesariamente el acceso.", "Kthe informacionin financiar të nevojshëm për kontekstin aktual të përdoruesit pa zgjeruar qasjen në mënyrë të panevojshme.", "أعد المعلومات المالية اللازمة لسياق المستخدم الحالي دون توسيع الوصول بلا حاجة.", "Devolva a informação financeira necessária para o contexto atual do utilizador sem alargar desnecessariamente o acesso.", "Restituisci le informazioni finanziarie necessarie per il contesto attuale dell’utente senza ampliare inutilmente l’accesso.", "Возвращайте финансовую информацию, необходимую для текущего контекста пользователя, не расширяя доступ без необходимости."),
  "Legal information": landing("Rechtliche Informationen", "Información legal", "Informacion ligjor", "معلومات قانونية", "Informação legal", "Informazioni legali", "Юридическая информация"),
  "Product privacy and legal privacy serve different purposes.": landing("Produktdatenschutz und rechtlicher Datenschutz erfüllen unterschiedliche Zwecke.", "La privacidad del producto y la privacidad legal cumplen funciones diferentes.", "Privatësia e produktit dhe privatësia ligjore shërbejnë qëllime të ndryshme.", "خصوصية المنتج والخصوصية القانونية تخدمان أغراضًا مختلفة.", "A privacidade do produto e a privacidade legal servem objetivos diferentes.", "La privacy del prodotto e quella legale hanno scopi diversi.", "Продуктовая и юридическая конфиденциальность служат разным целям."),
  "This page explains the product principles behind FICONTER's approach to privacy and trust. The formal Privacy Policy, legal disclosures and data-protection information remain available separately through the Legal section of the website.": landing(
    "Diese Seite erklärt die Produktprinzipien hinter FICONTERs Ansatz zu Datenschutz und Vertrauen. Die formelle Datenschutzerklärung, rechtliche Hinweise und Datenschutzinformationen bleiben separat im Bereich „Rechtliches“ der Website verfügbar.",
    "Esta página explica los principios de producto detrás del enfoque de FICONTER sobre privacidad y confianza. La Política de Privacidad formal, las divulgaciones legales y la información de protección de datos siguen disponibles por separado en la sección Legal del sitio.",
    "Kjo faqe shpjegon parimet e produktit pas qasjes së FICONTER ndaj privatësisë dhe besimit. Politika zyrtare e Privatësisë, njoftimet ligjore dhe informacioni për mbrojtjen e të dhënave mbeten të disponueshme veçmas te seksioni Ligjor i faqes.",
    "تشرح هذه الصفحة مبادئ المنتج وراء نهج FICONTER في الخصوصية والثقة. تبقى سياسة الخصوصية الرسمية والإفصاحات القانونية ومعلومات حماية البيانات متاحة بشكل منفصل عبر القسم القانوني من الموقع.",
    "Esta página explica os princípios do produto por detrás da abordagem da FICONTER à privacidade e confiança. A Política de Privacidade formal, os avisos legais e a informação de proteção de dados continuam disponíveis separadamente na secção Legal do site.",
    "Questa pagina spiega i principi di prodotto alla base dell’approccio di FICONTER a privacy e fiducia. L’Informativa sulla privacy formale, le comunicazioni legali e le informazioni sulla protezione dei dati restano disponibili separatamente nella sezione Legale del sito.",
    "Эта страница объясняет продуктовые принципы подхода FICONTER к конфиденциальности и доверию. Формальная Политика конфиденциальности, юридические раскрытия и информация о защите данных остаются отдельно доступными в разделе правовой информации сайта."
  ),
};

Object.assign(LANDING_UI_TRANSLATIONS, PUBLIC_PRIVACY_TRANSLATIONS);
