import type { FiconterLanguage } from "./config";
import { PHRASE_TRANSLATIONS } from "./phrases";
import "./publicFaqAboutCatalog";
import "./publicFaqHowCatalog";
import "./publicFaqIntelligenceCatalog";
import "./publicFaqSavingsBusinessCatalog";
import "./publicFaqPrivacyAccessCatalog";

type L = Exclude<FiconterLanguage, "en">;
type Row = Record<L, string>;
const r = (de: string, es: string, sq: string, ar: string, pt: string, it: string, ru: string): Row => ({ de, es, sq, ar, pt, it, ru });

const PUBLIC_FAQ_SHELL_TRANSLATIONS: Record<string, Row> = {
  "FICONTER FAQ": r("FICONTER FAQ", "FAQ DE FICONTER", "FAQ E FICONTER", "أسئلة FICONTER الشائعة", "FAQ FICONTER", "FAQ FICONTER", "FAQ FICONTER"),
  "Questions worth answering clearly.": r("Fragen, die klare Antworten verdienen.", "Preguntas que merecen respuestas claras.", "Pyetje që meritojnë përgjigje të qarta.", "أسئلة تستحق إجابات واضحة.", "Perguntas que merecem respostas claras.", "Domande che meritano risposte chiare.", "Вопросы, на которые стоит отвечать ясно."),
  "Straightforward answers about how FICONTER works, what it is designed to do, how financial information is handled and where the platform draws its boundaries.": r("Klare Antworten dazu, wie FICONTER funktioniert, wofür es entwickelt wurde, wie Finanzinformationen verarbeitet werden und wo die Grenzen der Plattform liegen.", "Respuestas directas sobre cómo funciona FICONTER, para qué está diseñado, cómo se trata la información financiera y dónde están los límites de la plataforma.", "Përgjigje të drejtpërdrejta për mënyrën si funksionon FICONTER, për çfarë është krijuar, si trajtohet informacioni financiar dhe ku vendosen kufijtë e platformës.", "إجابات مباشرة حول كيفية عمل FICONTER وما صُممت للقيام به وكيف تُعالج المعلومات المالية وأين تضع المنصة حدودها.", "Respostas diretas sobre como funciona a FICONTER, para que foi concebida, como é tratada a informação financeira e onde estão os limites da plataforma.", "Risposte dirette su come funziona FICONTER, cosa è progettato per fare, come vengono gestite le informazioni finanziarie e dove si collocano i limiti della piattaforma.", "Прямые ответы о том, как работает FICONTER, для чего он создан, как обрабатывается финансовая информация и где проходят границы платформы."),
  "Start free": r("Kostenlos starten", "Empezar gratis", "Fillo falas", "ابدأ مجانًا", "Começar gratuitamente", "Inizia gratis", "Начать бесплатно"),
  "About FICONTER": r("Über FICONTER", "Acerca de FICONTER", "Rreth FICONTER", "حول FICONTER", "Sobre a FICONTER", "Informazioni su FICONTER", "О FICONTER"),
  "Clear answers": r("Klare Antworten", "Respuestas claras", "Përgjigje të qarta", "إجابات واضحة", "Respostas claras", "Risposte chiare", "Понятные ответы"),
  "Know what FICONTER does before you rely on it.": r("Verstehe, was FICONTER tut, bevor du dich darauf verlässt.", "Conoce lo que hace FICONTER antes de confiar en él.", "Kupto çfarë bën FICONTER përpara se të mbështetesh tek ai.", "اعرف ما الذي تفعله FICONTER قبل الاعتماد عليها.", "Saiba o que a FICONTER faz antes de confiar nela.", "Scopri cosa fa FICONTER prima di affidarti ad esso.", "Поймите, что делает FICONTER, прежде чем на него полагаться."),
  "questions": r("Fragen", "preguntas", "pyetje", "أسئلة", "perguntas", "domande", "вопросов"),
  "topics": r("Themen", "temas", "tema", "موضوعات", "temas", "argomenti", "тем"),
  "clear reference": r("klare Referenz", "referencia clara", "referencë e qartë", "مرجع واضح", "referência clara", "riferimento chiaro", "понятный справочник"),
  "Includes direct answers to common concerns about privacy, bank access and business use.": r("Enthält direkte Antworten auf häufige Fragen zu Datenschutz, Bankzugriff und geschäftlicher Nutzung.", "Incluye respuestas directas a inquietudes comunes sobre privacidad, acceso bancario y uso empresarial.", "Përfshin përgjigje të drejtpërdrejta për shqetësime të zakonshme rreth privatësisë, qasjes bankare dhe përdorimit për biznes.", "يتضمن إجابات مباشرة عن المخاوف الشائعة بشأن الخصوصية والوصول البنكي واستخدام الأعمال.", "Inclui respostas diretas a preocupações comuns sobre privacidade, acesso bancário e utilização empresarial.", "Include risposte dirette ai dubbi comuni su privacy, accesso bancario e uso aziendale.", "Содержит прямые ответы на частые вопросы о конфиденциальности, доступе к банку и использовании для бизнеса."),
  "Browse by topic": r("Nach Thema durchsuchen", "Explorar por tema", "Shfleto sipas temës", "تصفح حسب الموضوع", "Explorar por tema", "Sfoglia per argomento", "Просмотреть по темам"),
  "Find the part of FICONTER you want to understand.": r("Finde den Bereich von FICONTER, den du verstehen möchtest.", "Encuentra la parte de FICONTER que quieres comprender.", "Gjej pjesën e FICONTER që dëshiron të kuptosh.", "اعثر على الجزء من FICONTER الذي تريد فهمه.", "Encontre a parte da FICONTER que pretende compreender.", "Trova la parte di FICONTER che vuoi comprendere.", "Найдите ту часть FICONTER, которую хотите понять."),
  "Choose a topic to jump directly to its questions.": r("Wähle ein Thema, um direkt zu den zugehörigen Fragen zu springen.", "Elige un tema para ir directamente a sus preguntas.", "Zgjidh një temë për të kaluar drejtpërdrejt te pyetjet e saj.", "اختر موضوعًا للانتقال مباشرة إلى أسئلته.", "Escolha um tema para ir diretamente às respetivas perguntas.", "Scegli un argomento per passare direttamente alle relative domande.", "Выберите тему, чтобы сразу перейти к её вопросам."),
  "FAQ topics": r("FAQ-Themen", "Temas de FAQ", "Temat e FAQ", "موضوعات الأسئلة الشائعة", "Temas das FAQ", "Argomenti FAQ", "Темы FAQ"),
  "Answers": r("Antworten", "Respuestas", "Përgjigje", "إجابات", "Respostas", "Risposte", "Ответы"),
  "Frequently asked questions.": r("Häufig gestellte Fragen.", "Preguntas frecuentes.", "Pyetje të shpeshta.", "الأسئلة الشائعة.", "Perguntas frequentes.", "Domande frequenti.", "Часто задаваемые вопросы."),
  "Open any question to read the full answer. You can keep more than one answer open while comparing topics.": r("Öffne eine Frage, um die vollständige Antwort zu lesen. Beim Vergleichen von Themen kannst du mehrere Antworten gleichzeitig geöffnet lassen.", "Abre cualquier pregunta para leer la respuesta completa. Puedes mantener varias respuestas abiertas mientras comparas temas.", "Hap çdo pyetje për të lexuar përgjigjen e plotë. Mund të mbash më shumë se një përgjigje të hapur ndërsa krahason temat.", "افتح أي سؤال لقراءة الإجابة كاملة. يمكنك إبقاء أكثر من إجابة مفتوحة أثناء مقارنة الموضوعات.", "Abra qualquer pergunta para ler a resposta completa. Pode manter mais do que uma resposta aberta enquanto compara temas.", "Apri una domanda per leggere la risposta completa. Puoi tenere aperta più di una risposta mentre confronti gli argomenti.", "Откройте любой вопрос, чтобы прочитать полный ответ. При сравнении тем можно держать открытыми несколько ответов."),
  "Financial Control Center": r("Finanzkontrollzentrum", "Centro de Control Financiero", "Qendra e Kontrollit Financiar", "مركز التحكم المالي", "Centro de Controlo Financeiro", "Centro di Controllo Finanziario", "Центр финансового контроля"),
  "Understand the platform. Then decide if it fits the way you manage money.": r("Verstehe die Plattform. Entscheide dann, ob sie zu deiner Art der Geldverwaltung passt.", "Entiende la plataforma. Después decide si encaja con tu forma de gestionar el dinero.", "Kupto platformën. Pastaj vendos nëse përshtatet me mënyrën si menaxhon paratë.", "افهم المنصة، ثم قرر إن كانت تناسب طريقتك في إدارة المال.", "Compreenda a plataforma. Depois decida se se adapta à forma como gere o dinheiro.", "Comprendi la piattaforma. Poi decidi se si adatta al tuo modo di gestire il denaro.", "Разберитесь в платформе, а затем решите, подходит ли она вашему способу управления деньгами."),
  "Start with a private workspace and build a clearer structure around the financial life you are managing.": r("Beginne mit einem privaten Arbeitsbereich und schaffe eine klarere Struktur für dein finanzielles Leben.", "Empieza con un espacio privado y crea una estructura más clara para la vida financiera que gestionas.", "Fillo me një hapësirë private dhe ndërto një strukturë më të qartë rreth jetës financiare që po menaxhon.", "ابدأ بمساحة عمل خاصة وابنِ هيكلًا أوضح حول حياتك المالية.", "Comece com um espaço privado e construa uma estrutura mais clara em torno da vida financeira que gere.", "Inizia con uno spazio privato e costruisci una struttura più chiara attorno alla vita finanziaria che gestisci.", "Начните с приватного пространства и выстройте более понятную структуру вокруг своих финансов."),
  "Create your account": r("Konto erstellen", "Crear tu cuenta", "Krijo llogarinë", "أنشئ حسابك", "Criar a sua conta", "Crea il tuo account", "Создать аккаунт"),
  "Log in": r("Anmelden", "Iniciar sesión", "Hyr", "تسجيل الدخول", "Iniciar sessão", "Accedi", "Войти"),

  "How it works": r("So funktioniert es", "Cómo funciona", "Si funksionon", "كيف تعمل", "Como funciona", "Come funziona", "Как это работает"),
  "Financial intelligence": r("Finanzintelligenz", "Inteligencia financiera", "Inteligjenca financiare", "الذكاء المالي", "Inteligência financeira", "Intelligenza finanziaria", "Финансовая аналитика"),
  "Savings, debt & credit": r("Sparen, Schulden & Kredit", "Ahorros, deuda y crédito", "Kursime, borxhe & kredi", "الادخار والديون والائتمان", "Poupanças, dívida e crédito", "Risparmi, debiti e credito", "Сбережения, долги и кредит"),
  "Privacy & security": r("Datenschutz & Sicherheit", "Privacidad y seguridad", "Privatësia & siguria", "الخصوصية والأمان", "Privacidade e segurança", "Privacy e sicurezza", "Конфиденциальность и безопасность"),
  "Access & support": r("Zugang & Support", "Acceso y soporte", "Qasje & mbështetje", "الوصول والدعم", "Acesso e suporte", "Accesso e assistenza", "Доступ и поддержка"),
  "What FICONTER is, who it is for and how it is positioned.": r("Was FICONTER ist, für wen es gedacht ist und wie es positioniert ist.", "Qué es FICONTER, para quién está diseñado y cómo se posiciona.", "Çfarë është FICONTER, për kë është dhe si pozicionohet.", "ما هي FICONTER ولمن صُممت وكيف تتموضع.", "O que é a FICONTER, para quem se destina e como se posiciona.", "Cos'è FICONTER, a chi si rivolge e come si posiziona.", "Что такое FICONTER, для кого он предназначен и как позиционируется."),
  "Bank connections, user control, monthly planning and core financial records.": r("Bankverbindungen, Nutzerkontrolle, Monatsplanung und grundlegende Finanzdaten.", "Conexiones bancarias, control del usuario, planificación mensual y registros financieros básicos.", "Lidhjet bankare, kontrolli i përdoruesit, planifikimi mujor dhe regjistrimet bazë financiare.", "الاتصالات البنكية وتحكم المستخدم والتخطيط الشهري والسجلات المالية الأساسية.", "Ligações bancárias, controlo do utilizador, planeamento mensal e registos financeiros essenciais.", "Connessioni bancarie, controllo dell'utente, pianificazione mensile e registri finanziari fondamentali.", "Банковские подключения, контроль пользователя, ежемесячное планирование и основные финансовые записи."),
  "Financial Health, Smart Insights and decision-support features.": r("Financial Health, Smart Insights und Funktionen zur Entscheidungsunterstützung.", "Financial Health, Smart Insights y funciones de apoyo a decisiones.", "Financial Health, Smart Insights dhe veçoritë e mbështetjes së vendimeve.", "Financial Health وSmart Insights وميزات دعم القرار.", "Financial Health, Smart Insights e funcionalidades de apoio à decisão.", "Financial Health, Smart Insights e funzioni di supporto alle decisioni.", "Financial Health, Smart Insights и функции поддержки решений."),
  "Goals, debt management and credit-card tracking.": r("Ziele, Schuldenmanagement und Kreditkartenverfolgung.", "Objetivos, gestión de deuda y seguimiento de tarjetas de crédito.", "Objektivat, menaxhimi i borxhit dhe gjurmimi i kartave të kreditit.", "الأهداف وإدارة الديون وتتبع بطاقات الائتمان.", "Objetivos, gestão de dívida e acompanhamento de cartões de crédito.", "Obiettivi, gestione dei debiti e monitoraggio delle carte di credito.", "Цели, управление долгами и отслеживание кредитных карт."),
  "Business workspaces, separation of records and accounting boundaries.": r("Geschäftliche Arbeitsbereiche, Trennung von Datensätzen und Abgrenzung zur Buchhaltung.", "Espacios empresariales, separación de registros y límites contables.", "Hapësirat e biznesit, ndarja e regjistrimeve dhe kufijtë e kontabilitetit.", "مساحات عمل الأعمال وفصل السجلات وحدود المحاسبة.", "Espaços empresariais, separação de registos e limites contabilísticos.", "Spazi aziendali, separazione dei record e confini contabili.", "Деловые пространства, разделение записей и границы бухгалтерского учёта."),
  "Data control, account boundaries and trust.": r("Datenkontrolle, Kontogrenzen und Vertrauen.", "Control de datos, límites de cuenta y confianza.", "Kontrolli i të dhënave, kufijtë e llogarisë dhe besimi.", "التحكم في البيانات وحدود الحساب والثقة.", "Controlo de dados, limites da conta e confiança.", "Controllo dei dati, confini dell'account e fiducia.", "Контроль данных, границы аккаунта и доверие."),
  "Devices, currencies, languages, product development and support.": r("Geräte, Währungen, Sprachen, Produktentwicklung und Support.", "Dispositivos, monedas, idiomas, desarrollo del producto y soporte.", "Pajisjet, monedhat, gjuhët, zhvillimi i produktit dhe mbështetja.", "الأجهزة والعملات واللغات وتطوير المنتج والدعم.", "Dispositivos, moedas, idiomas, desenvolvimento do produto e suporte.", "Dispositivi, valute, lingue, sviluppo del prodotto e assistenza.", "Устройства, валюты, языки, развитие продукта и поддержка."),
};

Object.assign(PHRASE_TRANSLATIONS, PUBLIC_FAQ_SHELL_TRANSLATIONS);
