import type { FiconterLanguage } from "./config";
import { PHRASE_TRANSLATIONS } from "./phrases";

type L = Exclude<FiconterLanguage, "en">;
type Row = Record<L, string>;
const r = (de: string, es: string, sq: string, ar: string, pt: string, it: string, ru: string): Row => ({ de, es, sq, ar, pt, it, ru });

const PUBLIC_HELP_TRANSLATIONS: Record<string, Row> = {
  "Understand the platform": r("Die Plattform verstehen", "Entender la plataforma", "Kupto platformën", "فهم المنصة", "Compreender a plataforma", "Comprendere la piattaforma", "Понять платформу"),
  "See how personal and business workspaces, planning, wealth and financial intelligence fit together.": r("Sieh, wie private und geschäftliche Arbeitsbereiche, Planung, Vermögen und Finanzintelligenz zusammenspielen.", "Descubre cómo encajan los espacios personales y empresariales, la planificación, el patrimonio y la inteligencia financiera.", "Shih si lidhen hapësirat personale dhe të biznesit, planifikimi, pasuria dhe inteligjenca financiare.", "تعرّف على كيفية تكامل مساحات العمل الشخصية والتجارية والتخطيط والثروة والذكاء المالي.", "Veja como os espaços pessoais e empresariais, o planeamento, o património e a inteligência financeira funcionam em conjunto.", "Scopri come si integrano spazi personali e aziendali, pianificazione, patrimonio e intelligenza finanziaria.", "Посмотрите, как связаны личное и деловое пространства, планирование, капитал и финансовая аналитика."),
  "Read the full FAQ": r("Die vollständigen FAQ lesen", "Leer las FAQ completas", "Lexo FAQ-në e plotë", "قراءة الأسئلة الشائعة كاملة", "Ler as FAQ completas", "Leggi le FAQ complete", "Прочитать все FAQ"),
  "Browse direct answers about how FICONTER works, privacy, business use, account access and platform boundaries.": r("Lies direkte Antworten zur Funktionsweise von FICONTER, zu Datenschutz, geschäftlicher Nutzung, Kontozugriff und den Grenzen der Plattform.", "Consulta respuestas directas sobre cómo funciona FICONTER, privacidad, uso empresarial, acceso a la cuenta y límites de la plataforma.", "Shfleto përgjigje të drejtpërdrejta për mënyrën si funksionon FICONTER, privatësinë, përdorimin për biznes, qasjen në llogari dhe kufijtë e platformës.", "اطّلع على إجابات مباشرة حول كيفية عمل FICONTER والخصوصية واستخدام الأعمال والوصول إلى الحساب وحدود المنصة.", "Consulte respostas diretas sobre o funcionamento da FICONTER, privacidade, utilização empresarial, acesso à conta e limites da plataforma.", "Consulta risposte dirette su come funziona FICONTER, privacy, uso aziendale, accesso all'account e limiti della piattaforma.", "Посмотрите прямые ответы о работе FICONTER, конфиденциальности, использовании для бизнеса, доступе к аккаунту и границах платформы."),
  "Open FAQ": r("FAQ öffnen", "Abrir FAQ", "Hap FAQ-në", "فتح الأسئلة الشائعة", "Abrir FAQ", "Apri FAQ", "Открыть FAQ"),
  "Privacy and security": r("Datenschutz und Sicherheit", "Privacidad y seguridad", "Privatësia dhe siguria", "الخصوصية والأمان", "Privacidade e segurança", "Privacy e sicurezza", "Конфиденциальность и безопасность"),
  "Review FICONTER's privacy principles, workspace isolation, data control and security architecture.": r("Prüfe FICONTERs Datenschutzprinzipien, die Trennung von Arbeitsbereichen, Datenkontrolle und Sicherheitsarchitektur.", "Revisa los principios de privacidad de FICONTER, el aislamiento de espacios, el control de datos y la arquitectura de seguridad.", "Shqyrto parimet e privatësisë së FICONTER, izolimin e hapësirave, kontrollin e të dhënave dhe arkitekturën e sigurisë.", "راجع مبادئ الخصوصية في FICONTER وعزل مساحات العمل والتحكم في البيانات وبنية الأمان.", "Reveja os princípios de privacidade da FICONTER, o isolamento dos espaços, o controlo de dados e a arquitetura de segurança.", "Esamina i principi di privacy di FICONTER, l'isolamento degli spazi, il controllo dei dati e l'architettura di sicurezza.", "Изучите принципы конфиденциальности FICONTER, изоляцию пространств, контроль данных и архитектуру безопасности."),
  "View privacy & trust": r("Datenschutz & Vertrauen ansehen", "Ver privacidad y confianza", "Shiko privatësinë & besimin", "عرض الخصوصية والثقة", "Ver privacidade e confiança", "Vedi privacy e fiducia", "Открыть раздел конфиденциальности и доверия"),
  "Account access": r("Kontozugriff", "Acceso a la cuenta", "Qasja në llogari", "الوصول إلى الحساب", "Acesso à conta", "Accesso all'account", "Доступ к аккаунту"),
  "Log in to your workspace, recover account access or continue into the private Help Center after authentication.": r("Melde dich in deinem Arbeitsbereich an, stelle den Kontozugriff wieder her oder gehe nach der Authentifizierung zum privaten Help Center.", "Inicia sesión en tu espacio, recupera el acceso a tu cuenta o continúa al Centro de Ayuda privado después de autenticarte.", "Hyr në hapësirën tënde, rikthe qasjen në llogari ose vazhdo te Qendra private e Ndihmës pas autentikimit.", "سجّل الدخول إلى مساحة عملك أو استعد الوصول إلى حسابك أو انتقل إلى مركز المساعدة الخاص بعد المصادقة.", "Inicie sessão no seu espaço, recupere o acesso à conta ou continue para o Centro de Ajuda privado após a autenticação.", "Accedi al tuo spazio, recupera l'accesso all'account o prosegui nel Centro assistenza privato dopo l'autenticazione.", "Войдите в рабочее пространство, восстановите доступ к аккаунту или после аутентификации перейдите в приватный Центр помощи."),
  "Go to account access": r("Zum Kontozugriff", "Ir al acceso de cuenta", "Shko te qasja në llogari", "الانتقال إلى الوصول للحساب", "Ir para o acesso à conta", "Vai all'accesso account", "Перейти к доступу к аккаунту"),
  "Getting started": r("Erste Schritte", "Primeros pasos", "Fillimi", "البدء", "Primeiros passos", "Per iniziare", "Начало работы"),
  "Create an account and choose the workspace you want to use.": r("Erstelle ein Konto und wähle den Arbeitsbereich, den du verwenden möchtest.", "Crea una cuenta y elige el espacio que quieres usar.", "Krijo një llogari dhe zgjidh hapësirën që dëshiron të përdorësh.", "أنشئ حسابًا واختر مساحة العمل التي تريد استخدامها.", "Crie uma conta e escolha o espaço que pretende utilizar.", "Crea un account e scegli lo spazio che vuoi utilizzare.", "Создайте аккаунт и выберите рабочее пространство."),
  "Start with your core financial records before relying on scores or projections.": r("Beginne mit deinen grundlegenden Finanzdaten, bevor du dich auf Bewertungen oder Prognosen verlässt.", "Empieza con tus registros financieros básicos antes de confiar en puntuaciones o proyecciones.", "Fillo me regjistrimet bazë financiare përpara se të mbështetesh te pikët ose projeksionet.", "ابدأ بسجلاتك المالية الأساسية قبل الاعتماد على الدرجات أو التوقعات.", "Comece pelos seus registos financeiros essenciais antes de confiar em pontuações ou projeções.", "Parti dai dati finanziari fondamentali prima di affidarti a punteggi o proiezioni.", "Сначала заполните основные финансовые данные, прежде чем полагаться на оценки или прогнозы."),
  "Use the Personal and Business areas as separate contexts for separate records.": r("Nutze die Bereiche Privat und Geschäftlich als getrennte Kontexte für getrennte Datensätze.", "Usa las áreas Personal y Empresa como contextos separados para registros separados.", "Përdor zonat Personale dhe Biznes si kontekste të ndara për regjistrime të ndara.", "استخدم منطقتي الشخصي والأعمال كسياقين منفصلين لسجلات منفصلة.", "Use as áreas Pessoal e Empresa como contextos separados para registos separados.", "Usa le aree Personale e Business come contesti distinti per record separati.", "Используйте личную и деловую области как отдельные контексты для разных записей."),
  "Managing money": r("Geld verwalten", "Gestionar el dinero", "Menaxhimi i parave", "إدارة المال", "Gerir dinheiro", "Gestire il denaro", "Управление деньгами"),
  "Transactions are the foundation for income and expense activity.": r("Transaktionen sind die Grundlage für Einnahmen- und Ausgabenaktivitäten.", "Las transacciones son la base de la actividad de ingresos y gastos.", "Transaksionet janë baza e aktivitetit të të ardhurave dhe shpenzimeve.", "المعاملات هي أساس نشاط الدخل والمصروفات.", "As transações são a base da atividade de rendimentos e despesas.", "Le transazioni sono la base delle attività di entrata e spesa.", "Транзакции — основа учёта доходов и расходов."),
  "Bills, debt payments, savings and goals should be recorded in their dedicated modules.": r("Rechnungen, Schuldenzahlungen, Sparen und Ziele sollten in den dafür vorgesehenen Modulen erfasst werden.", "Las facturas, pagos de deuda, ahorros y objetivos deben registrarse en sus módulos específicos.", "Faturat, pagesat e borxheve, kursimet dhe objektivat duhet të regjistrohen në modulet e tyre përkatëse.", "يجب تسجيل الفواتير ومدفوعات الديون والادخار والأهداف في وحداتها المخصصة.", "Contas, pagamentos de dívida, poupanças e objetivos devem ser registados nos respetivos módulos.", "Bollette, pagamenti dei debiti, risparmi e obiettivi vanno registrati nei rispettivi moduli.", "Счета, платежи по долгам, сбережения и цели следует записывать в соответствующих модулях."),
  "Connected views can update when the same financial movement affects more than one module.": r("Verknüpfte Ansichten können aktualisiert werden, wenn dieselbe Finanzbewegung mehr als ein Modul betrifft.", "Las vistas conectadas pueden actualizarse cuando el mismo movimiento financiero afecta a más de un módulo.", "Pamjet e lidhura mund të përditësohen kur e njëjta lëvizje financiare ndikon në më shumë se një modul.", "يمكن أن تتحدث العروض المرتبطة عندما تؤثر الحركة المالية نفسها في أكثر من وحدة.", "As vistas associadas podem ser atualizadas quando o mesmo movimento financeiro afeta mais do que um módulo.", "Le viste collegate possono aggiornarsi quando lo stesso movimento finanziario interessa più di un modulo.", "Связанные представления могут обновляться, когда одно финансовое движение затрагивает несколько модулей."),
  "Using financial intelligence": r("Finanzintelligenz nutzen", "Usar la inteligencia financiera", "Përdorimi i inteligjencës financiare", "استخدام الذكاء المالي", "Utilizar inteligência financeira", "Usare l'intelligenza finanziaria", "Использование финансовой аналитики"),
  "Scores and insights depend on the financial data available in your workspace.": r("Bewertungen und Einblicke hängen von den Finanzdaten ab, die in deinem Arbeitsbereich verfügbar sind.", "Las puntuaciones y análisis dependen de los datos financieros disponibles en tu espacio.", "Pikët dhe analizat varen nga të dhënat financiare që gjenden në hapësirën tënde.", "تعتمد الدرجات والرؤى على البيانات المالية المتاحة في مساحة عملك.", "As pontuações e análises dependem dos dados financeiros disponíveis no seu espaço.", "Punteggi e analisi dipendono dai dati finanziari disponibili nel tuo spazio.", "Оценки и выводы зависят от финансовых данных в вашем рабочем пространстве."),
  "An empty or incomplete account may remain Not assessed instead of receiving a misleading score.": r("Ein leeres oder unvollständiges Konto kann als Nicht bewertet verbleiben, statt eine irreführende Bewertung zu erhalten.", "Una cuenta vacía o incompleta puede permanecer como No evaluada en lugar de recibir una puntuación engañosa.", "Një llogari bosh ose e paplotë mund të mbetet E pavlerësuar në vend që të marrë një pikë mashtruese.", "قد يبقى الحساب الفارغ أو غير المكتمل غير مقيّم بدلًا من الحصول على درجة مضللة.", "Uma conta vazia ou incompleta pode permanecer Não avaliada em vez de receber uma pontuação enganadora.", "Un account vuoto o incompleto può rimanere Non valutato invece di ricevere un punteggio fuorviante.", "Пустой или неполный аккаунт может оставаться «Не оценено», чтобы не показывать вводящую в заблуждение оценку."),
  "FICONTER guidance supports financial organization and decision-making; it does not replace regulated professional advice.": r("FICONTER unterstützt finanzielle Organisation und Entscheidungen; es ersetzt keine regulierte professionelle Beratung.", "La orientación de FICONTER apoya la organización y la toma de decisiones financieras; no sustituye el asesoramiento profesional regulado.", "Udhëzimi i FICONTER mbështet organizimin dhe vendimmarrjen financiare; nuk zëvendëson këshillimin profesional të rregulluar.", "تدعم إرشادات FICONTER التنظيم واتخاذ القرارات المالية؛ ولا تحل محل المشورة المهنية الخاضعة للتنظيم.", "A orientação da FICONTER apoia a organização e a tomada de decisões financeiras; não substitui aconselhamento profissional regulado.", "Le indicazioni di FICONTER supportano l'organizzazione e le decisioni finanziarie; non sostituiscono una consulenza professionale regolamentata.", "Рекомендации FICONTER помогают организовать финансы и принимать решения, но не заменяют регулируемую профессиональную консультацию."),
  "FICONTER HELP": r("FICONTER HILFE", "AYUDA FICONTER", "NDIHMA FICONTER", "مساعدة FICONTER", "AJUDA FICONTER", "ASSISTENZA FICONTER", "ПОМОЩЬ FICONTER"),
  "Help should be available before you ever need to log in.": r("Hilfe sollte verfügbar sein, bevor du dich überhaupt anmelden musst.", "La ayuda debe estar disponible incluso antes de iniciar sesión.", "Ndihma duhet të jetë e disponueshme përpara se të kesh nevojë të hysh.", "ينبغي أن تكون المساعدة متاحة قبل أن تحتاج حتى إلى تسجيل الدخول.", "A ajuda deve estar disponível antes de precisar sequer de iniciar sessão.", "L'assistenza dovrebbe essere disponibile prima ancora di dover accedere.", "Помощь должна быть доступна ещё до того, как вам потребуется войти."),
  "Use this public Help Center to understand the platform, find common answers, review privacy and security information, and reach the right account-access path.": r("Nutze dieses öffentliche Help Center, um die Plattform zu verstehen, häufige Antworten zu finden, Datenschutz- und Sicherheitsinformationen zu prüfen und den richtigen Weg zum Kontozugriff zu erreichen.", "Usa este Centro de Ayuda público para entender la plataforma, encontrar respuestas comunes, revisar información de privacidad y seguridad y acceder a la ruta correcta de tu cuenta.", "Përdor këtë Qendër publike të Ndihmës për të kuptuar platformën, për të gjetur përgjigje të zakonshme, për të shqyrtuar privatësinë dhe sigurinë dhe për të gjetur rrugën e duhur për qasjen në llogari.", "استخدم مركز المساعدة العام هذا لفهم المنصة والعثور على الإجابات الشائعة ومراجعة معلومات الخصوصية والأمان والوصول إلى المسار الصحيح للحساب.", "Use este Centro de Ajuda público para compreender a plataforma, encontrar respostas comuns, rever informações de privacidade e segurança e chegar ao percurso correto de acesso à conta.", "Usa questo Centro assistenza pubblico per comprendere la piattaforma, trovare risposte comuni, consultare privacy e sicurezza e raggiungere il percorso corretto per l'accesso all'account.", "Используйте этот публичный Центр помощи, чтобы понять платформу, найти ответы на частые вопросы, изучить конфиденциальность и безопасность и выбрать нужный путь доступа к аккаунту."),
  "Browse FAQ": r("FAQ durchsuchen", "Explorar FAQ", "Shfleto FAQ-në", "تصفح الأسئلة الشائعة", "Consultar FAQ", "Sfoglia FAQ", "Просмотреть FAQ"),
  "Explore FICONTER": r("FICONTER entdecken", "Explorar FICONTER", "Eksploro FICONTER", "استكشف FICONTER", "Explorar FICONTER", "Esplora FICONTER", "Изучить FICONTER"),
  "PUBLIC RESOURCE": r("ÖFFENTLICHE RESSOURCE", "RECURSO PÚBLICO", "BURIM PUBLIK", "مورد عام", "RECURSO PÚBLICO", "RISORSA PUBBLICA", "ПУБЛИЧНЫЙ РЕСУРС"),
  "Available to visitors, customers and anyone evaluating FICONTER.": r("Verfügbar für Besucher, Kunden und alle, die FICONTER bewerten.", "Disponible para visitantes, clientes y cualquier persona que evalúe FICONTER.", "E disponueshme për vizitorët, klientët dhe këdo që po vlerëson FICONTER.", "متاح للزوار والعملاء ولكل من يقيّم FICONTER.", "Disponível para visitantes, clientes e qualquer pessoa que esteja a avaliar a FICONTER.", "Disponibile per visitatori, clienti e chiunque stia valutando FICONTER.", "Доступно посетителям, клиентам и всем, кто оценивает FICONTER."),
  "Account-specific support stays private after sign-in, while general product help remains open to everyone.": r("Kontospezifischer Support bleibt nach der Anmeldung privat, während allgemeine Produkthilfe für alle offen bleibt.", "El soporte específico de la cuenta permanece privado después de iniciar sesión, mientras que la ayuda general del producto sigue abierta a todos.", "Mbështetja specifike për llogarinë mbetet private pas hyrjes, ndërsa ndihma e përgjithshme e produktit mbetet e hapur për të gjithë.", "يبقى الدعم الخاص بالحساب سريًا بعد تسجيل الدخول، بينما تظل مساعدة المنتج العامة متاحة للجميع.", "O suporte específico da conta permanece privado após o início de sessão, enquanto a ajuda geral do produto continua aberta a todos.", "L'assistenza specifica dell'account resta privata dopo l'accesso, mentre l'aiuto generale sul prodotto rimane aperto a tutti.", "Поддержка по конкретному аккаунту остаётся приватной после входа, а общая помощь по продукту доступна всем."),
  "FIND THE RIGHT PLACE": r("DEN RICHTIGEN ORT FINDEN", "ENCUENTRA EL LUGAR ADECUADO", "GJEJ VENDIN E DUHUR", "اعثر على المكان المناسب", "ENCONTRE O LOCAL CERTO", "TROVA IL POSTO GIUSTO", "НАЙДИТЕ НУЖНЫЙ РАЗДЕЛ"),
  "Choose what you need help with.": r("Wähle, wobei du Hilfe brauchst.", "Elige con qué necesitas ayuda.", "Zgjidh për çfarë të duhet ndihmë.", "اختر ما تحتاج المساعدة بشأنه.", "Escolha aquilo em que precisa de ajuda.", "Scegli per cosa ti serve aiuto.", "Выберите, с чем вам нужна помощь."),
  "Public guidance and private account support serve different purposes. These paths keep each request in the right place.": r("Öffentliche Orientierung und privater Kontosupport erfüllen unterschiedliche Zwecke. Diese Wege bringen jede Anfrage an die richtige Stelle.", "La orientación pública y el soporte privado de cuenta tienen fines distintos. Estas rutas mantienen cada solicitud en el lugar adecuado.", "Udhëzimi publik dhe mbështetja private e llogarisë kanë qëllime të ndryshme. Këto rrugë e çojnë çdo kërkesë në vendin e duhur.", "للإرشاد العام ودعم الحساب الخاص أغراض مختلفة. هذه المسارات توجّه كل طلب إلى المكان المناسب.", "A orientação pública e o suporte privado da conta têm finalidades diferentes. Estes caminhos mantêm cada pedido no local certo.", "La guida pubblica e l'assistenza privata dell'account hanno scopi diversi. Questi percorsi indirizzano ogni richiesta nel posto giusto.", "Публичные материалы и приватная поддержка аккаунта решают разные задачи. Эти пути направляют каждый запрос в нужное место."),
  "PRODUCT GUIDANCE": r("PRODUKTHINWEISE", "GUÍA DEL PRODUCTO", "UDHËZIME PËR PRODUKTIN", "إرشادات المنتج", "ORIENTAÇÃO DO PRODUTO", "GUIDA AL PRODOTTO", "РУКОВОДСТВО ПО ПРОДУКТУ"),
  "Start with the fundamentals.": r("Beginne mit den Grundlagen.", "Empieza por lo fundamental.", "Fillo me bazat.", "ابدأ بالأساسيات.", "Comece pelos fundamentos.", "Parti dalle basi.", "Начните с основ."),
  "These principles apply whether you are exploring FICONTER or already using your own workspace.": r("Diese Grundsätze gelten, egal ob du FICONTER erkundest oder bereits deinen eigenen Arbeitsbereich nutzt.", "Estos principios se aplican tanto si estás explorando FICONTER como si ya utilizas tu propio espacio.", "Këto parime vlejnë si kur po eksploron FICONTER, ashtu edhe kur po përdor tashmë hapësirën tënde.", "تنطبق هذه المبادئ سواء كنت تستكشف FICONTER أو تستخدم بالفعل مساحة عملك الخاصة.", "Estes princípios aplicam-se quer esteja a explorar a FICONTER, quer já esteja a utilizar o seu próprio espaço.", "Questi principi valgono sia se stai esplorando FICONTER sia se usi già il tuo spazio.", "Эти принципы действуют и при знакомстве с FICONTER, и при работе в собственном пространстве."),
  "ACCOUNT-SPECIFIC SUPPORT": r("KONTOSPEZIFISCHER SUPPORT", "SOPORTE ESPECÍFICO DE CUENTA", "MBËSHTETJE SPECIFIKE PËR LLOGARINË", "دعم خاص بالحساب", "SUPORTE ESPECÍFICO DA CONTA", "ASSISTENZA SPECIFICA DELL'ACCOUNT", "ПОДДЕРЖКА ПО АККАУНТУ"),
  "Already have a FICONTER account?": r("Hast du bereits ein FICONTER-Konto?", "¿Ya tienes una cuenta FICONTER?", "Ke tashmë një llogari FICONTER?", "هل لديك حساب FICONTER بالفعل؟", "Já tem uma conta FICONTER?", "Hai già un account FICONTER?", "У вас уже есть аккаунт FICONTER?"),
  "Sign in and open the private Help Center for workspace-specific guidance and secure support conversations linked to your account.": r("Melde dich an und öffne das private Help Center für arbeitsbereichsspezifische Hinweise und sichere Supportgespräche, die mit deinem Konto verknüpft sind.", "Inicia sesión y abre el Centro de Ayuda privado para obtener orientación específica de tu espacio y conversaciones de soporte seguras vinculadas a tu cuenta.", "Hyr dhe hap Qendrën private të Ndihmës për udhëzime specifike për hapësirën dhe biseda të sigurta mbështetjeje të lidhura me llogarinë tënde.", "سجّل الدخول وافتح مركز المساعدة الخاص للحصول على إرشادات خاصة بمساحة العمل ومحادثات دعم آمنة مرتبطة بحسابك.", "Inicie sessão e abra o Centro de Ajuda privado para orientação específica do espaço e conversas de suporte seguras associadas à sua conta.", "Accedi e apri il Centro assistenza privato per indicazioni specifiche dello spazio e conversazioni di supporto sicure collegate al tuo account.", "Войдите и откройте приватный Центр помощи для рекомендаций по вашему пространству и защищённых обращений поддержки, связанных с аккаунтом."),
  "Log in for private support": r("Für privaten Support anmelden", "Iniciar sesión para soporte privado", "Hyr për mbështetje private", "تسجيل الدخول للدعم الخاص", "Iniciar sessão para suporte privado", "Accedi per assistenza privata", "Войти для приватной поддержки"),
};

Object.assign(PHRASE_TRANSLATIONS, PUBLIC_HELP_TRANSLATIONS);
