import type { FiconterLanguage } from "./config";
import { LANDING_UI_TRANSLATIONS } from "./landingUiCatalog";

type NonEnglishLanguage = Exclude<FiconterLanguage, "en">;
type TranslationRow = Record<NonEnglishLanguage, string>;

function landing(
  de: string,
  es: string,
  sq: string,
  ar: string,
  pt: string,
  it: string,
  ru: string,
): TranslationRow {
  return { de, es, sq, ar, pt, it, ru };
}

/** Exact translations for the shared public header, footer and information-page chrome. */
export const PUBLIC_SITE_CHROME_TRANSLATIONS: Record<string, TranslationRow> = {
  "Platform overview": landing("Plattformübersicht", "Resumen de la plataforma", "Përmbledhja e platformës", "نظرة عامة على المنصة", "Visão geral da plataforma", "Panoramica della piattaforma", "Обзор платформы"),
  "See how FICONTER brings planning, money, wealth and intelligence together.": landing("Sieh, wie FICONTER Planung, Geld, Vermögen und Intelligenz zusammenführt.", "Descubre cómo FICONTER reúne planificación, dinero, patrimonio e inteligencia.", "Shih si FICONTER bashkon planifikimin, paratë, pasurinë dhe inteligjencën.", "اكتشف كيف تجمع FICONTER بين التخطيط والمال والثروة والذكاء المالي.", "Veja como a FICONTER reúne planeamento, dinheiro, património e inteligência.", "Scopri come FICONTER riunisce pianificazione, denaro, patrimonio e intelligenza.", "Посмотрите, как FICONTER объединяет планирование, деньги, капитал и финансовую аналитику."),
  "Planning & money": landing("Planung & Geld", "Planificación y dinero", "Planifikimi & paratë", "التخطيط والمال", "Planeamento e dinheiro", "Pianificazione e denaro", "Планирование и деньги"),
  "Transactions, bills, monthly planning, savings, debt and goals in one flow.": landing("Transaktionen, Rechnungen, Monatsplanung, Sparen, Schulden und Ziele in einem Ablauf.", "Transacciones, facturas, planificación mensual, ahorro, deuda y objetivos en un solo flujo.", "Transaksione, fatura, planifikim mujor, kursime, borxhe dhe objektiva në një rrjedhë të vetme.", "المعاملات والفواتير والتخطيط الشهري والادخار والديون والأهداف في مسار واحد.", "Transações, contas, planeamento mensal, poupanças, dívida e objetivos num único fluxo.", "Transazioni, fatture, pianificazione mensile, risparmi, debiti e obiettivi in un unico flusso.", "Транзакции, счета, ежемесячное планирование, сбережения, долги и цели в одном процессе."),
  "Financial intelligence": landing("Finanzielle Intelligenz", "Inteligencia financiera", "Inteligjenca financiare", "الذكاء المالي", "Inteligência financeira", "Intelligenza finanziaria", "Финансовая аналитика"),
  "Understand health, cash flow, reserves and the signals that deserve attention.": landing("Verstehe finanzielle Gesundheit, Cashflow, Rücklagen und die Signale, die Aufmerksamkeit verdienen.", "Comprende la salud financiera, el flujo de caja, las reservas y las señales que merecen atención.", "Kupto shëndetin financiar, rrjedhën e parasë, rezervat dhe sinjalet që kërkojnë vëmendje.", "افهم الصحة المالية والتدفق النقدي والاحتياطيات والإشارات التي تستحق الانتباه.", "Compreenda a saúde financeira, o fluxo de caixa, as reservas e os sinais que merecem atenção.", "Comprendi salute finanziaria, flusso di cassa, riserve e segnali che meritano attenzione.", "Понимайте финансовое здоровье, денежный поток, резервы и сигналы, требующие внимания."),
  "Security & control": landing("Sicherheit & Kontrolle", "Seguridad y control", "Siguria & kontrolli", "الأمان والتحكم", "Segurança e controlo", "Sicurezza e controllo", "Безопасность и контроль"),
  "Learn how private workspaces, access controls and user ownership fit together.": landing("Erfahre, wie private Arbeitsbereiche, Zugriffskontrollen und Nutzerhoheit zusammenspielen.", "Descubre cómo se combinan los espacios privados, los controles de acceso y el control del usuario.", "Mëso si lidhen hapësirat private, kontrollet e qasjes dhe pronësia e përdoruesit.", "تعرّف على كيفية تكامل مساحات العمل الخاصة وضوابط الوصول وملكية المستخدم.", "Saiba como os espaços privados, os controlos de acesso e o controlo do utilizador funcionam em conjunto.", "Scopri come spazi privati, controlli di accesso e controllo dell’utente lavorano insieme.", "Узнайте, как сочетаются приватные рабочие пространства, контроль доступа и пользовательский контроль."),
  "Personal workspace": landing("Privater Arbeitsbereich", "Espacio personal", "Hapësira personale", "مساحة العمل الشخصية", "Espaço pessoal", "Spazio personale", "Личное пространство"),
  "Household cash flow, obligations, savings, debt, goals and long-term direction.": landing("Haushalts-Cashflow, Verpflichtungen, Sparen, Schulden, Ziele und langfristige Ausrichtung.", "Flujo de caja del hogar, obligaciones, ahorro, deuda, objetivos y dirección a largo plazo.", "Rrjedha e parasë së familjes, detyrimet, kursimet, borxhet, objektivat dhe drejtimi afatgjatë.", "التدفق النقدي للأسرة والالتزامات والادخار والديون والأهداف والاتجاه طويل الأجل.", "Fluxo de caixa familiar, obrigações, poupanças, dívida, objetivos e direção a longo prazo.", "Flusso di cassa familiare, obblighi, risparmi, debiti, obiettivi e direzione a lungo termine.", "Денежный поток домохозяйства, обязательства, сбережения, долги, цели и долгосрочное направление."),
  "Business workspace": landing("Geschäftlicher Arbeitsbereich", "Espacio empresarial", "Hapësira e biznesit", "مساحة عمل الأعمال", "Espaço empresarial", "Spazio aziendale", "Бизнес-пространство"),
  "Revenue, operating costs, inventory, suppliers and reporting in a dedicated context.": landing("Umsatz, Betriebskosten, Bestand, Lieferanten und Berichte in einem eigenen Kontext.", "Ingresos, costes operativos, inventario, proveedores e informes en un contexto dedicado.", "Të ardhurat, kostot operative, inventari, furnitorët dhe raportimi në një kontekst të dedikuar.", "الإيرادات وتكاليف التشغيل والمخزون والموردون والتقارير ضمن سياق مخصص.", "Receitas, custos operacionais, inventário, fornecedores e relatórios num contexto dedicado.", "Ricavi, costi operativi, inventario, fornitori e report in un contesto dedicato.", "Выручка, операционные расходы, запасы, поставщики и отчётность в отдельном контексте."),
  "One account, two contexts": landing("Ein Konto, zwei Kontexte", "Una cuenta, dos contextos", "Një llogari, dy kontekste", "حساب واحد، سياقان", "Uma conta, dois contextos", "Un account, due contesti", "Один аккаунт, два контекста"),
  "Switch between personal and business without mixing the records that matter.": landing("Wechsle zwischen Privat und Geschäft, ohne wichtige Datensätze zu vermischen.", "Cambia entre lo personal y lo empresarial sin mezclar los registros importantes.", "Kalo mes personales dhe biznesit pa përzier të dhënat që kanë rëndësi.", "تنقّل بين الشخصي والتجاري دون خلط السجلات المهمة.", "Alterne entre pessoal e empresarial sem misturar os registos importantes.", "Passa dal personale al business senza mescolare i dati importanti.", "Переключайтесь между личным и деловым контекстом, не смешивая важные записи."),
  "Privacy overview": landing("Datenschutzübersicht", "Resumen de privacidad", "Përmbledhja e privatësisë", "نظرة عامة على الخصوصية", "Visão geral da privacidade", "Panoramica della privacy", "Обзор конфиденциальности"),
  "The principles behind FICONTER's private-by-design approach.": landing("Die Prinzipien hinter FICONTERs Ansatz „Privacy by Design“.", "Los principios del enfoque de FICONTER de privacidad desde el diseño.", "Parimet pas qasjes së FICONTER për privatësi që në dizajn.", "المبادئ وراء نهج FICONTER القائم على الخصوصية منذ التصميم.", "Os princípios por detrás da abordagem de privacidade desde a conceção da FICONTER.", "I principi alla base dell’approccio privacy-by-design di FICONTER.", "Принципы подхода FICONTER к конфиденциальности по умолчанию."),
  "Data ownership & control": landing("Datenhoheit & Kontrolle", "Propiedad y control de los datos", "Pronësia & kontrolli i të dhënave", "ملكية البيانات والتحكم", "Propriedade e controlo dos dados", "Proprietà e controllo dei dati", "Владение данными и контроль"),
  "What belongs to you, what FICONTER stores and the controls available to you.": landing("Was dir gehört, was FICONTER speichert und welche Kontrollmöglichkeiten dir zur Verfügung stehen.", "Qué te pertenece, qué almacena FICONTER y qué controles tienes disponibles.", "Çfarë të përket ty, çfarë ruan FICONTER dhe cilat kontrolle ke në dispozicion.", "ما الذي يخصك، وما الذي تخزنه FICONTER، وما أدوات التحكم المتاحة لك.", "O que lhe pertence, o que a FICONTER armazena e os controlos disponíveis para si.", "Cosa appartiene a te, cosa conserva FICONTER e quali controlli hai a disposizione.", "Что принадлежит вам, что хранит FICONTER и какие инструменты контроля доступны."),
  "Security architecture": landing("Sicherheitsarchitektur", "Arquitectura de seguridad", "Arkitektura e sigurisë", "بنية الأمان", "Arquitetura de segurança", "Architettura di sicurezza", "Архитектура безопасности"),
  "Authentication, workspace isolation and database-level access safeguards.": landing("Authentifizierung, Isolation von Arbeitsbereichen und Zugriffsschutz auf Datenbankebene.", "Autenticación, aislamiento de espacios y protecciones de acceso a nivel de base de datos.", "Autentikimi, izolimi i hapësirave dhe masat e qasjes në nivel databaze.", "المصادقة وعزل مساحات العمل وضوابط الوصول على مستوى قاعدة البيانات.", "Autenticação, isolamento de espaços e proteções de acesso ao nível da base de dados.", "Autenticazione, isolamento degli spazi e protezioni di accesso a livello database.", "Аутентификация, изоляция рабочих пространств и защита доступа на уровне базы данных."),
  "Legal privacy policy": landing("Rechtliche Datenschutzerklärung", "Política legal de privacidad", "Politika ligjore e privatësisë", "سياسة الخصوصية القانونية", "Política de privacidade legal", "Informativa legale sulla privacy", "Юридическая политика конфиденциальности"),
  "Read the formal privacy information and data-protection disclosures.": landing("Lies die formellen Datenschutzinformationen und Hinweise zum Datenschutz.", "Lee la información formal de privacidad y las divulgaciones de protección de datos.", "Lexo informacionin zyrtar të privatësisë dhe njoftimet për mbrojtjen e të dhënave.", "اقرأ معلومات الخصوصية الرسمية وإفصاحات حماية البيانات.", "Leia as informações formais de privacidade e os avisos de proteção de dados.", "Leggi le informazioni formali sulla privacy e le informative sulla protezione dei dati.", "Прочитайте официальную информацию о конфиденциальности и защите данных."),
  "Open Platform menu": landing("Plattformmenü öffnen", "Abrir menú de Plataforma", "Hap menunë e Platformës", "فتح قائمة المنصة", "Abrir menu da Plataforma", "Apri menu Piattaforma", "Открыть меню платформы"),
  "FICONTER PLATFORM": landing("FICONTER PLATTFORM", "PLATAFORMA FICONTER", "PLATFORMA FICONTER", "منصة FICONTER", "PLATAFORMA FICONTER", "PIATTAFORMA FICONTER", "ПЛАТФОРМА FICONTER"),
  "A financial control center built around decisions, not disconnected screens.": landing("Ein Finanzkontrollzentrum, das um Entscheidungen gebaut ist – nicht um voneinander getrennte Ansichten.", "Un centro de control financiero construido alrededor de decisiones, no de pantallas desconectadas.", "Një qendër kontrolli financiar e ndërtuar rreth vendimeve, jo ekraneve të shkëputura.", "مركز تحكم مالي مبني حول القرارات، لا حول شاشات منفصلة.", "Um centro de controlo financeiro construído em torno de decisões, não de ecrãs desconectados.", "Un centro di controllo finanziario costruito attorno alle decisioni, non a schermate scollegate.", "Центр финансового контроля, построенный вокруг решений, а не разрозненных экранов."),
  "Explore the full platform →": landing("Die vollständige Plattform entdecken →", "Explorar la plataforma completa →", "Eksploro platformën e plotë →", "استكشف المنصة بالكامل ←", "Explorar a plataforma completa →", "Esplora la piattaforma completa →", "Изучить всю платформу →"),
  "Open Personal and Business menu": landing("Menü Privat & Geschäft öffnen", "Abrir menú Personal y Empresa", "Hap menunë Personale dhe Biznes", "فتح قائمة الشخصي والأعمال", "Abrir menu Pessoal e Empresa", "Apri menu Personale e Business", "Открыть меню личного и делового"),
  "Personal": landing("Privat", "Personal", "Personale", "شخصي", "Pessoal", "Personale", "Личное"),
  "Business": landing("Geschäftlich", "Empresa", "Biznes", "أعمال", "Empresa", "Business", "Бизнес"),
  "Open Privacy menu": landing("Datenschutzmenü öffnen", "Abrir menú de Privacidad", "Hap menunë e Privatësisë", "فتح قائمة الخصوصية", "Abrir menu de Privacidade", "Apri menu Privacy", "Открыть меню конфиденциальности"),
  "TRUST CENTER": landing("VERTRAUENSZENTRUM", "CENTRO DE CONFIANZA", "QENDRA E BESIMIT", "مركز الثقة", "CENTRO DE CONFIANÇA", "CENTRO FIDUCIA", "ЦЕНТР ДОВЕРИЯ"),
  "Your financial workspace should be understandable, controlled and private.": landing("Dein finanzieller Arbeitsbereich sollte verständlich, kontrollierbar und privat sein.", "Tu espacio financiero debe ser comprensible, controlado y privado.", "Hapësira jote financiare duhet të jetë e kuptueshme, e kontrolluar dhe private.", "يجب أن تكون مساحة عملك المالية مفهومة وتحت سيطرتك وخاصة.", "O seu espaço financeiro deve ser compreensível, controlado e privado.", "Il tuo spazio finanziario deve essere comprensibile, controllato e privato.", "Ваше финансовое пространство должно быть понятным, контролируемым и приватным."),
  "About": landing("Über uns", "Acerca de", "Rreth nesh", "حول", "Sobre", "Chi siamo", "О нас"),
  "Close navigation": landing("Navigation schließen", "Cerrar navegación", "Mbyll navigimin", "إغلاق التنقل", "Fechar navegação", "Chiudi navigazione", "Закрыть навигацию"),
  "Open navigation": landing("Navigation öffnen", "Abrir navegación", "Hap navigimin", "فتح التنقل", "Abrir navegação", "Apri navigazione", "Открыть навигацию"),
  "Overview, planning and intelligence": landing("Übersicht, Planung und Intelligenz", "Resumen, planificación e inteligencia", "Përmbledhje, planifikim dhe inteligjencë", "نظرة عامة وتخطيط وذكاء مالي", "Visão geral, planeamento e inteligência", "Panoramica, pianificazione e intelligenza", "Обзор, планирование и аналитика"),
  "Two workspaces, one account": landing("Zwei Arbeitsbereiche, ein Konto", "Dos espacios, una cuenta", "Dy hapësira, një llogari", "مساحتا عمل، حساب واحد", "Dois espaços, uma conta", "Due spazi, un account", "Два пространства, один аккаунт"),
  "Trust, control and security": landing("Vertrauen, Kontrolle und Sicherheit", "Confianza, control y seguridad", "Besim, kontroll dhe siguri", "الثقة والتحكم والأمان", "Confiança, controlo e segurança", "Fiducia, controllo e sicurezza", "Доверие, контроль и безопасность"),
  "Why FICONTER exists": landing("Warum FICONTER existiert", "Por qué existe FICONTER", "Pse ekziston FICONTER", "لماذا توجد FICONTER", "Porque existe a FICONTER", "Perché esiste FICONTER", "Зачем существует FICONTER"),
  "Financial control for the life you are building.": landing("Finanzielle Kontrolle für das Leben, das du aufbaust.", "Control financiero para la vida que estás construyendo.", "Kontroll financiar për jetën që po ndërton.", "تحكم مالي للحياة التي تبنيها.", "Controlo financeiro para a vida que está a construir.", "Controllo finanziario per la vita che stai costruendo.", "Финансовый контроль для жизни, которую вы строите."),
  "Footer navigation": landing("Footer-Navigation", "Navegación del pie de página", "Navigimi i fundit të faqes", "تنقل تذييل الصفحة", "Navegação do rodapé", "Navigazione del piè di pagina", "Навигация в подвале"),
  "Explore": landing("Entdecken", "Explorar", "Eksploro", "استكشف", "Explorar", "Esplora", "Изучить"),
  "Access": landing("Zugang", "Acceso", "Qasje", "الوصول", "Acesso", "Accesso", "Доступ"),
  "Legal": landing("Rechtliches", "Legal", "Ligjore", "قانوني", "Legal", "Legale", "Правовая информация"),
  "Privacy Policy": landing("Datenschutzerklärung", "Política de privacidad", "Politika e privatësisë", "سياسة الخصوصية", "Política de Privacidade", "Informativa sulla privacy", "Политика конфиденциальности"),
  "Terms & Conditions": landing("Allgemeine Geschäftsbedingungen", "Términos y condiciones", "Termat & Kushtet", "الشروط والأحكام", "Termos e Condições", "Termini e condizioni", "Условия использования"),
  "Withdrawal": landing("Widerruf", "Desistimiento", "Tërheqja", "الانسحاب", "Direito de livre resolução", "Recesso", "Отказ от договора"),
  "Cookies & Technology": landing("Cookies & Technologie", "Cookies y tecnología", "Cookies & Teknologjia", "ملفات تعريف الارتباط والتقنية", "Cookies e Tecnologia", "Cookie e tecnologia", "Файлы cookie и технологии"),
  "FICONTER · Financial Control Center": landing("FICONTER · Finanzkontrollzentrum", "FICONTER · Centro de Control Financiero", "FICONTER · Qendra e Kontrollit Financiar", "FICONTER · مركز التحكم المالي", "FICONTER · Centro de Controlo Financeiro", "FICONTER · Centro di Controllo Finanziario", "FICONTER · Центр финансового контроля"),
  "Back to homepage": landing("Zurück zur Startseite", "Volver al inicio", "Kthehu te faqja kryesore", "العودة إلى الصفحة الرئيسية", "Voltar à página inicial", "Torna alla home", "Вернуться на главную"),
  "At a glance": landing("Auf einen Blick", "De un vistazo", "Me një vështrim", "في لمحة", "Em resumo", "A colpo d’occhio", "Кратко"),
  "What this means inside FICONTER.": landing("Was das innerhalb von FICONTER bedeutet.", "Qué significa esto dentro de FICONTER.", "Çfarë do të thotë kjo brenda FICONTER.", "ما الذي يعنيه ذلك داخل FICONTER.", "O que isto significa dentro da FICONTER.", "Cosa significa all’interno di FICONTER.", "Что это означает внутри FICONTER."),
  "Build a clearer financial system around your own life.": landing("Baue ein klareres Finanzsystem rund um dein eigenes Leben auf.", "Construye un sistema financiero más claro alrededor de tu propia vida.", "Ndërto një sistem financiar më të qartë rreth jetës tënde.", "ابنِ نظامًا ماليًا أوضح حول حياتك أنت.", "Construa um sistema financeiro mais claro em torno da sua própria vida.", "Costruisci un sistema finanziario più chiaro intorno alla tua vita.", "Постройте более понятную финансовую систему вокруг собственной жизни."),
  "Start with a private workspace and grow from there as your financial needs become more complex.": landing("Beginne mit einem privaten Arbeitsbereich und erweitere ihn, wenn deine finanziellen Anforderungen komplexer werden.", "Empieza con un espacio privado y amplíalo a medida que tus necesidades financieras se vuelvan más complejas.", "Fillo me një hapësirë private dhe zgjeroje ndërsa nevojat e tua financiare bëhen më komplekse.", "ابدأ بمساحة عمل خاصة وتوسّع منها مع ازدياد تعقيد احتياجاتك المالية.", "Comece com um espaço privado e expanda a partir daí à medida que as suas necessidades financeiras se tornam mais complexas.", "Inizia con uno spazio privato e amplia il sistema man mano che le tue esigenze finanziarie diventano più complesse.", "Начните с приватного пространства и расширяйте его по мере усложнения финансовых потребностей."),
  "Create your account": landing("Konto erstellen", "Crear tu cuenta", "Krijo llogarinë", "أنشئ حسابك", "Criar a sua conta", "Crea il tuo account", "Создать аккаунт"),
};

Object.assign(LANDING_UI_TRANSLATIONS, PUBLIC_SITE_CHROME_TRANSLATIONS);
