import type { FiconterLanguage } from "./config";
import { registerGlobalRuntimeTemplates } from "./globalRuntimeTemplates";

type L = Exclude<FiconterLanguage, "en">;
type Row = Record<L, string>;
const r = (de: string, es: string, sq: string, ar: string, pt: string, it: string, ru: string): Row => ({ de, es, sq, ar, pt, it, ru });

registerGlobalRuntimeTemplates({
  "{0} · {1}% data coverage": r("{0} · {1}% Datenabdeckung", "{0} · {1}% de cobertura de datos", "{0} · {1}% mbulim të dhënash", "{0} · تغطية البيانات {1}%", "{0} · {1}% de cobertura de dados", "{0} · copertura dati {1}%", "{0} · покрытие данных {1}%"),
  "Your FICONTER base currency is {0}": r("Deine FICONTER-Basiswährung ist {0}", "Tu moneda base de FICONTER es {0}", "Monedha bazë e FICONTER është {0}", "عملة FICONTER الأساسية لديك هي {0}", "A sua moeda base na FICONTER é {0}", "La tua valuta base FICONTER è {0}", "Ваша базовая валюта FICONTER — {0}"),
  "The question contains {0}, so FICONTER will not silently treat that amount as {1}.": r("Die Frage enthält {0}; FICONTER behandelt diesen Betrag daher nicht stillschweigend als {1}.", "La pregunta contiene {0}, por lo que FICONTER no tratará silenciosamente ese importe como {1}.", "Pyetja përmban {0}, prandaj FICONTER nuk do ta trajtojë në heshtje atë shumë si {1}.", "يحتوي السؤال على {0}، لذلك لن تتعامل FICONTER مع هذا المبلغ تلقائيًا على أنه {1}.", "A pergunta contém {0}, por isso a FICONTER não tratará silenciosamente esse montante como {1}.", "La domanda contiene {0}, quindi FICONTER non tratterà implicitamente quell'importo come {1}.", "В вопросе указано {0}, поэтому FICONTER не будет автоматически считать эту сумму как {1}."),
  "Ask again using {0}": r("Erneut mit {0} fragen", "Preguntar de nuevo usando {0}", "Pyet përsëri duke përdorur {0}", "اسأل مرة أخرى باستخدام {0}", "Perguntar novamente usando {0}", "Chiedi di nuovo usando {0}", "Спросить снова, используя {0}"),
  "Your current conservative capacity for a new recurring commitment is about {0} per month.": r("Deine aktuelle konservative Kapazität für eine neue wiederkehrende Verpflichtung liegt bei etwa {0} pro Monat.", "Tu capacidad conservadora actual para un nuevo compromiso recurrente es de unos {0} al mes.", "Kapaciteti yt aktual konservativ për një detyrim të ri të përsëritur është rreth {0} në muaj.", "قدرتك المحافظة الحالية على التزام متكرر جديد تبلغ نحو {0} شهريًا.", "A sua capacidade conservadora atual para um novo compromisso recorrente é de cerca de {0} por mês.", "La tua capacità prudenziale attuale per un nuovo impegno ricorrente è di circa {0} al mese.", "Текущая консервативная возможность для нового регулярного обязательства — около {0} в месяц."),
  "{0} per month is the current conservative ceiling": r("{0} pro Monat ist die aktuelle konservative Obergrenze", "{0} al mes es el límite conservador actual", "{0} në muaj është kufiri aktual konservativ", "{0} شهريًا هو الحد المحافظ الحالي", "{0} por mês é o limite conservador atual", "{0} al mese è l'attuale limite prudenziale", "{0} в месяц — текущий консервативный предел"),
  "{0} per month is within the current FICONTER planning ceiling and leaves about {1} of that ceiling unused.": r("{0} pro Monat liegt innerhalb der aktuellen FICONTER-Planungsobergrenze und lässt etwa {1} davon ungenutzt.", "{0} al mes está dentro del límite de planificación actual de FICONTER y deja unos {1} sin utilizar.", "{0} në muaj është brenda kufirit aktual të planifikimit të FICONTER dhe lë rreth {1} të papërdorur.", "{0} شهريًا يقع ضمن حد التخطيط الحالي في FICONTER ويترك نحو {1} من هذا الحد غير مستخدم.", "{0} por mês está dentro do limite atual de planeamento da FICONTER e deixa cerca de {1} desse limite por utilizar.", "{0} al mese rientra nell'attuale limite di pianificazione FICONTER e ne lascia circa {1} inutilizzati.", "{0} в месяц укладывается в текущий плановый предел FICONTER и оставляет около {1} этого предела неиспользованными."),
  "{0} per month is about {1} above the current FICONTER planning ceiling.": r("{0} pro Monat liegt etwa {1} über der aktuellen FICONTER-Planungsobergrenze.", "{0} al mes está unos {1} por encima del límite de planificación actual de FICONTER.", "{0} në muaj është rreth {1} mbi kufirin aktual të planifikimit të FICONTER.", "{0} شهريًا يزيد بنحو {1} عن حد التخطيط الحالي في FICONTER.", "{0} por mês está cerca de {1} acima do limite atual de planeamento da FICONTER.", "{0} al mese supera di circa {1} l'attuale limite di pianificazione FICONTER.", "{0} в месяц примерно на {1} выше текущего планового предела FICONTER."),
  "{0} / month": r("{0} / Monat", "{0} / mes", "{0} / muaj", "{0} / شهر", "{0} / mês", "{0} / mese", "{0} / месяц"),
  "When could you afford the {0}?": r("Wann könntest du dir {0} leisten?", "¿Cuándo podrías permitirte {0}?", "Kur mund ta përballosh {0}?", "متى يمكنك تحمل تكلفة {0}؟", "Quando poderia suportar {0}?", "Quando potresti permetterti {0}?", "Когда вы сможете позволить себе {0}?"),
  "FICONTER currently sees about {0} per month as a usable planning pace for a dedicated target without assuming that unrelated savings can be spent.": r("FICONTER sieht derzeit etwa {0} pro Monat als nutzbares Planungstempo für ein bestimmtes Ziel, ohne anzunehmen, dass andere Ersparnisse ausgegeben werden können.", "FICONTER considera actualmente unos {0} al mes como un ritmo de planificación utilizable para un objetivo específico, sin asumir que otros ahorros pueden gastarse.", "FICONTER aktualisht sheh rreth {0} në muaj si ritëm të përdorshëm planifikimi për një objektiv të dedikuar, pa supozuar se kursimet e tjera mund të shpenzohen.", "ترى FICONTER حاليًا أن نحو {0} شهريًا وتيرة تخطيط قابلة للاستخدام لهدف مخصص دون افتراض إمكانية إنفاق مدخرات غير مرتبطة.", "A FICONTER considera atualmente cerca de {0} por mês como um ritmo de planeamento utilizável para um objetivo dedicado, sem assumir que outras poupanças podem ser gastas.", "FICONTER considera attualmente circa {0} al mese come ritmo di pianificazione utilizzabile per un obiettivo dedicato, senza presumere che altri risparmi possano essere spesi.", "FICONTER сейчас считает около {0} в месяц рабочим темпом накопления на отдельную цель, не предполагая, что несвязанные с ней сбережения можно потратить."),
  "When could I afford a {0} car?": r("Wann könnte ich mir ein Auto für {0} leisten?", "¿Cuándo podría permitirme un coche de {0}?", "Kur mund ta përballoj një makinë prej {0}?", "متى يمكنني تحمل تكلفة سيارة بسعر {0}؟", "Quando poderia suportar um carro de {0}?", "Quando potrei permettermi un'auto da {0}?", "Когда я смогу позволить себе автомобиль за {0}?"),
  "How long to save {0}?": r("Wie lange dauert es, {0} zu sparen?", "¿Cuánto tardaría en ahorrar {0}?", "Sa kohë duhet për të kursyer {0}?", "كم يستغرق ادخار {0}؟", "Quanto tempo para poupar {0}?", "Quanto tempo serve per risparmiare {0}?", "Сколько времени нужно, чтобы накопить {0}?"),
  "Timeline for {0}": r("Zeitplan für {0}", "Plazo para {0}", "Afati për {0}", "الجدول الزمني لـ {0}", "Prazo para {0}", "Tempistica per {0}", "Срок для {0}"),
  "Approximately {0} months from zero dedicated funds": r("Ungefähr {0} Monate ab null zweckgebundenem Kapital", "Aproximadamente {0} meses desde cero fondos dedicados", "Afërsisht {0} muaj nga zero fonde të dedikuara", "حوالي {0} أشهر بدءًا من عدم وجود أموال مخصصة", "Aproximadamente {0} meses a partir de zero fundos dedicados", "Circa {0} mesi partendo da zero fondi dedicati", "Примерно {0} месяцев при нулевых целевых накоплениях"),
  "At the current planning pace of about {0} per month, the target would be reached around {1}.": r("Beim aktuellen Planungstempo von etwa {0} pro Monat würde das Ziel ungefähr {1} erreicht.", "Al ritmo de planificación actual de unos {0} al mes, el objetivo se alcanzaría hacia {1}.", "Me ritmin aktual të planifikimit prej rreth {0} në muaj, objektivi do të arrihej rreth {1}.", "بوتيرة التخطيط الحالية البالغة نحو {0} شهريًا، سيُبلغ الهدف تقريبًا في {1}.", "Ao ritmo atual de planeamento de cerca de {0} por mês, o objetivo seria alcançado por volta de {1}.", "Con l'attuale ritmo di pianificazione di circa {0} al mese, l'obiettivo verrebbe raggiunto intorno a {1}.", "При текущем темпе около {0} в месяц цель будет достигнута примерно к {1}."),
  "{0} months": r("{0} Monate", "{0} meses", "{0} muaj", "{0} أشهر", "{0} meses", "{0} mesi", "{0} месяцев"),
  "Around {0} if the current target-building pace is maintained.": r("Etwa {0}, wenn das aktuelle Tempo beim Zielaufbau beibehalten wird.", "Alrededor de {0} si se mantiene el ritmo actual de avance hacia el objetivo.", "Rreth {0} nëse ruhet ritmi aktual i ndërtimit të objektivit.", "حوالي {0} إذا استمرت وتيرة بناء الهدف الحالية.", "Por volta de {0} se for mantido o ritmo atual de construção do objetivo.", "Intorno a {0} se viene mantenuto l'attuale ritmo di accumulo per l'obiettivo.", "Примерно {0}, если сохранить текущий темп накопления на цель."),
  "FICONTER currently sees about {0} per month as conservative recurring capacity.": r("FICONTER sieht derzeit etwa {0} pro Monat als konservative wiederkehrende Kapazität.", "FICONTER considera actualmente unos {0} al mes como capacidad recurrente conservadora.", "FICONTER aktualisht sheh rreth {0} në muaj si kapacitet konservativ të përsëritur.", "ترى FICONTER حاليًا نحو {0} شهريًا كقدرة محافظة متكررة.", "A FICONTER considera atualmente cerca de {0} por mês como capacidade recorrente conservadora.", "FICONTER considera attualmente circa {0} al mese come capacità ricorrente prudenziale.", "FICONTER сейчас считает около {0} в месяц консервативной регулярной возможностью."),
  "When could I afford {0}?": r("Wann könnte ich mir {0} leisten?", "¿Cuándo podría permitirme {0}?", "Kur mund ta përballoj {0}?", "متى يمكنني تحمل تكلفة {0}؟", "Quando poderia suportar {0}?", "Quando potrei permettermi {0}?", "Когда я смогу позволить себе {0}?"),
  "Can you afford {0}?": r("Kannst du dir {0} leisten?", "¿Puedes permitirte {0}?", "A mund ta përballosh {0}?", "هل يمكنك تحمل تكلفة {0}؟", "Pode suportar {0}?", "Puoi permetterti {0}?", "Можете ли вы позволить себе {0}?"),
  "From zero dedicated funds, the amount equals roughly {0} months of your current target-building pace.": r("Ab null zweckgebundenem Kapital entspricht der Betrag ungefähr {0} Monaten deines aktuellen Zielaufbautempos.", "Partiendo de cero fondos dedicados, el importe equivale aproximadamente a {0} meses de tu ritmo actual de avance hacia el objetivo.", "Nga zero fonde të dedikuara, shuma barazohet me afërsisht {0} muaj të ritmit tënd aktual të ndërtimit të objektivit.", "بدءًا من عدم وجود أموال مخصصة، يعادل المبلغ نحو {0} أشهر من وتيرة بناء الهدف الحالية.", "A partir de zero fundos dedicados, o montante equivale a cerca de {0} meses do seu ritmo atual de construção do objetivo.", "Partendo da zero fondi dedicati, l'importo equivale a circa {0} mesi dell'attuale ritmo di accumulo per l'obiettivo.", "При нулевых целевых накоплениях сумма соответствует примерно {0} месяцам вашего текущего темпа накопления на цель."),
  "Approximate time from zero dedicated funds at {0} per month.": r("Ungefähre Zeit ab null zweckgebundenem Kapital bei {0} pro Monat.", "Tiempo aproximado desde cero fondos dedicados a {0} al mes.", "Koha e përafërt nga zero fonde të dedikuara me {0} në muaj.", "المدة التقريبية بدءًا من عدم وجود أموال مخصصة بمعدل {0} شهريًا.", "Tempo aproximado a partir de zero fundos dedicados a {0} por mês.", "Tempo approssimativo partendo da zero fondi dedicati a {0} al mese.", "Примерный срок при нулевых целевых накоплениях и темпе {0} в месяц."),
  "Your emergency coverage is {0} months, so FICONTER would protect near-term liquidity before aggressively redirecting every spare euro to debt.": r("Deine Notfallabdeckung beträgt {0} Monate; FICONTER würde daher kurzfristige Liquidität schützen, bevor jeder freie Euro aggressiv in Schulden umgeleitet wird.", "Tu cobertura de emergencia es de {0} meses, por lo que FICONTER protegería la liquidez a corto plazo antes de redirigir agresivamente cada euro libre a la deuda.", "Mbulimi yt i emergjencës është {0} muaj, prandaj FICONTER do të mbronte likuiditetin afatshkurtër përpara se çdo euro e lirë të drejtohej agresivisht te borxhi.", "تغطية الطوارئ لديك {0} أشهر، لذلك ستحمي FICONTER السيولة القريبة قبل توجيه كل يورو فائض بقوة نحو الديون.", "A sua cobertura de emergência é de {0} meses, pelo que a FICONTER protegeria a liquidez de curto prazo antes de redirecionar agressivamente cada euro livre para dívida.", "La tua copertura di emergenza è di {0} mesi, quindi FICONTER proteggerebbe prima la liquidità a breve termine anziché destinare aggressivamente ogni euro libero al debito.", "Ваш резерв покрывает {0} месяцев, поэтому FICONTER сначала защитит краткосрочную ликвидность, прежде чем направлять каждый свободный евро на долги."),
  "Debt payments currently use about {0}% of recorded income, while your first emergency layer is already in place.": r("Schuldenzahlungen beanspruchen derzeit etwa {0}% des erfassten Einkommens, während deine erste Notfallreserve bereits vorhanden ist.", "Los pagos de deuda utilizan actualmente cerca del {0}% de los ingresos registrados, mientras tu primera capa de emergencia ya está creada.", "Pagesat e borxhit aktualisht përdorin rreth {0}% të të ardhurave të regjistruara, ndërsa shtresa e parë e emergjencës tashmë është krijuar.", "تستهلك مدفوعات الديون حاليًا نحو {0}% من الدخل المسجل، بينما طبقة الطوارئ الأولى موجودة بالفعل.", "Os pagamentos de dívida utilizam atualmente cerca de {0}% do rendimento registado, enquanto a sua primeira camada de emergência já está criada.", "I pagamenti del debito assorbono attualmente circa il {0}% del reddito registrato, mentre il primo livello di emergenza è già presente.", "Платежи по долгам сейчас используют около {0}% зарегистрированного дохода, при этом первый уровень аварийного резерва уже создан."),
  "{0} / 100 · {1}": r("{0} / 100 · {1}", "{0} / 100 · {1}", "{0} / 100 · {1}", "{0} / 100 · {1}", "{0} / 100 · {1}", "{0} / 100 · {1}", "{0} / 100 · {1}"),
  "Your current conservative recurring decision capacity is about {0} per month. Add a price, payment or target to make the answer more specific.": r("Deine aktuelle konservative wiederkehrende Entscheidungskapazität liegt bei etwa {0} pro Monat. Füge einen Preis, eine Zahlung oder ein Ziel hinzu, um die Antwort genauer zu machen.", "Tu capacidad conservadora recurrente actual para decisiones es de unos {0} al mes. Añade un precio, pago u objetivo para obtener una respuesta más específica.", "Kapaciteti yt aktual konservativ i përsëritur për vendime është rreth {0} në muaj. Shto një çmim, pagesë ose objektiv për ta bërë përgjigjen më specifike.", "قدرتك المحافظة الحالية المتكررة لاتخاذ القرارات تبلغ نحو {0} شهريًا. أضف سعرًا أو دفعة أو هدفًا لجعل الإجابة أكثر تحديدًا.", "A sua capacidade conservadora recorrente atual para decisões é de cerca de {0} por mês. Adicione um preço, pagamento ou objetivo para tornar a resposta mais específica.", "La tua capacità prudenziale ricorrente attuale per le decisioni è di circa {0} al mese. Aggiungi un prezzo, un pagamento o un obiettivo per rendere la risposta più specifica.", "Текущая консервативная регулярная возможность для решений — около {0} в месяц. Добавьте цену, платёж или цель, чтобы получить более конкретный ответ."),
  "Added {0}": r("Hinzugefügt {0}", "Añadida {0}", "Shtuar {0}", "أُضيف {0}", "Adicionada {0}", "Aggiunta {0}", "Добавлено {0}"),
  "· Last used {0}": r("· Zuletzt verwendet {0}", "· Último uso {0}", "· Përdorur për herë të fundit {0}", "· آخر استخدام {0}", "· Última utilização {0}", "· Ultimo utilizzo {0}", "· Последнее использование {0}"),
  "{0} linked transaction": r("{0} verknüpfte Transaktion", "{0} transacción vinculada", "{0} transaksion i lidhur", "{0} معاملة مرتبطة", "{0} transação associada", "{0} transazione collegata", "{0} связанная транзакция"),
  "{0} linked transactions": r("{0} verknüpfte Transaktionen", "{0} transacciones vinculadas", "{0} transaksione të lidhura", "{0} معاملات مرتبطة", "{0} transações associadas", "{0} transazioni collegate", "{0} связанных транзакций"),
  "Display currency: {0}": r("Anzeigewährung: {0}", "Moneda de visualización: {0}", "Monedha e shfaqjes: {0}", "عملة العرض: {0}", "Moeda de apresentação: {0}", "Valuta di visualizzazione: {0}", "Валюта отображения: {0}"),
  "Base currency equivalent: {0}": r("Gegenwert in Basiswährung: {0}", "Equivalente en moneda base: {0}", "Ekuivalenti në monedhën bazë: {0}", "المعادل بالعملة الأساسية: {0}", "Equivalente na moeda base: {0}", "Equivalente nella valuta base: {0}", "Эквивалент в базовой валюте: {0}"),
  "EUR reference value: {0}": r("EUR-Referenzwert: {0}", "Valor de referencia en EUR: {0}", "Vlera referuese në EUR: {0}", "القيمة المرجعية باليورو: {0}", "Valor de referência em EUR: {0}", "Valore di riferimento EUR: {0}", "Справочное значение в EUR: {0}"),
});
