REVOKE EXECUTE ON FUNCTION public.business_member_can_manage(uuid) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.business_member_can_write(uuid) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.business_member_has_access(uuid) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.cleanup_support_request_notifications() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.create_default_ficonter_subscription() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.enforce_ficonter_beta_assignment() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.enforce_vault_recovery_dual_control() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.ficonter_apply_signup_base_currency() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.ficonter_debt_due_date(date, integer) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.ficonter_enforce_document_upload_intent_ciphertext_only() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.ficonter_enforce_financial_document_ciphertext_only() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.ficonter_enforce_transaction_template_ciphertext_only() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.ficonter_next_bill_due_date(date, text, integer, boolean) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.ficonter_safe_timezone(text) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.ficonter_sanitize_automatic_payment_run() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.ficonter_sanitize_encrypted_credit_card_row() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.ficonter_scheduled_timestamp(date, time without time zone, text) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.ficonter_transactions_scrub_server_insert() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.protect_signed_vault_recovery_document() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.protect_vault_recovery_audit_append_only() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.protect_vault_recovery_request_record() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.record_vault_recovery_verification() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.seal_vault_recovery_document_hash() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.sync_credit_card_monthly_record() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.touch_support_request_from_message() FROM PUBLIC, anon;
